// snippets/components/react/modal/41/modal.tsx
import React, { CSSProperties, ReactNode, useEffect } from 'react';

interface ModalTheme {
  overlay: string;
  background: string;
  text: string;
  border: string;
  shadow: string;
}

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  position?: 'center' | 'top' | 'bottom';
  animation?: 'fade' | 'slide' | 'zoom' | 'flip';
  title?: string;
  subtitle?: string;
  closeButton?: boolean;
  closeOnOverlay?: boolean;
  closeOnEscape?: boolean;
  header?: ReactNode;
  footer?: ReactNode;
  theme?: Partial<ModalTheme>;
  className?: string;
  children: ReactNode;
}

const defaultTheme: ModalTheme = {
  overlay: 'rgba(0, 0, 0, 0.6)',
  background: '#ffffff',
  text: '#111827',
  border: '#e5e7eb',
  shadow: 'rgba(0, 0, 0, 0.3)'
};

export const Modal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  size = 'md',
  position = 'center',
  animation = 'slide',
  title,
  subtitle,
  closeButton = true,
  closeOnOverlay = true,
  closeOnEscape = true,
  header,
  footer,
  theme = {},
  className = '',
  children
}) => {
  const appliedTheme = { ...defaultTheme, ...theme };

  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (closeOnEscape && e.key === 'Escape' && isOpen) {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener('keydown', handleEscape);
      document.body.style.overflow = 'hidden';
    }

    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = '';
    };
  }, [isOpen, closeOnEscape, onClose]);

  if (!isOpen) return null;

  const sizeMap: Record<string, string> = {
    sm: '400px',
    md: '600px',
    lg: '800px',
    xl: '1200px',
    full: 'calc(100vw - 32px)'
  };

  const positionMap: Record<string, CSSProperties> = {
    center: { alignItems: 'center', justifyContent: 'center' },
    top: { alignItems: 'flex-start', justifyContent: 'center', paddingTop: '60px' },
    bottom: { alignItems: 'flex-end', justifyContent: 'center', paddingBottom: '60px' }
  };

  const animationMap: Record<string, string> = {
    fade: 'modalFade',
    slide: 'modalSlide',
    zoom: 'modalZoom',
    flip: 'modalFlip'
  };

  const overlayStyle: CSSProperties = {
    position: 'fixed',
    inset: 0,
    backgroundColor: appliedTheme.overlay,
    backdropFilter: 'blur(4px)',
    display: 'flex',
    ...positionMap[position],
    zIndex: 9999,
    padding: '16px',
    animation: 'overlayFade 0.3s ease'
  };

  const containerStyle: CSSProperties = {
    position: 'relative',
    width: '100%',
    maxWidth: sizeMap[size],
    maxHeight: '90vh',
    backgroundColor: appliedTheme.background,
    color: appliedTheme.text,
    borderRadius: '16px',
    boxShadow: `0 20px 25px ${appliedTheme.shadow}`,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    animation: `${animationMap[animation]} 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)`,
    fontFamily: 'system-ui, -apple-system, sans-serif'
  };

  const headerStyle: CSSProperties = {
    padding: '24px',
    borderBottom: `1px solid ${appliedTheme.border}`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '16px'
  };

  const titleContainerStyle: CSSProperties = {
    flex: 1
  };

  const titleStyle: CSSProperties = {
    margin: 0,
    fontSize: '1.5rem',
    fontWeight: 700,
    lineHeight: 1.3
  };

  const subtitleStyle: CSSProperties = {
    margin: '8px 0 0',
    fontSize: '0.875rem',
    opacity: 0.7
  };

  const closeButtonStyle: CSSProperties = {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    padding: '8px',
    borderRadius: '6px',
    lineHeight: 1,
    transition: 'background 0.2s',
    color: appliedTheme.text
  };

  const bodyStyle: CSSProperties = {
    flex: 1,
    padding: '24px',
    overflowY: 'auto'
  };

  const footerStyle: CSSProperties = {
    padding: '24px',
    borderTop: `1px solid ${appliedTheme.border}`,
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end'
  };

  return (
    <>
      <style>{`
        @keyframes overlayFade {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        @keyframes modalFade {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        @keyframes modalSlide {
          from { transform: translateY(40px); opacity: 0; }
          to { transform: translateY(0); opacity: 1; }
        }
        @keyframes modalZoom {
          from { transform: scale(0.9); opacity: 0; }
          to { transform: scale(1); opacity: 1; }
        }
        @keyframes modalFlip {
          from { transform: rotateX(-20deg); opacity: 0; }
          to { transform: rotateX(0); opacity: 1; }
        }
      `}</style>
      <div
        style={overlayStyle}
        onClick={closeOnOverlay ? onClose : undefined}>
        <div
          style={containerStyle}
          className={className}
          onClick={(e) => e.stopPropagation()}>
          {(header || title || closeButton) && (
            <div style={headerStyle}>
              <div style={titleContainerStyle}>
                {title && <h2 style={titleStyle}>{title}</h2>}
                {subtitle && <p style={subtitleStyle}>{subtitle}</p>}
                {header}
              </div>
              {closeButton && (
                <button
                  style={closeButtonStyle}
                  onClick={onClose}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.background = 'rgba(0, 0, 0, 0.05)';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.background = 'none';
                  }}
                  aria-label="Close">
                  ×
                </button>
              )}
            </div>
          )}
          <div style={bodyStyle}>{children}</div>
          {footer && <div style={footerStyle}>{footer}</div>}
        </div>
      </div>
    </>
  );
};

// snippets/components/angular/modal/31/modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

interface ModalTheme {
  overlayColor: string;
  backgroundColor: string;
  textColor: string;
  borderColor: string;
  shadowColor: string;
}

type ModalSize = 'sm' | 'md' | 'lg' | 'xl' | 'full';
type ModalAnimation = 'fade' | 'slide-up' | 'slide-down' | 'zoom' | 'flip';

@Component({
  selector: 'app-modal',
  template: `
    <div *ngIf="isOpen" class="modal-overlay" [ngStyle]="overlayStyles" (click)="onOverlayClick()">
      <div class="modal-container" [ngStyle]="containerStyles" [ngClass]="animationClass" (click)="$event.stopPropagation()">
        <div *ngIf="showHeader" class="modal-header" [ngStyle]="headerStyles">
          <div class="header-content">
            <h2 *ngIf="title" class="modal-title">{{ title }}</h2>
            <p *ngIf="subtitle" class="modal-subtitle">{{ subtitle }}</p>
          </div>
          <button *ngIf="closable" class="close-button" (click)="close()" aria-label="Close">
            <span class="close-icon">&times;</span>
          </button>
        </div>

        <div class="modal-body" [ngStyle]="bodyStyles">
          <ng-content></ng-content>
        </div>

        <div *ngIf="showFooter" class="modal-footer" [ngStyle]="footerStyles">
          <ng-content select="[modalFooter]"></ng-content>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .modal-overlay {
      position: fixed;
      inset: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 1000;
      padding: 1rem;
      animation: fadeIn 0.3s ease;
    }
    @keyframes fadeIn {
      from { opacity: 0; }
      to { opacity: 1; }
    }
    .modal-container {
      position: relative;
      width: 100%;
      max-height: 90vh;
      overflow: hidden;
      display: flex;
      flex-direction: column;
    }
    .fade {
      animation: modalFade 0.3s ease;
    }
    @keyframes modalFade {
      from { opacity: 0; }
      to { opacity: 1; }
    }
    .slide-up {
      animation: slideUp 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
    }
    @keyframes slideUp {
      from { transform: translateY(100px); opacity: 0; }
      to { transform: translateY(0); opacity: 1; }
    }
    .slide-down {
      animation: slideDown 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
    }
    @keyframes slideDown {
      from { transform: translateY(-100px); opacity: 0; }
      to { transform: translateY(0); opacity: 1; }
    }
    .zoom {
      animation: zoomIn 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
    }
    @keyframes zoomIn {
      from { transform: scale(0.8); opacity: 0; }
      to { transform: scale(1); opacity: 1; }
    }
    .flip {
      animation: flipIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1);
    }
    @keyframes flipIn {
      from { transform: rotateX(-90deg); opacity: 0; }
      to { transform: rotateX(0); opacity: 1; }
    }
    .modal-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      gap: 1rem;
      flex-shrink: 0;
    }
    .header-content {
      flex: 1;
    }
    .modal-title {
      margin: 0;
      font-size: 1.5rem;
      font-weight: 700;
      line-height: 1.3;
    }
    .modal-subtitle {
      margin: 0.5rem 0 0;
      font-size: 0.875rem;
      opacity: 0.7;
    }
    .close-button {
      background: none;
      border: none;
      cursor: pointer;
      padding: 0.5rem;
      border-radius: 50%;
      transition: all 0.2s;
      line-height: 1;
    }
    .close-button:hover {
      background: rgba(0, 0, 0, 0.1);
    }
    .close-icon {
      font-size: 1.5rem;
      font-weight: 300;
    }
    .modal-body {
      flex: 1;
      overflow-y: auto;
    }
    .modal-footer {
      flex-shrink: 0;
      display: flex;
      gap: 0.75rem;
      justify-content: flex-end;
      align-items: center;
      flex-wrap: wrap;
    }
  `]
})
export class ModalComponent {
  @Input() isOpen = false;
  @Input() size: ModalSize = 'md';
  @Input() animation: ModalAnimation = 'slide-up';
  @Input() theme: Partial<ModalTheme> = {};
  @Input() title?: string;
  @Input() subtitle?: string;
  @Input() closable = true;
  @Input() closeOnOverlay = true;
  @Input() showHeader = true;
  @Input() showFooter = false;
  @Output() closeModal = new EventEmitter<void>();

  private defaultTheme: ModalTheme = {
    overlayColor: 'rgba(0, 0, 0, 0.5)',
    backgroundColor: '#ffffff',
    textColor: '#111827',
    borderColor: '#e5e7eb',
    shadowColor: 'rgba(0, 0, 0, 0.25)'
  };

  get appliedTheme(): ModalTheme {
    return { ...this.defaultTheme, ...this.theme };
  }

  get animationClass(): string {
    return this.animation;
  }

  get overlayStyles(): Record<string, string> {
    return {
      backgroundColor: this.appliedTheme.overlayColor,
      backdropFilter: 'blur(4px)'
    };
  }

  get containerStyles(): Record<string, string> {
    const t = this.appliedTheme;
    const sizeMap = {
      sm: { maxWidth: '400px' },
      md: { maxWidth: '600px' },
      lg: { maxWidth: '800px' },
      xl: { maxWidth: '1200px' },
      full: { maxWidth: 'calc(100% - 2rem)' }
    };

    return {
      ...sizeMap[this.size],
      backgroundColor: t.backgroundColor,
      color: t.textColor,
      borderRadius: '16px',
      boxShadow: `0 20px 25px ${t.shadowColor}`
    };
  }

  get headerStyles(): Record<string, string> {
    return {
      padding: '1.5rem',
      borderBottom: `1px solid ${this.appliedTheme.borderColor}`
    };
  }

  get bodyStyles(): Record<string, string> {
    return {
      padding: '1.5rem',
      color: this.appliedTheme.textColor
    };
  }

  get footerStyles(): Record<string, string> {
    return {
      padding: '1.5rem',
      borderTop: `1px solid ${this.appliedTheme.borderColor}`
    };
  }

  close(): void {
    this.closeModal.emit();
  }

  onOverlayClick(): void {
    if (this.closeOnOverlay && this.closable) {
      this.close();
    }
  }
}
