// snippets/screens/angular-ionic/loading_screen/3/loading_screen.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-loading-screen',
  template: `
    <ion-content [style.--background]="backgroundGradient" class="loading-container">
      <div class="content-wrapper">
        <!-- Loading Animation -->
        <div class="animation-container">
          <div class="pulse-ring" [style.transform]="'scale(' + pulseScale + ')'"></div>
          <div class="spinner-ring">
            <ion-spinner name="crescent" color="light"></ion-spinner>
          </div>
          <div class="inner-icon">
            <ion-icon name="bulb" [style.color]="primaryColor"></ion-icon>
          </div>
        </div>

        <!-- Title -->
        <h1 class="title">{{ title || 'Loading' }}</h1>

        <!-- Message -->
        <div class="message-container">
          <p class="message">{{ currentMessage }}</p>
        </div>

        <!-- Progress -->
        <div class="progress-container">
          <div *ngIf="showProgress" class="progress-section">
            <div *ngIf="progress !== undefined" class="progress-text">
              {{ Math.round(progress * 100) }}%
            </div>
            <ion-progress-bar
              [value]="progress || 0"
              color="light"
              class="progress-bar"
            ></ion-progress-bar>
          </div>

          <div *ngIf="!showProgress" class="dots-container">
            <div class="dot" *ngFor="let dot of [0,1,2]; let i = index" [style.animation-delay]="(i * 0.2) + 's'"></div>
          </div>
        </div>
      </div>
    </ion-content>
  `,
  styles: [`
    .loading-container {
      color: white;
    }

    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 32px;
      text-align: center;
    }

    .animation-container {
      position: relative;
      width: 80px;
      height: 80px;
      margin-bottom: 40px;
    }

    .pulse-ring {
      position: absolute;
      width: 80px;
      height: 80px;
      border-radius: 50%;
      background: rgba(255, 255, 255, 0.2);
      animation: pulse 1.5s ease-in-out infinite alternate;
    }

    @keyframes pulse {
      from { transform: scale(1); }
      to { transform: scale(1.2); }
    }

    .spinner-ring {
      position: absolute;
      top: 8px;
      left: 8px;
      width: 64px;
      height: 64px;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .inner-icon {
      position: absolute;
      top: 16px;
      left: 16px;
      width: 48px;
      height: 48px;
      background: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .inner-icon ion-icon {
      font-size: 24px;
    }

    .title {
      font-size: 28px;
      font-weight: 700;
      margin-bottom: 16px;
    }

    .message-container {
      height: 48px;
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 40px;
    }

    .message {
      font-size: 16px;
      opacity: 0.8;
      line-height: 1.4;
      max-width: 280px;
    }

    .progress-container {
      width: 100%;
      max-width: 280px;
    }

    .progress-section {
      width: 100%;
    }

    .progress-text {
      text-align: right;
      font-size: 14px;
      opacity: 0.7;
      margin-bottom: 8px;
      font-weight: 500;
    }

    .progress-bar {
      --background: rgba(255, 255, 255, 0.3);
      --progress-background: white;
      height: 4px;
      border-radius: 2px;
    }

    .dots-container {
      display: flex;
      justify-content: center;
      gap: 8px;
    }

    .dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: rgba(255, 255, 255, 0.6);
      animation: dot-pulse 1.4s ease-in-out infinite;
    }

    @keyframes dot-pulse {
      0%, 80%, 100% { opacity: 0.4; }
      40% { opacity: 1; }
    }
  `]
})
export class LoadingScreenComponent implements OnInit {
  @Input() title?: string;
  @Input() message?: string;
  @Input() showProgress = false;
  @Input() progress?: number;
  @Input() primaryColor = '#6366F1';

  currentMessageIndex = 0;
  pulseScale = 1;

  private loadingMessages = [
    'Preparing your experience...',
    'Loading AI challenges...',
    'Setting up your profile...',
    'Almost ready...'
  ];

  ngOnInit() {
    if (!this.message) {
      this.startMessageCycle();
    }
    this.startPulseAnimation();
  }

  get currentMessage(): string {
    return this.message || this.loadingMessages[this.currentMessageIndex];
  }

  get backgroundGradient(): string {
    return `linear-gradient(180deg, ${this.primaryColor} 0%, ${this.primaryColor}CC 100%)`;
  }

  private startMessageCycle() {
    setInterval(() => {
      this.currentMessageIndex = (this.currentMessageIndex + 1) % this.loadingMessages.length;
    }, 2000);
  }

  private startPulseAnimation() {
    setInterval(() => {
      this.pulseScale = this.pulseScale === 1 ? 1.2 : 1;
    }, 1500);
  }

  Math = Math;
}

// snippets/screens/react-native/loading_screen/3/loading_screen.jsx
import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Animated,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import Icon from 'react-native-vector-icons/MaterialIcons';

const LoadingScreen = ({
  title = "Loading",
  message,
  showProgress = false,
  progress,
  primaryColor = '#6366F1',
}) => {
  const [currentMessageIndex, setCurrentMessageIndex] = useState(0);
  const rotateAnim = new Animated.Value(0);
  const pulseAnim = new Animated.Value(1);

  const loadingMessages = [
    "Preparing your experience...",
    "Loading AI challenges...",
    "Setting up your profile...",
    "Almost ready..."
  ];

  useEffect(() => {
    // Rotation animation
    Animated.loop(
      Animated.timing(rotateAnim, {
        toValue: 1,
        duration: 2000,
        useNativeDriver: true,
      })
    ).start();

    // Pulse animation
    Animated.loop(
      Animated.sequence([
        Animated.timing(pulseAnim, {
          toValue: 1.2,
          duration: 1500,
          useNativeDriver: true,
        }),
        Animated.timing(pulseAnim, {
          toValue: 1,
          duration: 1500,
          useNativeDriver: true,
        }),
      ])
    ).start();

    // Message cycling
    if (!message) {
      const interval = setInterval(() => {
        setCurrentMessageIndex((prev) => (prev + 1) % loadingMessages.length);
      }, 2000);

      return () => clearInterval(interval);
    }
  }, [message]);

  const spin = rotateAnim.interpolate({
    inputRange: [0, 1],
    outputRange: ['0deg', '360deg'],
  });

  return (
    <LinearGradient
      colors={[primaryColor, `${primaryColor}CC`]}
      style={styles.container}
    >
      <View style={styles.content}>
        {/* Loading Animation */}
        <View style={styles.animationContainer}>
          <Animated.View
            style={[
              styles.pulseRing,
              {
                transform: [{ scale: pulseAnim }],
              },
            ]}
          />

          <Animated.View
            style={[
              styles.spinnerRing,
              {
                transform: [{ rotate: spin }],
              },
            ]}
          />

          <View style={styles.innerIcon}>
            <Icon name="psychology" size={24} color={primaryColor} />
          </View>
        </View>

        {/* Title */}
        <Text style={styles.title}>{title}</Text>

        {/* Message */}
        <View style={styles.messageContainer}>
          <Text style={styles.message}>
            {message || loadingMessages[currentMessageIndex]}
          </Text>
        </View>

        {/* Progress */}
        <View style={styles.progressContainer}>
          {showProgress ? (
            <View style={styles.progressBarContainer}>
              {progress !== undefined && (
                <View style={styles.progressTextContainer}>
                  <Text style={styles.progressText}>
                    {Math.round(progress * 100)}%
                  </Text>
                </View>
              )}
              <View style={styles.progressTrack}>
                <View
                  style={[
                    styles.progressBar,
                    { width: `${(progress || 0) * 100}%` },
                  ]}
                />
              </View>
            </View>
          ) : (
            <View style={styles.dotsContainer}>
              {[0, 1, 2].map((i) => (
                <View key={i} style={styles.dot} />
              ))}
            </View>
          )}
        </View>
      </View>
    </LinearGradient>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  content: {
    alignItems: 'center',
    width: '100%',
    maxWidth: 280,
  },
  animationContainer: {
    position: 'relative',
    width: 80,
    height: 80,
    marginBottom: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pulseRing: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  spinnerRing: {
    position: 'absolute',
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 3,
    borderColor: 'white',
    borderTopColor: 'transparent',
  },
  innerIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 16,
  },
  messageContainer: {
    height: 48,
    justifyContent: 'center',
    marginBottom: 40,
  },
  message: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    lineHeight: 22,
  },
  progressContainer: {
    width: '100%',
  },
  progressBarContainer: {
    width: '100%',
  },
  progressTextContainer: {
    alignItems: 'flex-end',
    marginBottom: 8,
  },
  progressText: {
    fontSize: 14,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.7)',
  },
  progressTrack: {
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: 'white',
    borderRadius: 2,
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    marginHorizontal: 4,
  },
});

export default LoadingScreen;
