// snippets/components/react/modal/6/modal.tsx
import React, { useEffect, useRef, CSSProperties, ReactNode } from 'react';

export interface ModalTheme {
  background: string;
  overlay: string;
  border: string;
  shadow: string;
}

export interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title?: string;
  children: ReactNode;
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  variant?: 'default' | 'centered' | 'drawer' | 'fullscreen' | 'bottom-sheet';
  closeOnOverlay?: boolean;
  closeOnEsc?: boolean;
  showCloseButton?: boolean;
  theme?: Partial<ModalTheme>;
}

const defaultTheme: ModalTheme = {
  background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  overlay: 'rgba(240, 147, 251, 0.2)',
  border: 'rgba(255, 255, 255, 0.5)',
  shadow: 'rgba(245, 87, 108, 0.4)'
};

export const Modal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  title = 'Gradient Modal',
  children,
  size = 'md',
  variant = 'centered',
  closeOnOverlay = true,
  closeOnEsc = true,
  showCloseButton = true,
  theme = {}
}) => {
  const appliedTheme = { ...defaultTheme, ...theme };
  const modalRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => {
      if (closeOnEsc && e.key === 'Escape') {
        onClose();
      }
    };
    if (isOpen) {
      document.addEventListener('keydown', handleEsc);
    }
    return () => document.removeEventListener('keydown', handleEsc);
  }, [isOpen, closeOnEsc, onClose]);

  useEffect(() => {
    if (!isOpen || !modalRef.current) return;

    const focusableElements = modalRef.current.querySelectorAll(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
    const firstElement = focusableElements[0] as HTMLElement;
    const lastElement = focusableElements[focusableElements.length - 1] as HTMLElement;

    const handleTab = (e: KeyboardEvent) => {
      if (e.key !== 'Tab') return;

      if (e.shiftKey) {
        if (document.activeElement === firstElement) {
          lastElement?.focus();
          e.preventDefault();
        }
      } else {
        if (document.activeElement === lastElement) {
          firstElement?.focus();
          e.preventDefault();
        }
      }
    };

    document.addEventListener('keydown', handleTab);
    return () => document.removeEventListener('keydown', handleTab);
  }, [isOpen]);

  if (!isOpen) return null;

  const sizeMap: Record<string, CSSProperties> = {
    sm: { maxWidth: '450px', width: '90%' },
    md: { maxWidth: '620px', width: '90%' },
    lg: { maxWidth: '880px', width: '90%' },
    xl: { maxWidth: '1150px', width: '95%' },
    full: { maxWidth: '98vw', width: '98%', height: '98vh' }
  };

  const overlayStyle: CSSProperties = {
    position: 'fixed',
    inset: 0,
    background: appliedTheme.overlay,
    backdropFilter: 'blur(12px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    animation: 'fadeIn 0.3s ease-out'
  };

  const modalStyle: CSSProperties = {
    ...sizeMap[size],
    background: 'rgba(255, 255, 255, 0.95)',
    borderRadius: '24px',
    boxShadow: `0 20px 60px ${appliedTheme.shadow}`,
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '88vh',
    animation: 'flipIn 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
    border: `2px solid ${appliedTheme.border}`,
    position: 'relative',
    overflow: 'hidden'
  };

  const gradientBar: CSSProperties = {
    height: '6px',
    background: appliedTheme.background,
    width: '100%'
  };

  const headerStyle: CSSProperties = {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '26px 32px',
    borderBottom: `2px solid #fce7f3`
  };

  const titleStyle: CSSProperties = {
    margin: 0,
    fontSize: '25px',
    fontWeight: 800,
    background: appliedTheme.background,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '-0.6px'
  };

  const closeButtonStyle: CSSProperties = {
    background: appliedTheme.background,
    border: 'none',
    borderRadius: '50%',
    width: '38px',
    height: '38px',
    fontSize: '20px',
    cursor: 'pointer',
    color: '#fff',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: `0 4px 14px ${appliedTheme.shadow}`
  };

  const contentStyle: CSSProperties = {
    padding: '32px',
    flex: 1,
    overflow: 'auto',
    fontSize: '16px',
    lineHeight: 1.7,
    color: '#374151'
  };

  const footerStyle: CSSProperties = {
    padding: '22px 32px',
    borderTop: '2px solid #fce7f3',
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
    background: '#fef3f8'
  };

  const buttonStyle: CSSProperties = {
    padding: '12px 30px',
    borderRadius: '12px',
    border: 'none',
    fontSize: '15px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease'
  };

  const primaryButtonStyle: CSSProperties = {
    ...buttonStyle,
    background: appliedTheme.background,
    color: '#fff',
    boxShadow: `0 4px 14px ${appliedTheme.shadow}`
  };

  const secondaryButtonStyle: CSSProperties = {
    ...buttonStyle,
    background: '#fce7f3',
    color: '#ec4899'
  };

  return (
    <>
      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        @keyframes flipIn {
          0% { opacity: 0; transform: perspective(800px) rotateY(-90deg); }
          50% { opacity: 1; transform: perspective(800px) rotateY(10deg); }
          100% { opacity: 1; transform: perspective(800px) rotateY(0deg); }
        }
        .modal-v6-close-btn:hover {
          transform: scale(1.12) rotate(90deg);
          box-shadow: 0 6px 20px ${appliedTheme.shadow};
        }
        .modal-v6-primary-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 6px 20px ${appliedTheme.shadow};
        }
        .modal-v6-secondary-btn:hover {
          background: #fbcfe8;
          transform: translateY(-2px);
        }
      `}</style>
      <div style={overlayStyle} onClick={closeOnOverlay ? onClose : undefined}>
        <div ref={modalRef} style={modalStyle} onClick={(e) => e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="modal-title">
          <div style={gradientBar} />
          <div style={headerStyle}>
            <h2 id="modal-title" style={titleStyle}>{title}</h2>
            {showCloseButton && (
              <button
                className="modal-v6-close-btn"
                style={closeButtonStyle}
                onClick={onClose}
                aria-label="Close modal"
              >
                ✕
              </button>
            )}
          </div>

          <div style={contentStyle}>{children}</div>

          <div style={footerStyle}>
            <button className="modal-v6-secondary-btn" style={secondaryButtonStyle} onClick={onClose}>
              Cancel
            </button>
            <button className="modal-v6-primary-btn" style={primaryButtonStyle} onClick={onClose}>
              Continue
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

// snippets/components/svelte/modal/2/modal.svelte
<script lang="ts">
  import { fade, fly } from 'svelte/transition';
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';

  export interface ModalTheme {
    background?: string;
    overlay?: string;
    border?: string;
    shadow?: string;
  }

  export let isOpen = false;
  export let title = 'Modal';
  export let size: 'sm' | 'md' | 'lg' | 'xl' | 'full' = 'md';
  export let variant: 'default' | 'centered' | 'drawer' | 'fullscreen' | 'bottom-sheet' = 'drawer';
  export let closeOnOverlay = true;
  export let closeOnEsc = true;
  export let showCloseButton = true;
  export let theme: ModalTheme = {};

  const dispatch = createEventDispatcher();

  const defaultTheme: ModalTheme = {
    background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    overlay: 'rgba(245, 87, 108, 0.3)',
    border: '#f5576c',
    shadow: '0 20px 60px rgba(245, 87, 108, 0.4)'
  };

  $: appliedTheme = { ...defaultTheme, ...theme };
  $: modalWidth = size === 'sm' ? '350px' : size === 'md' ? '450px' : size === 'lg' ? '550px' : size === 'xl' ? '650px' : '100%';

  function handleKeydown(event: KeyboardEvent) {
    if (closeOnEsc && event.key === 'Escape' && isOpen) {
      close();
    }
  }

  function handleOverlayClick() {
    if (closeOnOverlay) {
      close();
    }
  }

  function close() {
    isOpen = false;
    dispatch('close');
  }

  onMount(() => {
    document.addEventListener('keydown', handleKeydown);
    return () => {
      document.removeEventListener('keydown', handleKeydown);
    };
  });

  $: if (isOpen) {
    document.body.style.overflow = 'hidden';
  } else {
    document.body.style.overflow = '';
  }

  onDestroy(() => {
    document.body.style.overflow = '';
  });
</script>

{#if isOpen}
  <div class="modal-overlay" style="background: {appliedTheme.overlay};" on:click={handleOverlayClick} transition:fade={{ duration: 250 }}>
    <div class="modal-drawer" style="width: {modalWidth}; background: {appliedTheme.background}; border-left: 3px solid {appliedTheme.border}; box-shadow: {appliedTheme.shadow};" on:click|stopPropagation transition:fly={{ x: 300, duration: 400 }}>
      <div class="modal-header">
        <h2>{title}</h2>
        {#if showCloseButton}
          <button class="close-btn" on:click={close}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <line x1="18" y1="6" x2="6" y2="18"></line>
              <line x1="6" y1="6" x2="18" y2="18"></line>
            </svg>
          </button>
        {/if}
      </div>

      <div class="modal-body">
        <slot />
      </div>

      <div class="modal-footer">
        <slot name="footer">
          <button class="btn-cancel" on:click={close}>Cancel</button>
          <button class="btn-primary">Confirm</button>
        </slot>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1000;
    backdrop-filter: blur(2px);
  }

  .modal-drawer {
    position: fixed;
    top: 0;
    right: 0;
    height: 100%;
    overflow-y: auto;
    color: white;
    display: flex;
    flex-direction: column;
  }

  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 2rem 1.5rem 1rem;
    border-bottom: 1px solid rgba(255, 255, 255, 0.15);
  }

  .modal-header h2 {
    margin: 0;
    font-size: 1.75rem;
    font-weight: 800;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .close-btn {
    background: transparent;
    border: 2px solid rgba(255, 255, 255, 0.3);
    cursor: pointer;
    color: white;
    width: 36px;
    height: 36px;
    border-radius: 8px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.3s;
  }

  .close-btn:hover {
    background: rgba(255, 255, 255, 0.2);
    border-color: rgba(255, 255, 255, 0.5);
    transform: scale(1.1);
  }

  .modal-body {
    flex: 1;
    padding: 1.5rem;
    overflow-y: auto;
  }

  .modal-footer {
    padding: 1.5rem;
    border-top: 1px solid rgba(255, 255, 255, 0.15);
    display: flex;
    justify-content: flex-end;
    gap: 1rem;
  }

  .btn-cancel {
    padding: 0.75rem 1.25rem;
    background: transparent;
    border: 2px solid rgba(255, 255, 255, 0.4);
    border-radius: 10px;
    color: white;
    cursor: pointer;
    font-weight: 600;
    transition: all 0.3s;
  }

  .btn-cancel:hover {
    background: rgba(255, 255, 255, 0.1);
  }

  .btn-primary {
    padding: 0.75rem 1.25rem;
    background: rgba(255, 255, 255, 0.25);
    border: 2px solid rgba(255, 255, 255, 0.5);
    border-radius: 10px;
    color: white;
    cursor: pointer;
    font-weight: 600;
    transition: all 0.3s;
  }

  .btn-primary:hover {
    background: rgba(255, 255, 255, 0.35);
    transform: translateY(-2px);
  }


@keyframes fade {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes expand {
  from { transform: scale(0.9); opacity: 0; }
  to { transform: scale(1); opacity: 1; }
}
</style>
