// snippets/components/react/tabs/13/tabs.tsx
import React, { useState } from 'react';

export interface ComponentProps {
  theme?: {
    primary?: string;
    background?: string;
    text?: string;
  };
  className?: string;
  onInteract?: (type: string) => void;
}

export const Component: React.FC<ComponentProps> = ({
  theme = {},
  className = '',
  onInteract
}) => {
  const [state, setState] = useState({ active: false, hovered: false });

  const primary = theme.primary || '#ef4444';
  const background = theme.background || '#ffffff';
  const text = theme.text || '#1f2937';

  return (
    <div
      className={className}
      onClick={() => {
        setState(s => ({ ...s, active: !s.active }));
        onInteract?.('interact');
      }}
      onMouseEnter={() => setState(s => ({ ...s, hovered: true }))}
      onMouseLeave={() => setState(s => ({ ...s, hovered: false }))}
      style={{
        padding: '18px 36px',
        backgroundColor: state.active ? primary : background,
        color: state.active ? '#fff' : text,
        borderRadius: '12px',
        border: `${state.hovered ? 2 : 1}px solid ${state.active ? primary : '#e5e7eb'}`,
        boxShadow: state.hovered ? '0 4px 8px rgba(0,0,0,0.10)' : '0 12px 24px rgba(0,0,0,0.20)',
        transform: state.hovered ? 'translateY(-2px) scale(1.02)' : 'translateY(0) scale(1)',
        transition: `all 400ms cubic-bezier(0.4, 0, 0.2, 1)`,
        cursor: 'pointer',
        fontSize: '19px',
        fontWeight: 700,
        userSelect: 'none' as const
      }}
    >
      tabs - variant 13
    </div>
  );
};

// snippets/components/angular/tabs/6/tabs.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

interface Theme {
  primaryColor: string;
  backgroundColor: string;
  textColor: string;
  borderColor: string;
}

@Component({
  selector: 'app-tabs',
  template: `
  <div
  [ngStyle]="styles"
  (click)="handleClick()"
  (mouseenter)="hovered = true"
  (mouseleave)="hovered = false"
  class="tabs-container">
  <ng-content></ng-content>
  <span *ngIf="active" class="indicator">✓</span>
  </div>
  `,
  styles: [`
  .tabs-container {
  cursor: pointer;
  transition: all 310ms cubic-bezier(0.4, 0, 0.2, 1);
  user-select: none;
  position: relative;
  }
  .indicator {
  margin-left: 8px;
  opacity: 0.8;
  font-size: 14px;
  }
  `]
})
export class TabsComponent {
  @Input() theme: Partial<Theme> = {};
  @Input() variant = 'default';
  @Output() interact = new EventEmitter<string>();

  active = false;
  hovered = false;

  private defaultTheme: Theme = {
  primaryColor: '#6366f1',
  backgroundColor: '#ffffff',
  textColor: '#1f2937',
  borderColor: '#e5e7eb'
  };

  get appliedTheme(): Theme {
  return { ...this.defaultTheme, ...this.theme };
  }

  get styles() {
  const t = this.appliedTheme;
  return {
  padding: '18px 26px',
  background: this.active ? t.primaryColor : t.backgroundColor,
  color: this.active ? '#ffffff' : t.textColor,
  border: `2px solid ${this.hovered ? t.primaryColor : t.borderColor}`,
  borderRadius: '8px',
  fontSize: '16px',
  fontWeight: 500,
  boxShadow: this.hovered ? `0 14px 22px ${t.primaryColor}40` : '0 2px 8px rgba(0,0,0,0.08)',
  transform: this.hovered ? 'translateY(-4px)' : 'translateY(0)',
  display: 'inline-flex',
  alignItems: 'center',
  gap: '8px'
  };
  }

  handleClick(): void {
  this.active = !this.active;
  this.interact.emit('tabs_v6');
  }
}
