// snippets/components/vue/table/1/table.vue
<template>
  <div class="table-container" :style="containerStyles">
    <!-- Search Bar -->
    <div class="table-header">
      <input
        v-model="searchQuery"
        type="text"
        placeholder="Search..."
        class="search-input"
        :style="searchStyles"
      />
    </div>
    <!-- Table -->
    <div class="table-wrapper">
      <table class="data-table" :style="tableStyles">
        <thead :style="theadStyles">
          <tr>
            <th v-if="selectable" class="select-column" :style="thStyles">
              <input
                type="checkbox"
                :checked="allSelected"
                @change="toggleSelectAll"
                class="checkbox"
              />
            </th>
            <th
              v-for="column in columns"
              :key="column.key"
              :style="{ ...thStyles, width: column.width || 'auto' }"
              @click="column.sortable ? toggleSort(column.key) : null"
              :class="{ sortable: column.sortable }"
            >
              {{ column.label }}
              <span v-if="column.sortable && sortKey === column.key" class="sort-icon">
                {{ sortOrder === 'asc' ? '▲' : '▼' }}
              </span>
            </th>
            <th v-if="hasActions" :style="thStyles" class="actions-column">Actions</th>
          </tr>
        </thead>
        <tbody v-if="!loading">
          <template v-if="paginatedData.length > 0">
            <template v-for="(row, index) in paginatedData" :key="row.id || index">
              <tr
                :style="getTrStyles(index)"
                :class="{ selected: selectedRows.includes(row.id || index) }"
                @click="expandableRows ? toggleExpand(row.id || index) : null"
              >
                <td v-if="selectable" :style="tdStyles">
                  <input
                    type="checkbox"
                    :checked="selectedRows.includes(row.id || index)"
                    @change="toggleSelect(row.id || index)"
                    @click.stop
                    class="checkbox"
                  />
                </td>
                <td
                  v-for="column in columns"
                  :key="column.key"
                  :style="tdStyles"
                >
                  {{ row[column.key] }}
                </td>
                <td v-if="hasActions" :style="tdStyles">
                  <div class="action-buttons">
                    <button
                      @click.stop="$emit('edit', row)"
                      class="action-btn edit-btn"
                      :style="editBtnStyles"
                    >
                      Edit
                    </button>
                    <button
                      @click.stop="$emit('delete', row)"
                      class="action-btn delete-btn"
                      :style="deleteBtnStyles"
                    >
                      Delete
                    </button>
                  </div>
                </td>
              </tr>
              <tr
                v-if="expandableRows && expandedRows.includes(row.id || index)"
                :style="expandedRowStyles"
              >
                <td :colspan="totalColumns" :style="tdStyles">
                  <div class="expanded-content">
                    <slot name="expanded" :row="row">
                      <pre>{{ JSON.stringify(row, null, 2) }}</pre>
                    </slot>
                  </div>
                </td>
              </tr>
            </template>
          </template>
          <tr v-else>
            <td :colspan="totalColumns" :style="{ ...tdStyles, textAlign: 'center', padding: '2rem' }">
              <div class="empty-state">No data available</div>
            </td>
          </tr>
        </tbody>
        <tbody v-else>
          <tr v-for="i in 5" :key="i" :style="getTrStyles(i)">
            <td v-if="selectable" :style="tdStyles">
              <div class="skeleton"></div>
            </td>
            <td v-for="column in columns" :key="column.key" :style="tdStyles">
              <div class="skeleton"></div>
            </td>
            <td v-if="hasActions" :style="tdStyles">
              <div class="skeleton"></div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- Pagination -->
    <div v-if="pagination && !loading" class="pagination" :style="paginationStyles">
      <button
        @click="currentPage--"
        :disabled="currentPage === 1"
        class="page-btn"
        :style="pageBtnStyles"
      >
        Previous
      </button>
      <span class="page-info">
        Page {{ currentPage }} of {{ totalPages }}
      </span>
      <button
        @click="currentPage++"
        :disabled="currentPage === totalPages"
        class="page-btn"
        :style="pageBtnStyles"
      >
        Next
      </button>
    </div>
  </div>
</template>
<script lang="ts">
import { ref, computed, watch } from 'vue';
export default {
  name: 'StripedModernTable',
  props: {
    columns: {
      type: Array,
      required: true,
      // Example: [{ key: 'name', label: 'Name', sortable: true, width: '200px' }]
    },
    data: {
      type: Array,
      required: true,
    },
    sortable: {
      type: Boolean,
      default: true,
    },
    selectable: {
      type: Boolean,
      default: false,
    },
    pagination: {
      type: Boolean,
      default: true,
    },
    loading: {
      type: Boolean,
      default: false,
    },
    theme: {
      type: Object,
      default: () => ({
        primary: '#6366f1',
        background: '#ffffff',
        border: '#e5e7eb',
        headerColor: '#1f2937',
        rowHover: '#f3f4f6',
      }),
    },
    expandableRows: {
      type: Boolean,
      default: false,
    },
    hasActions: {
      type: Boolean,
      default: true,
    },
    itemsPerPage: {
      type: Number,
      default: 10,
    },
  },
  emits: ['edit', 'delete', 'selection-change'],
  setup(props, { emit }) {
    const searchQuery = ref('');
    const sortKey = ref('');
    const sortOrder = ref('asc');
    const currentPage = ref(1);
    const selectedRows = ref([]);
    const expandedRows = ref([]);
    const filteredData = computed(() => {
      if (!searchQuery.value) return props.data;
      return props.data.filter(row => {
        return props.columns.some(column => {
          const value = row[column.key];
          return value && value.toString().toLowerCase().includes(searchQuery.value.toLowerCase());
        });
      });
    });
    const sortedData = computed(() => {
      if (!sortKey.value) return filteredData.value;
      return [...filteredData.value].sort((a, b) => {
        const aVal = a[sortKey.value];
        const bVal = b[sortKey.value];
        if (aVal < bVal) return sortOrder.value === 'asc' ? -1 : 1;
        if (aVal > bVal) return sortOrder.value === 'asc' ? 1 : -1;
        return 0;
      });
    });
    const totalPages = computed(() => {
      if (!props.pagination) return 1;
      return Math.ceil(sortedData.value.length / props.itemsPerPage);
    });
    const paginatedData = computed(() => {
      if (!props.pagination) return sortedData.value;
      const start = (currentPage.value - 1) * props.itemsPerPage;
      const end = start + props.itemsPerPage;
      return sortedData.value.slice(start, end);
    });
    const allSelected = computed(() => {
      return paginatedData.value.length > 0 &&
        paginatedData.value.every(row => selectedRows.value.includes(row.id || paginatedData.value.indexOf(row)));
    });
    const totalColumns = computed(() => {
      let count = props.columns.length;
      if (props.selectable) count++;
      if (props.hasActions) count++;
      return count;
    });
    const toggleSort = (key) => {
      if (sortKey.value === key) {
        sortOrder.value = sortOrder.value === 'asc' ? 'desc' : 'asc';
      } else {
        sortKey.value = key;
        sortOrder.value = 'asc';
      }
    };
    const toggleSelect = (rowId) => {
      const index = selectedRows.value.indexOf(rowId);
      if (index > -1) {
        selectedRows.value.splice(index, 1);
      } else {
        selectedRows.value.push(rowId);
      }
      emit('selection-change', selectedRows.value);
    };
    const toggleSelectAll = () => {
      if (allSelected.value) {
        selectedRows.value = [];
      } else {
        selectedRows.value = paginatedData.value.map((row, index) => row.id || index);
      }
      emit('selection-change', selectedRows.value);
    };
    const toggleExpand = (rowId) => {
      const index = expandedRows.value.indexOf(rowId);
      if (index > -1) {
        expandedRows.value.splice(index, 1);
      } else {
        expandedRows.value.push(rowId);
      }
    };
    watch(() => props.data, () => {
      currentPage.value = 1;
      selectedRows.value = [];
    });
    // Styles
    const containerStyles = computed(() => ({
      backgroundColor: props.theme.background,
      borderRadius: '12px',
      overflow: 'hidden',
      boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    }));
    const searchStyles = computed(() => ({
      border: `1px solid ${props.theme.border}`,
      color: props.theme.headerColor,
    }));
    const tableStyles = computed(() => ({
      borderCollapse: 'separate',
      borderSpacing: 0,
    }));
    const theadStyles = computed(() => ({
      backgroundColor: props.theme.primary,
      color: '#ffffff',
      position: 'sticky',
      top: 0,
      zIndex: 10,
    }));
    const thStyles = computed(() => ({
      padding: '1rem',
      textAlign: 'left',
      fontWeight: '600',
      fontSize: '0.875rem',
      textTransform: 'uppercase',
      letterSpacing: '0.05em',
      borderBottom: `2px solid ${props.theme.border}`,
    }));
    const tdStyles = computed(() => ({
      padding: '1rem',
      borderBottom: `1px solid ${props.theme.border}`,
      color: props.theme.headerColor,
    }));
    const getTrStyles = (index) => ({
      backgroundColor: index % 2 === 0 ? '#ffffff' : '#f9fafb',
      transition: 'background-color 0.2s',
    });
    const editBtnStyles = computed(() => ({
      backgroundColor: props.theme.primary,
      color: '#ffffff',
    }));
    const deleteBtnStyles = computed(() => ({
      backgroundColor: '#ef4444',
      color: '#ffffff',
    }));
    const paginationStyles = computed(() => ({
      borderTop: `1px solid ${props.theme.border}`,
      color: props.theme.headerColor,
    }));
    const pageBtnStyles = computed(() => ({
      backgroundColor: props.theme.primary,
      color: '#ffffff',
    }));
    const expandedRowStyles = computed(() => ({
      backgroundColor: '#f9fafb',
    }));
    return {
      searchQuery,
      sortKey,
      sortOrder,
      currentPage,
      selectedRows,
      expandedRows,
      paginatedData,
      allSelected,
      totalPages,
      totalColumns,
      toggleSort,
      toggleSelect,
      toggleSelectAll,
      toggleExpand,
      containerStyles,
      searchStyles,
      tableStyles,
      theadStyles,
      thStyles,
      tdStyles,
      getTrStyles,
      editBtnStyles,
      deleteBtnStyles,
      paginationStyles,
      pageBtnStyles,
      expandedRowStyles,
    };
  },
};
</script>
<style scoped>
.table-container {
  font-family: system-ui, -apple-system, sans-serif;
}
.table-header {
  padding: 1.5rem;
  border-bottom: 1px solid #e5e7eb;
}
.search-input {
  width: 100%;
  max-width: 400px;
  padding: 0.625rem 1rem;
  border-radius: 8px;
  font-size: 0.875rem;
  outline: none;
  transition: border-color 0.2s;
}
.search-input:focus {
  border-color: #6366f1;
  box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1);
}
.table-wrapper {
  overflow-x: auto;
  max-height: 600px;
  overflow-y: auto;
}
.data-table {
  width: 100%;
  min-width: 600px;
}
.data-table thead th.sortable {
  cursor: pointer;
  user-select: none;
}
.data-table thead th.sortable:hover {
  background-color: rgba(0, 0, 0, 0.1);
}
.sort-icon {
  margin-left: 0.5rem;
  font-size: 0.75rem;
}
.data-table tbody tr:hover {
  background-color: #f3f4f6 !important;
}
.data-table tbody tr.selected {
  background-color: rgba(99, 102, 241, 0.1) !important;
}
.checkbox {
  width: 1rem;
  height: 1rem;
  cursor: pointer;
  accent-color: #6366f1;
}
.action-buttons {
  display: flex;
  gap: 0.5rem;
}
.action-btn {
  padding: 0.375rem 0.75rem;
  border: none;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  transition: opacity 0.2s;
}
.action-btn:hover {
  opacity: 0.8;
}
.action-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.pagination {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 1.5rem;
  gap: 1rem;
}
.page-info {
  font-size: 0.875rem;
  font-weight: 500;
}
.page-btn {
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  transition: opacity 0.2s;
}
.page-btn:hover:not(:disabled) {
  opacity: 0.8;
}
.page-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.empty-state {
  font-size: 0.875rem;
  color: #9ca3af;
}
.skeleton {
  height: 1rem;
  background: linear-gradient(90deg, #f3f4f6 25%, #e5e7eb 50%, #f3f4f6 75%);
  background-size: 200% 100%;
  animation: loading 1.5s infinite;
  border-radius: 4px;
}
@keyframes loading {
  0% {
    background-position: 200% 0;
  }
  100% {
    background-position: -200% 0;
  }
}
.expanded-content {
  padding: 1rem;
  background-color: #ffffff;
  border-radius: 8px;
  margin: 0.5rem;
}
.select-column,
.actions-column {
  width: 100px;
}
</style>

// snippets/components/angular/table/2/table.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

interface TableTheme {
  primaryColor: string;
  secondaryColor: string;
  backgroundColor: string;
  textColor: string;
  borderColor: string;
  headerBgColor: string;
  hoverColor: string;
}

interface TableColumn {
  key: string;
  label: string;
  sortable?: boolean;
  width?: string;
}

interface TableRow {
  [key: string]: any;
  id: string | number;
}

@Component({
  selector: 'app-table',
  template: `
    <div [ngStyle]="containerStyles" class="table-container">
      <!-- Search Bar -->
      <div *ngIf="searchable" [ngStyle]="searchBarStyles">
        <input
          type="text"
          [ngStyle]="searchInputStyles"
          [(ngModel)]="searchTerm"
          (input)="onSearch()"
          placeholder="Search..."
          aria-label="Search table">
      </div>

      <!-- Loading State -->
      <div *ngIf="loading" [ngStyle]="loadingStyles">
        <div [ngStyle]="spinnerStyles"></div>
        <p>Loading data...</p>
      </div>

      <!-- Table -->
      <div *ngIf="!loading" [ngStyle]="tableWrapperStyles">
        <table [ngStyle]="tableStyles">
          <thead [ngStyle]="theadStyles">
            <tr>
              <th *ngIf="selectable" [ngStyle]="thStyles">
                <input
                  type="checkbox"
                  [checked]="allSelected"
                  (change)="toggleSelectAll()"
                  aria-label="Select all rows">
              </th>
              <th *ngFor="let col of columns"
                  [ngStyle]="thStyles"
                  [style.width]="col.width"
                  scope="col"
                  [attr.aria-sort]="getSortDirection(col.key)">
                <div [ngStyle]="thContentStyles">
                  <span>{{ col.label }}</span>
                  <button *ngIf="col.sortable"
                          (click)="onSort(col.key)"
                          [ngStyle]="sortButtonStyles"
                          [attr.aria-label]="'Sort by ' + col.label">
                    {{ getSortIcon(col.key) }}
                  </button>
                </div>
              </th>
              <th *ngIf="hasActions" [ngStyle]="thStyles" scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            <!-- Empty State -->
            <tr *ngIf="filteredData.length === 0">
              <td [attr.colspan]="totalColumns" [ngStyle]="emptyStateStyles">
                <div [ngStyle]="emptyStateContentStyles">
                  <p>No data available</p>
                </div>
              </td>
            </tr>

            <!-- Data Rows -->
            <ng-container *ngFor="let row of paginatedData; let i = index">
              <tr [ngStyle]="getTrStyles(row)"
                  (click)="onRowClick(row)"
                  [attr.aria-selected]="isSelected(row.id)">
                <td *ngIf="selectable" [ngStyle]="tdStyles">
                  <input
                    type="checkbox"
                    [checked]="isSelected(row.id)"
                    (change)="toggleSelect(row.id)"
                    (click)="$event.stopPropagation()"
                    [attr.aria-label]="'Select row ' + (i + 1)">
                </td>
                <td *ngFor="let col of columns" [ngStyle]="tdStyles">
                  {{ row[col.key] }}
                </td>
                <td *ngIf="hasActions" [ngStyle]="tdStyles">
                  <div [ngStyle]="actionButtonGroupStyles">
                    <button [ngStyle]="actionButtonStyles" (click)="onEdit(row); $event.stopPropagation()">Edit</button>
                    <button [ngStyle]="deleteButtonStyles" (click)="onDelete(row); $event.stopPropagation()">Delete</button>
                  </div>
                </td>
              </tr>
              <tr *ngIf="expandable && expandedRows.has(row.id)" [ngStyle]="expandedRowStyles">
                <td [attr.colspan]="totalColumns" [ngStyle]="expandedContentStyles">
                  <ng-content></ng-content>
                </td>
              </tr>
            </ng-container>
          </tbody>
        </table>
      </div>

      <!-- Pagination -->
      <div *ngIf="paginate && filteredData.length > 0" [ngStyle]="paginationStyles">
        <div [ngStyle]="paginationInfoStyles">
          Showing {{ startIndex + 1 }}-{{ endIndex }} of {{ filteredData.length }}
        </div>
        <div [ngStyle]="paginationButtonGroupStyles">
          <button [ngStyle]="paginationButtonStyles"
                  (click)="previousPage()"
                  [disabled]="currentPage === 1">
            Previous
          </button>
          <span [ngStyle]="pageNumberStyles">Page {{ currentPage }} of {{ totalPages }}</span>
          <button [ngStyle]="paginationButtonStyles"
                  (click)="nextPage()"
                  [disabled]="currentPage === totalPages">
            Next
          </button>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .table-container { width: 100%; }
  `]
})
export class TableComponent {
  @Input() theme: Partial<TableTheme> = {};
  @Input() columns: TableColumn[] = [];
  @Input() data: TableRow[] = [];
  @Input() selectable: boolean = false;
  @Input() searchable: boolean = true;
  @Input() paginate: boolean = true;
  @Input() pageSize: number = 10;
  @Input() striped: boolean = true;
  @Input() bordered: boolean = true;
  @Input() size: 'compact' | 'comfortable' | 'spacious' = 'comfortable';
  @Input() stickyHeader: boolean = true;
  @Input() expandable: boolean = false;
  @Input() hasActions: boolean = true;
  @Input() loading: boolean = false;

  @Output() rowClick = new EventEmitter<TableRow>();
  @Output() edit = new EventEmitter<TableRow>();
  @Output() delete = new EventEmitter<TableRow>();
  @Output() selectionChange = new EventEmitter<(string | number)[]>();

  searchTerm: string = '';
  sortKey: string = '';
  sortDirection: 'asc' | 'desc' | null = null;
  currentPage: number = 1;
  selectedRows: Set<string | number> = new Set();
  expandedRows: Set<string | number> = new Set();

  private defaultTheme: TableTheme = {
    primaryColor: '#2563eb',
    secondaryColor: '#3b82f6',
    backgroundColor: '#ffffff',
    textColor: '#1f2937',
    borderColor: '#e5e7eb',
    headerBgColor: '#f3f4f6',
    hoverColor: '#eff6ff'
  };

  get appliedTheme(): TableTheme {
    return { ...this.defaultTheme, ...this.theme };
  }

  get filteredData(): TableRow[] {
    let result = [...this.data];

    if (this.searchTerm) {
      result = result.filter(row =>
        Object.values(row).some(val =>
          String(val).toLowerCase().includes(this.searchTerm.toLowerCase())
        )
      );
    }

    if (this.sortKey && this.sortDirection) {
      result.sort((a, b) => {
        const aVal = a[this.sortKey];
        const bVal = b[this.sortKey];
        const modifier = this.sortDirection === 'asc' ? 1 : -1;
        return aVal > bVal ? modifier : aVal < bVal ? -modifier : 0;
      });
    }

    return result;
  }

  get paginatedData(): TableRow[] {
    if (!this.paginate) return this.filteredData;
    const start = (this.currentPage - 1) * this.pageSize;
    return this.filteredData.slice(start, start + this.pageSize);
  }

  get totalPages(): number {
    return Math.ceil(this.filteredData.length / this.pageSize);
  }

  get startIndex(): number {
    return (this.currentPage - 1) * this.pageSize;
  }

  get endIndex(): number {
    return Math.min(this.startIndex + this.pageSize, this.filteredData.length);
  }

  get allSelected(): boolean {
    return this.paginatedData.length > 0 &&
           this.paginatedData.every(row => this.selectedRows.has(row.id));
  }

  get totalColumns(): number {
    return this.columns.length + (this.selectable ? 1 : 0) + (this.hasActions ? 1 : 0);
  }

  get containerStyles() {
    return {
      width: '100%',
      backgroundColor: this.appliedTheme.backgroundColor,
      borderRadius: '8px',
      boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      overflow: 'hidden'
    };
  }

  get searchBarStyles() {
    return {
      padding: '16px',
      borderBottom: `1px solid ${this.appliedTheme.borderColor}`
    };
  }

  get searchInputStyles() {
    return {
      width: '100%',
      padding: '8px 12px',
      border: `1px solid ${this.appliedTheme.borderColor}`,
      borderRadius: '6px',
      fontSize: '14px',
      outline: 'none'
    };
  }

  get tableWrapperStyles() {
    return {
      overflowX: 'auto',
      maxHeight: this.stickyHeader ? '600px' : 'none',
      overflowY: this.stickyHeader ? 'auto' : 'visible'
    };
  }

  get tableStyles() {
    return {
      width: '100%',
      borderCollapse: 'collapse' as const,
      fontSize: this.size === 'compact' ? '13px' : this.size === 'comfortable' ? '14px' : '16px'
    };
  }

  get theadStyles() {
    return {
      backgroundColor: this.appliedTheme.headerBgColor,
      position: this.stickyHeader ? 'sticky' as const : 'static' as const,
      top: '0',
      zIndex: '10'
    };
  }

  get thStyles() {
    const padding = this.size === 'compact' ? '8px 12px' :
                   this.size === 'comfortable' ? '12px 16px' : '16px 20px';
    return {
      padding,
      textAlign: 'left' as const,
      fontWeight: '600',
      color: this.appliedTheme.textColor,
      borderBottom: `2px solid ${this.appliedTheme.borderColor}`,
      borderRight: this.bordered ? `1px solid ${this.appliedTheme.borderColor}` : 'none'
    };
  }

  get thContentStyles() {
    return {
      display: 'flex',
      alignItems: 'center',
      gap: '8px'
    };
  }

  get sortButtonStyles() {
    return {
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      fontSize: '12px',
      color: this.appliedTheme.primaryColor,
      padding: '2px 4px'
    };
  }

  getTrStyles(row: TableRow) {
    const isRowSelected = this.selectedRows.has(row.id);
    const padding = this.size === 'compact' ? '8px 12px' :
                   this.size === 'comfortable' ? '12px 16px' : '16px 20px';

    return {
      backgroundColor: isRowSelected ? this.appliedTheme.hoverColor : 'transparent',
      cursor: 'pointer',
      transition: 'background-color 0.2s',
      ':hover': {
        backgroundColor: this.appliedTheme.hoverColor
      }
    };
  }

  get tdStyles() {
    const padding = this.size === 'compact' ? '8px 12px' :
                   this.size === 'comfortable' ? '12px 16px' : '16px 20px';
    return {
      padding,
      borderBottom: `1px solid ${this.appliedTheme.borderColor}`,
      borderRight: this.bordered ? `1px solid ${this.appliedTheme.borderColor}` : 'none',
      color: this.appliedTheme.textColor
    };
  }

  get emptyStateStyles() {
    return {
      padding: '48px 16px',
      textAlign: 'center' as const,
      color: '#9ca3af'
    };
  }

  get emptyStateContentStyles() {
    return {
      fontSize: '14px'
    };
  }

  get loadingStyles() {
    return {
      display: 'flex',
      flexDirection: 'column' as const,
      alignItems: 'center',
      justifyContent: 'center',
      padding: '48px',
      gap: '16px'
    };
  }

  get spinnerStyles() {
    return {
      width: '40px',
      height: '40px',
      border: `4px solid ${this.appliedTheme.borderColor}`,
      borderTop: `4px solid ${this.appliedTheme.primaryColor}`,
      borderRadius: '50%',
      animation: 'spin 1s linear infinite'
    };
  }

  get paginationStyles() {
    return {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '16px',
      borderTop: `1px solid ${this.appliedTheme.borderColor}`,
      fontSize: '14px'
    };
  }

  get paginationInfoStyles() {
    return {
      color: this.appliedTheme.textColor
    };
  }

  get paginationButtonGroupStyles() {
    return {
      display: 'flex',
      gap: '12px',
      alignItems: 'center'
    };
  }

  get paginationButtonStyles() {
    return {
      padding: '6px 12px',
      border: `1px solid ${this.appliedTheme.borderColor}`,
      borderRadius: '6px',
      backgroundColor: this.appliedTheme.backgroundColor,
      color: this.appliedTheme.primaryColor,
      cursor: 'pointer',
      fontSize: '14px'
    };
  }

  get pageNumberStyles() {
    return {
      color: this.appliedTheme.textColor,
      fontSize: '14px'
    };
  }

  get actionButtonGroupStyles() {
    return {
      display: 'flex',
      gap: '8px'
    };
  }

  get actionButtonStyles() {
    return {
      padding: '4px 8px',
      border: 'none',
      borderRadius: '4px',
      backgroundColor: this.appliedTheme.primaryColor,
      color: '#ffffff',
      cursor: 'pointer',
      fontSize: '12px'
    };
  }

  get deleteButtonStyles() {
    return {
      padding: '4px 8px',
      border: 'none',
      borderRadius: '4px',
      backgroundColor: '#ef4444',
      color: '#ffffff',
      cursor: 'pointer',
      fontSize: '12px'
    };
  }

  get expandedRowStyles() {
    return {
      backgroundColor: '#f9fafb'
    };
  }

  get expandedContentStyles() {
    return {
      padding: '16px'
    };
  }

  onSearch() {
    this.currentPage = 1;
  }

  onSort(key: string) {
    if (this.sortKey === key) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : this.sortDirection === 'desc' ? null : 'asc';
      if (this.sortDirection === null) this.sortKey = '';
    } else {
      this.sortKey = key;
      this.sortDirection = 'asc';
    }
  }

  getSortIcon(key: string): string {
    if (this.sortKey !== key) return '↕';
    return this.sortDirection === 'asc' ? '↑' : '↓';
  }

  getSortDirection(key: string): string | null {
    if (this.sortKey !== key) return null;
    return this.sortDirection === 'asc' ? 'ascending' : 'descending';
  }

  toggleSelect(id: string | number) {
    if (this.selectedRows.has(id)) {
      this.selectedRows.delete(id);
    } else {
      this.selectedRows.add(id);
    }
    this.selectionChange.emit(Array.from(this.selectedRows));
  }

  toggleSelectAll() {
    if (this.allSelected) {
      this.paginatedData.forEach(row => this.selectedRows.delete(row.id));
    } else {
      this.paginatedData.forEach(row => this.selectedRows.add(row.id));
    }
    this.selectionChange.emit(Array.from(this.selectedRows));
  }

  isSelected(id: string | number): boolean {
    return this.selectedRows.has(id);
  }

  onRowClick(row: TableRow) {
    if (this.expandable) {
      if (this.expandedRows.has(row.id)) {
        this.expandedRows.delete(row.id);
      } else {
        this.expandedRows.add(row.id);
      }
    }
    this.rowClick.emit(row);
  }

  onEdit(row: TableRow) {
    this.edit.emit(row);
  }

  onDelete(row: TableRow) {
    this.delete.emit(row);
  }

  nextPage() {
    if (this.currentPage < this.totalPages) {
      this.currentPage++;
    }
  }

  previousPage() {
    if (this.currentPage > 1) {
      this.currentPage--;
    }
  }
}
