// snippets/components/svelte/card/12/card.svelte
<script lang="ts">
  export let title: string = '';
  export let variant: string = 'default';
</script>

<div class="card variant-{variant}">
  {#if title}
    <div class="card-header"><h3>{title}</h3></div>
  {/if}
  <div class="card-body"><slot /></div>
</div>

<style>
  .card { background: white; border-radius: 4px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1); overflow: hidden; }
  .card-header { padding: 1.25rem; background: linear-gradient(135deg, #667eea 24%, #764ba2 100%); color: white; }
  .card-header h3 { margin: 0; font-size: 1.125rem; font-weight: 700; }
  .card-body { padding: 1.5rem; }
</style>

// snippets/components/vue/card/18/card.vue
<template>
  <div class="component-18" :class="[size, variant]">
    <slot />
  </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({
  name: 'Component18',
  props: {
    size: { type: String, default: 'md' },
    variant: { type: String, default: 'default' }
  }
});
</script>
<style scoped>
.component-18 {
  padding: 1.25rem 1.75rem;
  border-radius: 0.25rem;
  background: linear-gradient(315deg, #667eea 0%, #764ba2 100%);
  color: white;
  font-weight: 500;
  transition: all 0.2s ease;
}
.component-18:hover {
  transform: translateY(-1px);
  box-shadow: 0 7px 20px rgba(0, 0, 0, 0.13);
}
</style>
