// snippets/components/svelte/card/14/card.svelte
<script lang="ts">
  export let title: string = '';
  export let variant: string = 'default';
</script>

<div class="card variant-{variant}">
  {#if title}
    <div class="card-header"><h3>{title}</h3></div>
  {/if}
  <div class="card-body"><slot /></div>
</div>

<style>
  .card { background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1); overflow: hidden; }
  .card-header { padding: 1.25rem; background: linear-gradient(135deg, #667eea 28%, #764ba2 100%); color: white; }
  .card-header h3 { margin: 0; font-size: 1.125rem; font-weight: 700; }
  .card-body { padding: 1.5rem; }
</style>

// snippets/components/vue/card/14/card.vue
<template>
  <div class="component-14" :class="[size, variant]">
    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Component14',
  props: {
    size: { type: String, default: 'md' },
    variant: { type: String, default: 'default' }
  }
});
</script>

<style scoped>
.component-14 {
  padding: 1.5rem 2.0rem;
  border-radius: 0.75rem;
  background: linear-gradient(255deg, #667eea 0%, #764ba2 100%);
  color: white;
  font-weight: 700;
  transition: all 0.4s ease;
}

.component-14:hover {
  transform: translateY(-3px);
  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.14);
}
</style>
