// snippets/screens/react-native/empty_state_screen/3/empty_state_screen.jsx
import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
} from 'react-native';
import Icon from 'react-native-vector-icons/MaterialIcons';

const EmptyStateScreen = ({
  title = "Nothing here yet",
  message = "It looks like there's no content to show right now. Try refreshing or come back later.",
  iconName = "inbox",
  buttonText,
  onAction,
}) => {
  return (
    <View style={styles.container}>
      <View style={styles.content}>
        <View style={styles.iconContainer}>
          <Icon name={iconName} size={60} color="#9CA3AF" />
        </View>

        <Text style={styles.title}>{title}</Text>
        <Text style={styles.message}>{message}</Text>

        {onAction && buttonText && (
          <TouchableOpacity style={styles.actionButton} onPress={onAction}>
            <Text style={styles.actionButtonText}>{buttonText}</Text>
          </TouchableOpacity>
        )}
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  content: {
    alignItems: 'center',
    maxWidth: 280,
  },
  iconContainer: {
    width: 120,
    height: 120,
    backgroundColor: 'rgba(107, 114, 128, 0.1)',
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
    textAlign: 'center',
    marginBottom: 12,
  },
  message: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
  },
  actionButton: {
    backgroundColor: '#6366F1',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    width: '100%',
    alignItems: 'center',
  },
  actionButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
});

export default EmptyStateScreen;

// snippets/screens/angular-ionic/empty_state_screen/1/empty_state_screen.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-empty-state-screen',
  template: `
    <ion-content class="empty-state-container">
      <div class="content-wrapper">
        <!-- Icon -->
        <div class="icon-container">
          <ion-icon [name]="iconName || 'archive-outline'" class="empty-icon"></ion-icon>
        </div>

        <!-- Content -->
        <div class="content">
          <h2 class="title">{{ title || 'Nothing here yet' }}</h2>
          <p class="message">
            {{ message || "It looks like there's no content to show right now. Try refreshing or come back later." }}
          </p>
        </div>

        <!-- Action Button -->
        <div class="button-container" *ngIf="buttonText && onAction">
          <ion-button
            expand="block"
            fill="solid"
            color="primary"
            class="action-button"
            (click)="handleAction()"
          >
            {{ buttonText }}
          </ion-button>
        </div>
      </div>
    </ion-content>
  `,
  styles: [`
    .empty-state-container {
      --background: #ffffff;
    }

    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 32px;
      text-align: center;
    }

    .icon-container {
      margin-bottom: 32px;
    }

    .empty-icon {
      font-size: 60px;
      color: #9CA3AF;
      width: 120px;
      height: 120px;
      background: rgba(156, 163, 175, 0.1);
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .content {
      margin-bottom: 32px;
      max-width: 280px;
    }

    .title {
      font-size: 24px;
      font-weight: 700;
      color: #1F2937;
      margin-bottom: 12px;
    }

    .message {
      font-size: 16px;
      color: #6B7280;
      line-height: 1.5;
    }

    .button-container {
      width: 100%;
      max-width: 280px;
    }

    .action-button {
      --border-radius: 12px;
      height: 48px;
      margin: 0;
      font-weight: 600;
    }
  `]
})
export class EmptyStateScreenComponent implements OnInit {
  @Input() title?: string;
  @Input() message?: string;
  @Input() iconName?: string;
  @Input() buttonText?: string;
  @Input() onAction?: () => void;

  ngOnInit() {}

  handleAction() {
    if (this.onAction) {
      this.onAction();
    }
  }
}
