// snippets/screens/react/splash_screen/3/splash_screen.jsx
import React, { useState, useEffect } from 'react';
import { Rocket, Brain } from 'lucide-react';

const SplashScreen = ({ onComplete }) => {
  const [logoScale, setLogoScale] = useState(0.8);
  const [logoOpacity, setLogoOpacity] = useState(0);
  const [textOpacity, setTextOpacity] = useState(0);
  const [showProgress, setShowProgress] = useState(false);

  useEffect(() => {
    const timeline = async () => {
      // Logo fade in
      setLogoOpacity(1);

      // Logo scale animation
      setTimeout(() => setLogoScale(1), 200);

      // Text fade in
      setTimeout(() => setTextOpacity(1), 400);

      // Progress indicator
      setTimeout(() => setShowProgress(true), 800);

      // Navigate after 3 seconds
      setTimeout(() => {
        if (onComplete) onComplete();
      }, 3000);
    };

    timeline();
  }, [onComplete]);

  return (
    <div className="min-h-screen bg-gradient-to-b from-indigo-500 to-indigo-600 flex items-center justify-center text-white">
      <div className="text-center">
        {/* Logo */}
        <div
          className="mb-8 transition-all duration-500 ease-out"
          style={{
            transform: `scale(${logoScale})`,
            opacity: logoOpacity
          }}
        >
          <div className="w-30 h-30 bg-white rounded-3xl shadow-2xl mx-auto flex items-center justify-center mb-8">
            <Rocket className="w-15 h-15 text-indigo-500" size={60} />
          </div>
        </div>

        {/* Title */}
        <div
          className="transition-opacity duration-600"
          style={{ opacity: textOpacity }}
        >
          <h1 className="text-4xl font-bold mb-4 tracking-widest">
            AIQ
          </h1>
          <p className="text-lg text-white/70 mb-20 tracking-wide">
            Artificial Intelligence Quotient
          </p>
        </div>

        {/* Progress Indicator */}
        {showProgress && (
          <div className="transition-opacity duration-400">
            <div className="w-8 h-8 border-2 border-white/70 border-t-transparent rounded-full animate-spin mx-auto"></div>
          </div>
        )}
      </div>
    </div>
  );
};

export default SplashScreen;

// snippets/screens/angular-ionic/splash_screen/2/splash_screen.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-splash-screen',
  template: `
    <ion-content class="splash-container">
      <div class="content-wrapper">
        <!-- Logo -->
        <div class="logo-container" [style.transform]="'scale(' + logoScale + ')'" [style.opacity]="logoOpacity">
          <div class="logo-card">
            <ion-icon name="rocket" class="logo-icon"></ion-icon>
          </div>
        </div>

        <!-- Title -->
        <div class="title-container" [style.opacity]="textOpacity">
          <h1 class="app-title">AIQ</h1>
          <p class="app-subtitle">Artificial Intelligence Quotient</p>
        </div>

        <!-- Progress Indicator -->
        <div class="progress-container" *ngIf="showProgress" [style.opacity]="progressOpacity">
          <ion-spinner name="crescent" color="light"></ion-spinner>
        </div>
      </div>
    </ion-content>
  `,
  styles: [`
    .splash-container {
      --background: linear-gradient(180deg, #6366F1 0%, rgba(99, 102, 241, 0.8) 100%);
    }

    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh;
      padding: 24px;
      color: white;
    }

    .logo-container {
      margin-bottom: 32px;
      transition: all 0.8s cubic-bezier(0.175, 0.885, 0.32, 1.275);
    }

    .logo-card {
      width: 120px;
      height: 120px;
      background: white;
      border-radius: 24px;
      display: flex;
      align-items: center;
      justify-content: center;
      box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
    }

    .logo-icon {
      font-size: 60px;
      color: #6366F1;
    }

    .title-container {
      text-align: center;
      margin-bottom: 80px;
      transition: opacity 0.6s ease-in;
    }

    .app-title {
      font-size: 32px;
      font-weight: 700;
      letter-spacing: 2px;
      margin-bottom: 16px;
    }

    .app-subtitle {
      font-size: 16px;
      opacity: 0.7;
      letter-spacing: 0.5px;
    }

    .progress-container {
      transition: opacity 0.4s ease-in;
    }

    ion-spinner {
      width: 32px;
      height: 32px;
    }
  `]
})
export class SplashScreenComponent implements OnInit {
  logoScale = 0.8;
  logoOpacity = 0;
  textOpacity = 0;
  progressOpacity = 0;
  showProgress = false;

  constructor(private router: Router) {}

  ngOnInit() {
    this.startAnimations();
  }

  private async startAnimations() {
    // Logo fade in
    setTimeout(() => {
      this.logoOpacity = 1;
    }, 100);

    // Logo scale animation
    setTimeout(() => {
      this.logoScale = 1;
    }, 300);

    // Text fade in
    setTimeout(() => {
      this.textOpacity = 1;
    }, 600);

    // Progress indicator
    setTimeout(() => {
      this.showProgress = true;
      this.progressOpacity = 1;
    }, 1000);

    // Navigate to onboarding
    setTimeout(() => {
      this.router.navigate(['/onboarding']);
    }, 3000);
  }
}
