// snippets/screens/react-native/splash_screen/2/splash_screen.jsx
import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Animated,
  Dimensions,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import Icon from 'react-native-vector-icons/MaterialIcons';

const { width, height } = Dimensions.get('window');

const SplashScreen = ({ onComplete }) => {
  const [logoScale] = useState(new Animated.Value(0.8));
  const [logoOpacity] = useState(new Animated.Value(0));
  const [textOpacity] = useState(new Animated.Value(0));
  const [showProgress, setShowProgress] = useState(false);

  useEffect(() => {
    const animateSequence = () => {
      // Logo fade in
      Animated.timing(logoOpacity, {
        toValue: 1,
        duration: 500,
        useNativeDriver: true,
      }).start();

      // Logo scale animation
      setTimeout(() => {
        Animated.spring(logoScale, {
          toValue: 1,
          tension: 50,
          friction: 7,
          useNativeDriver: true,
        }).start();
      }, 200);

      // Text fade in
      setTimeout(() => {
        Animated.timing(textOpacity, {
          toValue: 1,
          duration: 600,
          useNativeDriver: true,
        }).start();
      }, 400);

      // Progress indicator
      setTimeout(() => {
        setShowProgress(true);
      }, 800);

      // Navigate after 3 seconds
      setTimeout(() => {
        onComplete?.();
      }, 3000);
    };

    animateSequence();
  }, []);

  return (
    <LinearGradient
      colors={['#6366F1', 'rgba(99, 102, 241, 0.8)']}
      style={styles.container}
    >
      <View style={styles.content}>
        {/* Logo */}
        <Animated.View
          style={[
            styles.logoContainer,
            {
              transform: [{ scale: logoScale }],
              opacity: logoOpacity,
            },
          ]}
        >
          <View style={styles.logoCard}>
            <Icon name="rocket-launch" size={60} color="#6366F1" />
          </View>
        </Animated.View>

        {/* Title */}
        <Animated.View
          style={[styles.titleContainer, { opacity: textOpacity }]}
        >
          <Text style={styles.title}>AIQ</Text>
          <Text style={styles.subtitle}>Artificial Intelligence Quotient</Text>
        </Animated.View>

        {/* Progress Indicator */}
        {showProgress && (
          <Animated.View style={styles.progressContainer}>
            <View style={styles.spinner} />
          </Animated.View>
        )}
      </View>
    </LinearGradient>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    alignItems: 'center',
  },
  logoContainer: {
    marginBottom: 32,
  },
  logoCard: {
    width: 120,
    height: 120,
    backgroundColor: 'white',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 20,
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 80,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: 'white',
    letterSpacing: 2,
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.7)',
    letterSpacing: 0.5,
  },
  progressContainer: {
    alignItems: 'center',
  },
  spinner: {
    width: 32,
    height: 32,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    borderTopColor: 'transparent',
    borderRadius: 16,
    // Note: You'd need to add rotation animation here
  },
});

export default SplashScreen;

// snippets/screens/angular-ionic/splash_screen/2/splash_screen.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-splash-screen',
  template: `
    <ion-content class="splash-container">
      <div class="content-wrapper">
        <!-- Logo -->
        <div class="logo-container" [style.transform]="'scale(' + logoScale + ')'" [style.opacity]="logoOpacity">
          <div class="logo-card">
            <ion-icon name="rocket" class="logo-icon"></ion-icon>
          </div>
        </div>

        <!-- Title -->
        <div class="title-container" [style.opacity]="textOpacity">
          <h1 class="app-title">AIQ</h1>
          <p class="app-subtitle">Artificial Intelligence Quotient</p>
        </div>

        <!-- Progress Indicator -->
        <div class="progress-container" *ngIf="showProgress" [style.opacity]="progressOpacity">
          <ion-spinner name="crescent" color="light"></ion-spinner>
        </div>
      </div>
    </ion-content>
  `,
  styles: [`
    .splash-container {
      --background: linear-gradient(180deg, #6366F1 0%, rgba(99, 102, 241, 0.8) 100%);
    }

    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh;
      padding: 24px;
      color: white;
    }

    .logo-container {
      margin-bottom: 32px;
      transition: all 0.8s cubic-bezier(0.175, 0.885, 0.32, 1.275);
    }

    .logo-card {
      width: 120px;
      height: 120px;
      background: white;
      border-radius: 24px;
      display: flex;
      align-items: center;
      justify-content: center;
      box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
    }

    .logo-icon {
      font-size: 60px;
      color: #6366F1;
    }

    .title-container {
      text-align: center;
      margin-bottom: 80px;
      transition: opacity 0.6s ease-in;
    }

    .app-title {
      font-size: 32px;
      font-weight: 700;
      letter-spacing: 2px;
      margin-bottom: 16px;
    }

    .app-subtitle {
      font-size: 16px;
      opacity: 0.7;
      letter-spacing: 0.5px;
    }

    .progress-container {
      transition: opacity 0.4s ease-in;
    }

    ion-spinner {
      width: 32px;
      height: 32px;
    }
  `]
})
export class SplashScreenComponent implements OnInit {
  logoScale = 0.8;
  logoOpacity = 0;
  textOpacity = 0;
  progressOpacity = 0;
  showProgress = false;

  constructor(private router: Router) {}

  ngOnInit() {
    this.startAnimations();
  }

  private async startAnimations() {
    // Logo fade in
    setTimeout(() => {
      this.logoOpacity = 1;
    }, 100);

    // Logo scale animation
    setTimeout(() => {
      this.logoScale = 1;
    }, 300);

    // Text fade in
    setTimeout(() => {
      this.textOpacity = 1;
    }, 600);

    // Progress indicator
    setTimeout(() => {
      this.showProgress = true;
      this.progressOpacity = 1;
    }, 1000);

    // Navigate to onboarding
    setTimeout(() => {
      this.router.navigate(['/onboarding']);
    }, 3000);
  }
}
