// snippets/components/svelte/modal/5/modal.svelte
<script lang="ts">
  import { fade, scale } from 'svelte/transition';
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import { bounceOut } from 'svelte/easing';
  export interface ModalTheme {
    background?: string;
    overlay?: string;
    border?: string;
    shadow?: string;
  }
  export let isOpen = false;
  export let title = 'Modal';
  export let size: 'sm' | 'md' | 'lg' | 'xl' | 'full' = 'md';
  export let variant: 'default' | 'centered' | 'drawer' | 'fullscreen' | 'bottom-sheet' = 'centered';
  export let closeOnOverlay = true;
  export let closeOnEsc = true;
  export let showCloseButton = true;
  export let theme: ModalTheme = {};
  const dispatch = createEventDispatcher();
  const defaultTheme: ModalTheme = {
    background: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
    overlay: 'rgba(168, 237, 234, 0.4)',
    border: '#fed6e3',
    shadow: '0 30px 60px rgba(254, 214, 227, 0.5)'
  };
  $: appliedTheme = { ...defaultTheme, ...theme };
  $: modalWidth = size === 'sm' ? '380px' : size === 'md' ? '580px' : size === 'lg' ? '780px' : size === 'xl' ? '980px' : '100%';
  function handleKeydown(event: KeyboardEvent) {
    if (closeOnEsc && event.key === 'Escape' && isOpen) {
      close();
    }
  }
  function handleOverlayClick() {
    if (closeOnOverlay) {
      close();
    }
  }
  function close() {
    isOpen = false;
    dispatch('close');
  }
  onMount(() => {
    document.addEventListener('keydown', handleKeydown);
    return () => {
      document.removeEventListener('keydown', handleKeydown);
    };
  });
  $: if (isOpen) {
    document.body.style.overflow = 'hidden';
  } else {
    document.body.style.overflow = '';
  }
  onDestroy(() => {
    document.body.style.overflow = '';
  });
</script>
{#if isOpen}
  <div class="modal-overlay" style="background: {appliedTheme.overlay};" on:click={handleOverlayClick} transition:fade={{ duration: 300 }}>
    <div class="modal-content" style="max-width: {modalWidth}; background: {appliedTheme.background}; border: 3px solid {appliedTheme.border}; box-shadow: {appliedTheme.shadow};" on:click|stopPropagation transition:scale={{ duration: 600, start: 0.5, easing: bounceOut }}>
      <div class="modal-header">
        <h2>{title}</h2>
        {#if showCloseButton}
          <button class="close-btn" on:click={close}>
            <svg width="18" height="18" viewBox="0 0 18 18" fill="none" stroke="currentColor" stroke-width="2.5">
              <path d="M1 1L17 17M17 1L1 17" />
            </svg>
          </button>
        {/if}
      </div>
      <div class="modal-body">
        <slot />
      </div>
      <div class="modal-footer">
        <slot name="footer">
          <button class="btn-secondary" on:click={close}>Cancel</button>
          <button class="btn-primary">Confirm</button>
        </slot>
      </div>
    </div>
  </div>
{/if}
<style>
  .modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
    backdrop-filter: blur(5px);
  }
  .modal-content {
    border-radius: 16px;
    width: 90%;
    max-height: 90vh;
    overflow: auto;
    color: #1a202c;
  }
  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.75rem 2rem;
    border-bottom: 2px dashed rgba(254, 214, 227, 0.6);
  }
  .modal-header h2 {
    margin: 0;
    font-size: 1.75rem;
    font-weight: 800;
    color: #2d3748;
  }
  .close-btn {
    background: rgba(254, 214, 227, 0.3);
    border: 2px solid rgba(254, 214, 227, 0.6);
    cursor: pointer;
    color: #2d3748;
    width: 38px;
    height: 38px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.3s;
  }
  .close-btn:hover {
    background: rgba(254, 214, 227, 0.5);
    transform: rotate(90deg) scale(1.1);
  }
  .modal-body {
    padding: 2rem;
  }
  .modal-footer {
    padding: 1.75rem 2rem;
    border-top: 2px dashed rgba(254, 214, 227, 0.6);
    display: flex;
    justify-content: flex-end;
    gap: 0.75rem;
  }
  .btn-secondary {
    padding: 0.75rem 1.5rem;
    background: rgba(168, 237, 234, 0.3);
    border: 2px solid rgba(168, 237, 234, 0.6);
    border-radius: 10px;
    color: #2d3748;
    cursor: pointer;
    font-weight: 600;
    transition: all 0.3s;
  }
  .btn-secondary:hover {
    background: rgba(168, 237, 234, 0.5);
  }
  .btn-primary {
    padding: 0.75rem 1.5rem;
    background: rgba(254, 214, 227, 0.5);
    border: 2px solid rgba(254, 214, 227, 0.8);
    border-radius: 10px;
    color: #2d3748;
    cursor: pointer;
    font-weight: 700;
    transition: all 0.3s;
  }
  .btn-primary:hover {
    background: rgba(254, 214, 227, 0.7);
    transform: translateY(-2px);
  }
@keyframes fade {
  from { opacity: 0; }
  to { opacity: 1; }
}
@keyframes expand {
  from { transform: scale(0.9); opacity: 0; }
  to { transform: scale(1); opacity: 1; }
}
</style>

// snippets/components/react/modal/41/modal.tsx
import React, { useEffect, useRef, CSSProperties, ReactNode } from 'react';

export interface ModalTheme {
  background: string;
  overlay: string;
  border: string;
  shadow: string;
}

export interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title?: string;
  children: ReactNode;
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  variant?: 'default' | 'centered' | 'drawer' | 'fullscreen' | 'bottom-sheet';
  closeOnOverlay?: boolean;
  closeOnEsc?: boolean;
  showCloseButton?: boolean;
  theme?: Partial<ModalTheme>;
}

const defaultTheme: ModalTheme = {
  background: "linear-gradient(135deg, #6366f1 0%, #06b6d4 100%)",
  overlay: 'rgba(0, 0, 0, 0.4)',
  border: 'rgba(255, 255, 255, 0.3)',
  shadow: 'rgba(0, 0, 0, 0.2)'
};

export const Modal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  title = 'Wave Modal',
  children,
  size = 'md',
  variant = 'default',
  closeOnOverlay = true,
  closeOnEsc = true,
  showCloseButton = true,
  theme = {}
}) => {
  const appliedTheme = { ...defaultTheme, ...theme };
  const modalRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => {
      if (closeOnEsc && e.key === 'Escape') {
        onClose();
      }
    };
    if (isOpen) {
      document.addEventListener('keydown', handleEsc);
    }
    return () => document.removeEventListener('keydown', handleEsc);
  }, [isOpen, closeOnEsc, onClose]);

  useEffect(() => {
    if (!isOpen || !modalRef.current) return;
    const focusableElements = modalRef.current.querySelectorAll(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
    const firstElement = focusableElements[0] as HTMLElement;
    const lastElement = focusableElements[focusableElements.length - 1] as HTMLElement;
    const handleTab = (e: KeyboardEvent) => {
      if (e.key !== 'Tab') return;
      if (e.shiftKey) {
        if (document.activeElement === firstElement) {
          lastElement?.focus();
          e.preventDefault();
        }
      } else {
        if (document.activeElement === lastElement) {
          firstElement?.focus();
          e.preventDefault();
        }
      }
    };
    document.addEventListener('keydown', handleTab);
    return () => document.removeEventListener('keydown', handleTab);
  }, [isOpen]);

  if (!isOpen) return null;

  const sizeMap: Record<string, CSSProperties> = {
    sm: { maxWidth: '420px', width: '90%' },
    md: { maxWidth: '600px', width: '90%' },
    lg: { maxWidth: '840px', width: '90%' },
    xl: { maxWidth: '1080px', width: '95%' },
    full: { maxWidth: '100vw', width: '100%', height: '100vh' }
  };

  const overlayStyle: CSSProperties = {
    position: 'fixed',
    inset: 0,
    background: appliedTheme.overlay,
    backdropFilter: 'blur(5px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    animation: 'fadeIn 0.3s ease-out'
  };

  const modalStyle: CSSProperties = {
    ...sizeMap[size],
    background: '#fff',
    borderRadius: '18px',
    boxShadow: `0 20px 50px ${appliedTheme.shadow}`,
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '90vh',
    animation: 'waveIn 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
    position: 'relative'
  };

  const headerStyle: CSSProperties = {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '24px 30px',
    borderBottom: '2px solid #e5e7eb'
  };

  const titleStyle: CSSProperties = {
    margin: 0,
    fontSize: '22px',
    fontWeight: 700,
    color: '#1f2937'
  };

  const closeButtonStyle: CSSProperties = {
    background: appliedTheme.background,
    border: 'none',
    borderRadius: '50%',
    width: '36px',
    height: '36px',
    fontSize: '18px',
    cursor: 'pointer',
    color: '#fff',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  };

  const contentStyle: CSSProperties = {
    padding: '30px',
    flex: 1,
    overflow: 'auto',
    fontSize: '15px',
    lineHeight: 1.6,
    color: '#4b5563'
  };

  const footerStyle: CSSProperties = {
    padding: '20px 30px',
    borderTop: '2px solid #e5e7eb',
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
    background: '#f9fafb'
  };

  const buttonStyle: CSSProperties = {
    padding: '11px 26px',
    borderRadius: '10px',
    border: 'none',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease'
  };

  const primaryButtonStyle: CSSProperties = {
    ...buttonStyle,
    background: appliedTheme.background,
    color: '#fff'
  };

  const secondaryButtonStyle: CSSProperties = {
    ...buttonStyle,
    background: '#e5e7eb',
    color: '#374151'
  };

  return (
    <>
      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        @keyframes waveIn {
          0% { opacity: 0; transform: scale(0.5) rotate(-5deg); } 50% { transform: scale(1.05) rotate(2deg); } 100% { opacity: 1; transform: scale(1) rotate(0deg); }
        }
        .modal-v41-close-btn:hover {
          transform: scale(1.1) rotate(90deg);
        }
        .modal-v41-primary-btn:hover {
          transform: translateY(-2px);
          filter: brightness(110%);
        }
        .modal-v41-secondary-btn:hover {
          background: #d1d5db;
        }
      `}</style>
      <div style={overlayStyle} onClick={closeOnOverlay ? onClose : undefined}>
        <div ref={modalRef} style={modalStyle} onClick={(e) => e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="modal-title">
          <div style={headerStyle}>
            <h2 id="modal-title" style={titleStyle}>{title}</h2>
            {showCloseButton && (
              <button
                className="modal-v41-close-btn"
                style={closeButtonStyle}
                onClick={onClose}
                aria-label="Close modal"
              >
                ✕
              </button>
            )}
          </div>
          <div style={contentStyle}>{children}</div>
          <div style={footerStyle}>
            <button className="modal-v41-secondary-btn" style={secondaryButtonStyle} onClick={onClose}>
              Cancel
            </button>
            <button className="modal-v41-primary-btn" style={primaryButtonStyle} onClick={onClose}>
              Confirm
            </button>
          </div>
        </div>
      </div>
    </>
  );
};
