// snippets/components/vue/list/5/list.vue
<template>
  <div :style="componentStyles">
    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue';

export default defineComponent({
  name: 'Component',
  props: {
    theme: {
      type: Object,
      default: () => ({})
    },
    size: {
      type: String,
      default: 'md'
    }
  },
  setup(props) {
    const defaultTheme = {
      primaryColor: '#3b82f6',
      backgroundColor: '#ffffff',
      textColor: '#111827'
    };

    const appliedTheme = { ...defaultTheme, ...props.theme };

    const componentStyles = computed(() => ({
      padding: props.size === 'sm' ? '0.5rem' : props.size === 'lg' ? '1.5rem' : '1rem',
      backgroundColor: appliedTheme.backgroundColor,
      color: appliedTheme.textColor,
      borderRadius: '0.5rem'
    }));

    return { componentStyles };
  }
});
</script>

// snippets/components/svelte/list/1/list.svelte
<script lang="ts">
  export let theme = {};
  export let size = 'md';
  const defaultTheme = {
    primaryColor: '#3b82f6',
    backgroundColor: '#ffffff',
    textColor: '#111827'
  };
  $: appliedTheme = { ...defaultTheme, ...theme };
  $: padding = size === 'sm' ? '0.5rem' : size === 'lg' ? '1.5rem' : '1rem';
</script>
<div
  style="
    padding: {padding};
    background-color: {appliedTheme.backgroundColor};
    color: {appliedTheme.textColor};
    border-radius: 0.5rem;
  "
>
  <slot />
</div>
