// snippets/components/vue/grid/2/grid.vue
<template>
  <div class="grid-container" :style="containerStyles">
    <div v-if="loading" class="grid" :style="gridStyles">
      <div
        v-for="i in skeletonCount"
        :key="`skeleton-${i}`"
        class="grid-item skeleton"
        :style="itemStyles"
      >
        <div class="skeleton-image"></div>
        <div class="skeleton-content">
          <div class="skeleton-title"></div>
          <div class="skeleton-description"></div>
        </div>
      </div>
    </div>
    <div v-else class="grid uniform-grid" :style="gridStyles">
      <div
        v-for="item in items"
        :key="item.id"
        class="grid-item uniform-item"
        :style="itemStyles"
        @click="handleItemClick(item)"
      >
        <div class="item-overlay"></div>
        <div v-if="item.image" class="item-image-bg" :style="{ backgroundImage: `url(${item.image})` }">
          <div class="item-gradient"></div>
        </div>
        <div class="item-content-overlay">
          <h3 v-if="item.title" class="item-title">{{ item.title }}</h3>
          <p v-if="item.description" class="item-description">{{ item.description }}</p>
          <div v-if="item.content" class="item-text">{{ item.content }}</div>
        </div>
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import { computed } from 'vue';
interface GridTheme {
  primaryColor?: string;
  backgroundColor?: string;
  cardColor?: string;
  textColor?: string;
  borderColor?: string;
  shadowColor?: string;
}
interface GridItem {
  id: string | number;
  content?: string;
  image?: string;
  title?: string;
  description?: string;
}
type GridVariant = 'masonry' | 'uniform' | 'card' | 'minimal' | 'detailed';
type GridGap = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
interface Props {
  items?: GridItem[];
  columns?: number;
  gap?: GridGap;
  variant?: GridVariant;
  loading?: boolean;
  theme?: GridTheme;
}
const props = withDefaults(defineProps<Props>(), {
  items: () => [],
  columns: 4,
  gap: 'sm',
  variant: 'uniform',
  loading: false,
  theme: () => ({
    primaryColor: '#ec4899',
    backgroundColor: '#fdf2f8',
    cardColor: '#ffffff',
    textColor: '#ffffff',
    borderColor: '#fce7f3',
    shadowColor: 'rgba(236, 72, 153, 0.15)'
  })
});
const emit = defineEmits<{
  itemClick: [item: GridItem];
}>();
const gapSizes = {
  xs: '0.5rem',
  sm: '1rem',
  md: '1.5rem',
  lg: '2rem',
  xl: '3rem'
};
const skeletonCount = computed(() => props.columns * 3);
const containerStyles = computed(() => ({
  backgroundColor: props.theme?.backgroundColor || '#fdf2f8',
  padding: gapSizes[props.gap]
}));
const gridStyles = computed(() => ({
  display: 'grid',
  gap: gapSizes[props.gap],
  gridTemplateColumns: `repeat(${props.columns}, 1fr)`,
  gridAutoRows: '250px'
}));
const itemStyles = computed(() => ({
  borderColor: props.theme?.borderColor || '#fce7f3',
  '--primary-color': props.theme?.primaryColor || '#ec4899',
  '--text-color': props.theme?.textColor || '#ffffff',
  '--shadow-color': props.theme?.shadowColor || 'rgba(236, 72, 153, 0.15)'
}));
const handleItemClick = (item: GridItem) => {
  emit('itemClick', item);
};
</script>
<style scoped>
.grid-container {
  width: 100%;
  min-height: 200px;
}
.grid {
  width: 100%;
}
.uniform-grid {
  grid-auto-rows: 250px;
}
.grid-item {
  position: relative;
  border-radius: 16px;
  overflow: hidden;
  cursor: pointer;
  transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}
.uniform-item {
  display: flex;
  align-items: flex-end;
  justify-content: center;
  border: 2px solid;
  box-shadow: 0 4px 6px -1px var(--shadow-color);
}
.item-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: var(--primary-color);
  opacity: 0;
  transition: opacity 0.4s ease;
  z-index: 1;
}
.grid-item:hover .item-overlay {
  opacity: 0.1;
}
.grid-item:hover {
  transform: scale(1.05) rotate(1deg);
  box-shadow: 0 25px 50px -12px var(--shadow-color);
  z-index: 10;
}
.item-image-bg {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-size: cover;
  background-position: center;
  transition: transform 0.4s ease;
}
.grid-item:hover .item-image-bg {
  transform: scale(1.15);
}
.item-gradient {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: linear-gradient(to top, rgba(0, 0, 0, 0.8) 0%, transparent 100%);
}
.item-content-overlay {
  position: relative;
  z-index: 2;
  padding: 1.5rem;
  width: 100%;
  color: var(--text-color);
  transform: translateY(0);
  transition: transform 0.4s ease;
}
.grid-item:hover .item-content-overlay {
  transform: translateY(-8px);
}
.item-title {
  margin: 0 0 0.5rem 0;
  font-size: 1.125rem;
  font-weight: 700;
  line-height: 1.3;
  text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}
.item-description {
  margin: 0 0 0.25rem 0;
  font-size: 0.875rem;
  line-height: 1.5;
  opacity: 0.95;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
}
.item-text {
  font-size: 0.8125rem;
  line-height: 1.5;
  opacity: 0.9;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
}
/* Skeleton Loading */
.skeleton {
  pointer-events: none;
  animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}
.skeleton-image {
  width: 100%;
  height: 150px;
  background: linear-gradient(90deg, #fce7f3 25%, #fdf2f8 50%, #fce7f3 75%);
  background-size: 200% 100%;
  animation: shimmer 2s infinite;
}
.skeleton-content {
  padding: 1.5rem;
}
.skeleton-title {
  height: 1.125rem;
  background: linear-gradient(90deg, #fce7f3 25%, #fdf2f8 50%, #fce7f3 75%);
  background-size: 200% 100%;
  animation: shimmer 2s infinite;
  border-radius: 4px;
  margin-bottom: 0.5rem;
  width: 60%;
}
.skeleton-description {
  height: 2.5rem;
  background: linear-gradient(90deg, #fce7f3 25%, #fdf2f8 50%, #fce7f3 75%);
  background-size: 200% 100%;
  animation: shimmer 2s infinite;
  border-radius: 4px;
}
@keyframes pulse {
  0%, 100% {
    opacity: 1;
  }
  50% {
    opacity: 0.5;
  }
}
@keyframes shimmer {
  0% {
    background-position: -200% 0;
  }
  100% {
    background-position: 200% 0;
  }
}
/* Responsive */
@media (max-width: 1024px) {
  .grid {
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)) !important;
  }
}
@media (max-width: 640px) {
  .grid {
    grid-template-columns: repeat(2, 1fr) !important;
  }
  .uniform-grid {
    grid-auto-rows: 200px;
  }
}
</style>

// snippets/components/angular/grid/4/grid.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

interface GridItem {
  id: string | number;
  content: string;
  image?: string;
  title?: string;
  description?: string;
}

interface GridTheme {
  primaryColor: string;
  backgroundColor: string;
  cardColor: string;
  textColor: string;
  borderColor: string;
  shadowColor: string;
}

@Component({
  selector: 'app-grid',
  template: \`
    <div class="grid-container" [ngStyle]="containerStyles">
      <div *ngIf="loading" class="grid-wrapper" [ngStyle]="gridStyles">
        <div *ngFor="let item of [1,2,3,4,5,6]" class="grid-item skeleton" [ngStyle]="skeletonStyles"></div>
      </div>
      <div *ngIf="!loading" class="grid-wrapper card-layout" [ngStyle]="gridStyles">
        <div *ngFor="let item of items"
             class="grid-item card-gradient"
             [ngStyle]="itemStyles"
             (click)="onItemClick(item)">
          <div class="gradient-overlay"></div>
          <img *ngIf="item.image" [src]="item.image" [alt]="item.title" class="background-img">
          <div class="card-body">
            <div class="icon-badge">{{ item.id }}</div>
            <h3 *ngIf="item.title" class="item-title">{{ item.title }}</h3>
            <p class="item-content">{{ item.content }}</p>
            <span *ngIf="item.description" class="item-tag">{{ item.description }}</span>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .grid-container { width: 100%; min-height: 100vh; }
    .grid-wrapper { display: grid; width: 100%; }
    .card-layout .grid-item { min-height: 300px; }
    .grid-item { cursor: pointer; transition: all 0.35s cubic-bezier(0.4, 0, 0.2, 1); overflow: hidden; position: relative; }
    .grid-item:hover { transform: translateY(-12px) scale(1.02); }
    .card-gradient { background: linear-gradient(135deg, var(--grad-start) 0%, var(--grad-end) 100%); box-shadow: 0 10px 30px -10px rgba(139, 92, 246, 0.3); border-radius: 1.25rem; }
    .card-gradient:hover { box-shadow: 0 20px 50px -10px rgba(139, 92, 246, 0.5); }
    .gradient-overlay { position: absolute; inset: 0; background: linear-gradient(to bottom right, rgba(255,255,255,0.15), transparent); pointer-events: none; }
    .background-img { position: absolute; width: 100%; height: 100%; object-fit: cover; opacity: 0.15; }
    .card-body { position: relative; padding: 2rem; z-index: 1; color: white; }
    .icon-badge { width: 50px; height: 50px; border-radius: 50%; background: rgba(255,255,255,0.25); display: flex; align-items: center; justify-content: center; font-weight: 700; margin-bottom: 1rem; backdrop-filter: blur(10px); }
    .item-title { font-size: 1.5rem; font-weight: 800; margin: 0 0 1rem 0; text-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    .item-content { font-size: 1rem; line-height: 1.6; margin: 0 0 1.5rem 0; opacity: 0.95; }
    .item-tag { display: inline-block; padding: 0.375rem 1rem; background: rgba(255,255,255,0.2); border-radius: 2rem; font-size: 0.75rem; font-weight: 600; backdrop-filter: blur(5px); border: 1px solid rgba(255,255,255,0.3); }
    .skeleton { animation: pulse 2s ease-in-out infinite; border-radius: 1.25rem; background: linear-gradient(135deg, #e0e7ff 0%, #c7d2fe 100%); min-height: 300px; }
    @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.6; } }
  `]
})
export class GridComponent {
  @Input() items: GridItem[] = [];
  @Input() theme: Partial<GridTheme> = {};
  @Input() columns: 1 | 2 | 3 | 4 | 6 | 12 = 3;
  @Input() gap: 'xs' | 'sm' | 'md' | 'lg' | 'xl' = 'lg';
  @Input() variant: 'masonry' | 'uniform' | 'card' | 'minimal' | 'detailed' = 'card';
  @Input() loading: boolean = false;
  @Output() itemClicked = new EventEmitter<GridItem>();

  private defaultTheme: GridTheme = {
    primaryColor: '#8b5cf6',
    backgroundColor: '#faf5ff',
    cardColor: '#8b5cf6',
    textColor: '#ffffff',
    borderColor: '#e5e7eb',
    shadowColor: 'rgba(0,0,0,0.1)'
  };

  get appliedTheme(): GridTheme {
    return { ...this.defaultTheme, ...this.theme };
  }

  get containerStyles() {
    return {
      backgroundColor: this.appliedTheme.backgroundColor,
      padding: '2rem'
    };
  }

  get gridStyles() {
    const gapMap = { xs: '0.5rem', sm: '1rem', md: '1.5rem', lg: '2rem', xl: '3rem' };
    return {
      gap: gapMap[this.gap],
      gridTemplateColumns: `repeat(${this.columns}, 1fr)`
    };
  }

  get itemStyles() {
    return {
      '--grad-start': this.appliedTheme.primaryColor,
      '--grad-end': this.appliedTheme.cardColor
    };
  }

  get skeletonStyles() {
    return {
      minHeight: '300px'
    };
  }

  onItemClick(item: GridItem) {
    this.itemClicked.emit(item);
  }
}
