// snippets/screens/react/onboarding_carousel_screen/3/onboarding_carousel_screen.jsx
import React, { useState, useEffect } from 'react';
import { Brain, Quiz, TrendingUp, ArrowRight, ChevronLeft, ChevronRight } from 'lucide-react';

const OnboardingCarouselScreen = ({ onComplete, onSkip }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isAnimating, setIsAnimating] = useState(false);

  const pages = [
    {
      icon: Brain,
      title: "Discover Your AI Potential",
      description: "Explore the fascinating world of artificial intelligence and discover how smart you really are.",
      color: "from-indigo-500 to-indigo-600"
    },
    {
      icon: Quiz,
      title: "Take Smart Challenges",
      description: "Engage with carefully crafted questions designed to test your AI knowledge and reasoning skills.",
      color: "from-purple-500 to-purple-600"
    },
    {
      icon: TrendingUp,
      title: "Track Your Progress",
      description: "Monitor your improvement over time and compete with friends to see who has the highest AIQ score.",
      color: "from-cyan-500 to-cyan-600"
    }
  ];

  const nextPage = () => {
    if (isAnimating) return;

    if (currentIndex < pages.length - 1) {
      setIsAnimating(true);
      setTimeout(() => {
        setCurrentIndex(currentIndex + 1);
        setIsAnimating(false);
      }, 150);
    } else {
      onComplete?.();
    }
  };

  const previousPage = () => {
    if (isAnimating || currentIndex === 0) return;

    setIsAnimating(true);
    setTimeout(() => {
      setCurrentIndex(currentIndex - 1);
      setIsAnimating(false);
    }, 150);
  };

  const currentPage = pages[currentIndex];
  const IconComponent = currentPage.icon;

  return (
    <div className={`min-h-screen bg-gradient-to-b ${currentPage.color} text-white transition-all duration-500`}>
      <div className="flex flex-col min-h-screen">
        {/* Skip button */}
        <div className="flex justify-end p-6">
          <button
            onClick={onSkip}
            className="text-white/80 hover:text-white transition-colors text-lg font-medium"
          >
            Skip
          </button>
        </div>

        {/* Page content */}
        <div className="flex-1 flex items-center justify-center px-6">
          <div className={`text-center transition-all duration-300 ${isAnimating ? 'opacity-0 transform scale-95' : 'opacity-100 transform scale-100'}`}>
            {/* Icon */}
            <div className="mb-12">
              <div className="w-30 h-30 bg-white/20 rounded-full mx-auto flex items-center justify-center">
                <IconComponent size={60} className="text-white" />
              </div>
            </div>

            {/* Content */}
            <h1 className="text-3xl md:text-4xl font-bold mb-6 leading-tight">
              {currentPage.title}
            </h1>
            <p className="text-lg text-white/80 leading-relaxed max-w-md mx-auto">
              {currentPage.description}
            </p>
          </div>
        </div>

        {/* Navigation */}
        <div className="p-6">
          {/* Page indicators */}
          <div className="flex justify-center mb-8">
            {pages.map((_, index) => (
              <div
                key={index}
                className={`h-2 mx-1 rounded-full transition-all duration-300 ${
                  index === currentIndex
                    ? 'w-6 bg-white'
                    : 'w-2 bg-white/40'
                }`}
              />
            ))}
          </div>

          {/* Navigation buttons */}
          <div className="flex items-center justify-between">
            <button
              onClick={previousPage}
              className={`p-3 rounded-full transition-all ${
                currentIndex === 0
                  ? 'invisible'
                  : 'bg-white/20 hover:bg-white/30 active:bg-white/40'
              }`}
            >
              <ChevronLeft size={24} />
            </button>

            <button
              onClick={nextPage}
              className="bg-white text-gray-800 px-8 py-4 rounded-2xl font-semibold hover:bg-white/90 transition-all flex items-center space-x-2"
            >
              <span>
                {currentIndex === pages.length - 1 ? 'Get Started' : 'Next'}
              </span>
              {currentIndex < pages.length - 1 && <ArrowRight size={20} />}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default OnboardingCarouselScreen;

// snippets/screens/angular-ionic/onboarding_carousel_screen/1/onboarding_carousel_screen.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { IonSlides } from '@ionic/angular';
import { Router } from '@angular/router';

interface OnboardingPage {
  icon: string;
  title: string;
  description: string;
  color: string;
}

@Component({
  selector: 'app-onboarding-carousel',
  template: `
    <ion-content [style.--background]="currentBackgroundGradient" class="onboarding-container">
      <!-- Skip Button -->
      <div class="header">
        <ion-button fill="clear" color="light" (click)="skip()">
          Skip
        </ion-button>
      </div>

      <!-- Slides -->
      <ion-slides #slides pager="false" [options]="slideOpts" (ionSlideDidChange)="onSlideChange()">
        <ion-slide *ngFor="let page of pages">
          <div class="slide-content">
            <!-- Icon -->
            <div class="icon-container">
              <ion-icon [name]="page.icon" class="page-icon"></ion-icon>
            </div>

            <!-- Content -->
            <h1 class="page-title">{{ page.title }}</h1>
            <p class="page-description">{{ page.description }}</p>
          </div>
        </ion-slide>
      </ion-slides>

      <!-- Navigation -->
      <div class="navigation">
        <!-- Page Indicators -->
        <div class="indicators">
          <div
            *ngFor="let page of pages; let i = index"
            class="indicator"
            [class.active]="i === currentIndex"
          ></div>
        </div>

        <!-- Next Button -->
        <ion-button
          expand="block"
          fill="solid"
          color="light"
          class="next-button"
          (click)="nextSlide()"
        >
          <span>{{ isLastSlide ? 'Get Started' : 'Next' }}</span>
          <ion-icon *ngIf="!isLastSlide" name="arrow-forward" slot="end"></ion-icon>
        </ion-button>
      </div>
    </ion-content>
  `,
  styles: [`
    .onboarding-container {
      color: white;
    }

    .header {
      display: flex;
      justify-content: flex-end;
      padding: 16px;
      padding-top: 60px;
    }

    ion-slides {
      height: 60%;
    }

    .slide-content {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 24px;
      height: 100%;
    }

    .icon-container {
      width: 120px;
      height: 120px;
      background: rgba(255, 255, 255, 0.2);
      border-radius: 60px;
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 48px;
    }

    .page-icon {
      font-size: 60px;
      color: white;
    }

    .page-title {
      font-size: 28px;
      font-weight: 700;
      margin-bottom: 24px;
      line-height: 1.2;
    }

    .page-description {
      font-size: 16px;
      opacity: 0.8;
      line-height: 1.5;
      max-width: 320px;
    }

    .navigation {
      padding: 24px;
    }

    .indicators {
      display: flex;
      justify-content: center;
      gap: 8px;
      margin-bottom: 32px;
    }

    .indicator {
      width: 8px;
      height: 8px;
      border-radius: 4px;
      background: rgba(255, 255, 255, 0.4);
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    }

    .indicator.active {
      width: 24px;
      background: white;
    }

    .next-button {
      --border-radius: 16px;
      --color: var(--current-color);
      margin: 0;
      height: 56px;
      font-weight: 600;
    }
  
    
    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(10px); }
      to { opacity: 1; transform: translateY(0); }
    }
    
    @keyframes slideIn {
      from { transform: translateX(-20px); opacity: 0; }
      to { transform: translateX(0); opacity: 1; }
    }
    
    @keyframes scaleIn {
      from { transform: scale(0.95); opacity: 0; }
      to { transform: scale(1); opacity: 1; }
    }
  `]
})
export class OnboardingCarouselScreenComponent implements OnInit {
  @ViewChild('slides', { static: true }) slides!: IonSlides;

  currentIndex = 0;
  currentBackgroundGradient = 'linear-gradient(180deg, #6366F1 0%, rgba(99, 102, 241, 0.8) 100%)';

  pages: OnboardingPage[] = [
    {
      icon: 'bulb-outline',
      title: 'Discover Your AI Potential',
      description: 'Explore the fascinating world of artificial intelligence and discover how smart you really are.',
      color: '#6366F1'
    },
    {
      icon: 'help-circle-outline',
      title: 'Take Smart Challenges',
      description: 'Engage with carefully crafted questions designed to test your AI knowledge and reasoning skills.',
      color: '#8B5CF6'
    },
    {
      icon: 'trending-up-outline',
      title: 'Track Your Progress',
      description: 'Monitor your improvement over time and compete with friends to see who has the highest AIQ score.',
      color: '#06B6D4'
    }
  ];

  slideOpts = {
    initialSlide: 0,
    speed: 400,
    spaceBetween: 0,
  };

  constructor(private router: Router) {}

  ngOnInit() {}

  get isLastSlide(): boolean {
    return this.currentIndex === this.pages.length - 1;
  }

  async onSlideChange() {
    const index = await this.slides.getActiveIndex();
    this.currentIndex = index;
    this.updateBackground();
  }

  private updateBackground() {
    const currentColor = this.pages[this.currentIndex].color;
    this.currentBackgroundGradient = `linear-gradient(180deg, ${currentColor} 0%, ${currentColor}CC 100%)`;
  }

  async nextSlide() {
    if (this.isLastSlide) {
      this.router.navigate(['/welcome']);
    } else {
      await this.slides.slideNext();
    }
  }

  skip() {
    this.router.navigate(['/welcome']);
  }
}
