// snippets/screens/react-native/success_screen/1/success_screen.jsx
import React, { useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Animated,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import Icon from 'react-native-vector-icons/MaterialIcons';

const SuccessScreen = ({
  title = "Success!",
  message = "Your profile has been created successfully. You're ready to start your AIQ journey!",
  buttonText = "Get Started",
  onContinue,
}) => {
  const scaleAnim = new Animated.Value(0);
  const fadeAnim = new Animated.Value(0);

  useEffect(() => {
    Animated.sequence([
      Animated.spring(scaleAnim, {
        toValue: 1,
        tension: 50,
        friction: 7,
        useNativeDriver: true,
      }),
      Animated.timing(fadeAnim, {
        toValue: 1,
        duration: 600,
        useNativeDriver: true,
      }),
    ]).start();
  }, []);

  return (
    <LinearGradient
      colors={['#10B981', '#059669']}
      style={styles.container}
    >
      <View style={styles.content}>
        {/* Success Icon */}
        <Animated.View
          style={[
            styles.iconContainer,
            {
              transform: [{ scale: scaleAnim }],
            },
          ]}
        >
          <View style={styles.iconCircle}>
            <Icon name="check" size={60} color="#10B981" />
          </View>
        </Animated.View>

        {/* Content */}
        <Animated.View
          style={[styles.textContainer, { opacity: fadeAnim }]}
        >
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.message}>{message}</Text>
        </Animated.View>

        {/* Floating Elements */}
        <View style={styles.floatingElements}>
          <Text style={[styles.emoji, styles.emoji1]}>✨</Text>
          <Text style={[styles.emoji, styles.emoji2]}>🎉</Text>
          <Text style={[styles.emoji, styles.emoji3]}>⭐</Text>
          <Text style={[styles.emoji, styles.emoji4]}>🚀</Text>
        </View>

        {/* Continue Button */}
        <Animated.View style={[styles.buttonContainer, { opacity: fadeAnim }]}>
          <TouchableOpacity style={styles.continueButton} onPress={onContinue}>
            <Text style={styles.buttonText}>{buttonText}</Text>
            <Icon name="arrow-forward" size={20} color="#10B981" />
          </TouchableOpacity>
        </Animated.View>
      </View>
    </LinearGradient>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  iconContainer: {
    marginBottom: 40,
  },
  iconCircle: {
    width: 120,
    height: 120,
    backgroundColor: 'white',
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 15,
    },
    shadowOpacity: 0.2,
    shadowRadius: 30,
    elevation: 30,
  },
  textContainer: {
    alignItems: 'center',
    marginBottom: 60,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
    marginBottom: 16,
  },
  message: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    lineHeight: 24,
  },
  floatingElements: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  emoji: {
    position: 'absolute',
    fontSize: 20,
  },
  emoji1: {
    top: '20%',
    left: '20%',
  },
  emoji2: {
    top: '15%',
    right: '15%',
  },
  emoji3: {
    bottom: '40%',
    left: '15%',
  },
  emoji4: {
    bottom: '35%',
    right: '20%',
  },
  buttonContainer: {
    width: '100%',
  },
  continueButton: {
    backgroundColor: 'white',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#10B981',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
});

export default SuccessScreen;

// snippets/screens/angular-ionic/success_screen/1/success_screen.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-success-screen',
  template: `
    <ion-content class="success-container">
      <div class="content-wrapper">
        <!-- Success Icon -->
        <div class="icon-container" [style.transform]="'scale(' + iconScale + ')'">
          <div class="success-circle">
            <ion-icon name="checkmark" class="success-icon"></ion-icon>
          </div>
        </div>

        <!-- Content -->
        <div class="content" [style.opacity]="contentOpacity">
          <h1 class="title">{{ title || 'Success!' }}</h1>
          <p class="message">
            {{ message || "Your profile has been created successfully. You're ready to start your AIQ journey!" }}
          </p>
        </div>

        <!-- Floating Elements -->
        <div class="floating-elements" [style.opacity]="contentOpacity">
          <div class="particle particle-1">✨</div>
          <div class="particle particle-2">🎉</div>
          <div class="particle particle-3">⭐</div>
          <div class="particle particle-4">🚀</div>
        </div>

        <!-- Continue Button -->
        <div class="button-container" [style.opacity]="contentOpacity">
          <ion-button
            expand="block"
            fill="solid"
            color="light"
            class="continue-button"
            (click)="continue()"
          >
            {{ buttonText || 'Get Started' }}
            <ion-icon name="arrow-forward" slot="end"></ion-icon>
          </ion-button>
        </div>
      </div>
    </ion-content>
  `,
  styles: [`
    .success-container {
      --background: linear-gradient(180deg, #10B981 0%, #059669 100%);
      color: white;
    }

    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 24px;
      text-align: center;
      position: relative;
    }

    .icon-container {
      margin-bottom: 40px;
      transition: transform 0.8s cubic-bezier(0.175, 0.885, 0.32, 1.275);
    }

    .success-circle {
      width: 120px;
      height: 120px;
      background: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.07), 0 10px 20px rgba(0, 0, 0, 0.05);
    }

    .success-icon {
      font-size: 60px;
      color: #10B981;
    }

    .content {
      margin-bottom: 60px;
      transition: opacity 0.6s ease-out;
    }

    .title {
      font-size: 32px;
      font-weight: 700;
      margin-bottom: 16px;
      line-height: 1.2;
    }

    .message {
      font-size: 16px;
      opacity: 0.8;
      line-height: 1.5;
      max-width: 320px;
    }

    .floating-elements {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      pointer-events: none;
      transition: opacity 0.4s ease-out;
    }

    .particle {
      position: absolute;
      font-size: 20px;
      animation: float-up 2s ease-out forwards;
    }

    .particle-1 {
      top: 20%;
      left: 20%;
      animation-delay: 0.2s;
    }

    .particle-2 {
      top: 15%;
      right: 15%;
      animation-delay: 0.4s;
    }

    .particle-3 {
      bottom: 40%;
      left: 15%;
      animation-delay: 0.6s;
    }

    .particle-4 {
      bottom: 35%;
      right: 20%;
      animation-delay: 0.8s;
    }

    @keyframes float-up {
      0% {
        transform: translateY(20px);
        opacity: 0;
      }
      50% {
        opacity: 1;
      }
      100% {
        transform: translateY(-20px);
        opacity: 0.5;
      }
    }

    .button-container {
      width: 100%;
      max-width: 320px;
      transition: opacity 0.6s ease-out;
    }

    .continue-button {
      --border-radius: 16px;
      --background: white;
      --color: #10B981;
      height: 56px;
      margin: 0;
      font-weight: 600;
    }
  `]
})
export class SuccessScreenComponent implements OnInit {
  @Input() title?: string;
  @Input() message?: string;
  @Input() buttonText?: string;

  iconScale = 0;
  contentOpacity = 0;

  constructor(private router: Router) {}

  ngOnInit() {
    this.startAnimations();
  }

  private startAnimations() {
    // Icon scale animation
    setTimeout(() => {
      this.iconScale = 1;
    }, 200);

    // Content fade in
    setTimeout(() => {
      this.contentOpacity = 1;
    }, 400);
  }

  continue() {
    this.router.navigate(['/main']);
  }
}
