// snippets/components/svelte/card/7/card.svelte
<script lang="ts">
  export let title: string = '';
  export let subtitle: string = '';
  export let padding: string = '1.5rem';
</script>

<div class="modern-card">
  {#if title || subtitle}
    <div class="card-head">
      {#if title}
        <h3 class="card-heading">{title}</h3>
      {/if}
      {#if subtitle}
        <p class="card-subheading">{subtitle}</p>
      {/if}
    </div>
  {/if}
  <div class="card-main" style="padding: {padding}">
    <slot />
  </div>
</div>

<style>
  .modern-card {
    background: white;
    border-radius: 6px;
    border: 1px solid #f3f4f6;
    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
    overflow: hidden;
    transition: box-shadow 0.2s;
  }
  
  .modern-card:hover {
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
  }
  
  .card-head {
    padding: 1.25rem 1.5rem;
    border-bottom: 1px solid #e5e7eb;
    background: linear-gradient(to bottom, #ffffff, #fafafa);
  }
  
  .card-heading {
    font-size: 1.125rem;
    font-weight: 700;
    color: #111827;
    margin: 0 0 0.25rem 0;
  }
  
  .card-subheading {
    font-size: 0.875rem;
    color: #6b7280;
    margin: 0;
  }
  
  .card-main {
    color: #374151;
  }
</style>

// snippets/components/vue/card/1/card.vue
<template>
  <div class="custom-card" :class="{ elevated, bordered }">
    <div v-if="$slots.header || title" class="card-header">
      <h3 v-if="title" class="card-title">{{ title }}</h3>
      <slot name="header" />
    </div>
    <div class="card-body">
      <slot />
    </div>
    <div v-if="$slots.footer" class="card-footer">
      <slot name="footer" />
    </div>
  </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({
  name: 'CustomCard',
  props: {
    title: { type: String, default: '' },
    elevated: { type: Boolean, default: true },
    bordered: { type: Boolean, default: false }
  }
});
</script>
<style scoped>
.custom-card {
  background: white;
  border-radius: 1rem;
  overflow: hidden;
}
.custom-card.elevated {
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
}
.custom-card.bordered {
  border: 2px solid #e5e7eb;
}
.card-header {
  padding: 1.25rem 1.5rem;
  border-bottom: 1px solid #f3f4f6;
  background: linear-gradient(to bottom, #fafafa, #ffffff);
}
.card-title {
  font-size: 1.25rem;
  font-weight: 700;
  color: #111827;
  margin: 0;
}
.card-body {
  padding: 1.5rem;
}
.card-footer {
  padding: 1rem 1.5rem;
  border-top: 1px solid #f3f4f6;
  background: #f9fafb;
}
</style>
