// snippets/components/svelte/button/15/button.svelte
<script lang="ts">
  import { writable } from 'svelte/store';
  import { createEventDispatcher } from 'svelte';

  export interface ButtonTheme {
    primary: string;
    secondary: string;
    success: string;
    danger: string;
    warning: string;
    info: string;
  }

  export let variant: 'solid' | 'outline' | 'ghost' | 'gradient' | 'glass' | 'neumorphic' = 'glass';
  export let size: 'xs' | 'sm' | 'md' | 'lg' | 'xl' = 'md';
  export let fullWidth: boolean = false;
  export let loading: boolean = false;
  export let icon: string = '';
  export let iconPosition: 'left' | 'right' = 'left';
  export let disabled: boolean = false;
  export let theme: keyof ButtonTheme = 'primary';

  const dispatch = createEventDispatcher();
  const shining = writable(false);

  const themes: ButtonTheme = {
    primary: '#a855f7',
    secondary: '#10b981',
    success: '#3b82f6',
    danger: '#ef4444',
    warning: '#f59e0b',
    info: '#14b8a6'
  };

  const sizes = {
    xs: 'px-2 py-1 text-xs',
    sm: 'px-3 py-1.5 text-sm',
    md: 'px-4 py-2 text-base',
    lg: 'px-6 py-3 text-lg',
    xl: 'px-8 py-4 text-xl'
  };

  function handleClick(event: MouseEvent) {
    if (!disabled && !loading) {
      dispatch('click', event);
    }
  }
</script>

<button
  class="btn {sizes[size]} {variant} {theme}"
  class:full-width={fullWidth}
  class:loading={loading}
  {disabled}
  on:click={handleClick}
>
  {#if loading}
    <span class="spinner ring"></span>
  {:else}
    {#if icon && iconPosition === 'left'}
      <slot name="icon-left">{icon}</slot>
    {/if}
    <slot></slot>
    {#if icon && iconPosition === 'right'}
      <slot name="icon-right">{icon}</slot>
    {/if}
  {/if}
</button>

<style>
  .btn {
    position: relative;
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    border: 2px solid rgba(255, 255, 255, 0.25);
    border-radius: 18px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s ease;
    backdrop-filter: blur(15px) brightness(1.1);
  }

  .full-width {
    width: 100%;
    justify-content: center;
  }

  /* Frosted Glass Effect */
  .glass.primary {
    background: rgba(168, 85, 247, 0.18);
    color: #a855f7;
    box-shadow: 0 10px 40px rgba(168, 85, 247, 0.25), inset 0 2px 0 rgba(255, 255, 255, 0.2);
  }

  .glass.primary:hover {
    background: rgba(168, 85, 247, 0.28);
    box-shadow: 0 15px 50px rgba(168, 85, 247, 0.35), inset 0 2px 0 rgba(255, 255, 255, 0.3);
    transform: translateY(-3px);
  }

  .glass.secondary {
    background: rgba(16, 185, 129, 0.18);
    color: #10b981;
    box-shadow: 0 10px 40px rgba(16, 185, 129, 0.25), inset 0 2px 0 rgba(255, 255, 255, 0.2);
  }

  .glass.secondary:hover {
    transform: translateY(-3px);
  }

  .glass.success {
    background: rgba(59, 130, 246, 0.18);
    color: #3b82f6;
    box-shadow: 0 10px 40px rgba(59, 130, 246, 0.25), inset 0 2px 0 rgba(255, 255, 255, 0.2);
  }

  .glass.danger {
    background: rgba(239, 68, 68, 0.18);
    color: #ef4444;
    box-shadow: 0 10px 40px rgba(239, 68, 68, 0.25), inset 0 2px 0 rgba(255, 255, 255, 0.2);
  }

  .glass.warning {
    background: rgba(245, 158, 11, 0.18);
    color: #f59e0b;
    box-shadow: 0 10px 40px rgba(245, 158, 11, 0.25), inset 0 2px 0 rgba(255, 255, 255, 0.2);
  }

  .glass.info {
    background: rgba(20, 184, 166, 0.18);
    color: #14b8a6;
    box-shadow: 0 10px 40px rgba(20, 184, 166, 0.25), inset 0 2px 0 rgba(255, 255, 255, 0.2);
  }

  /* Loading State */
  .btn.loading {
    pointer-events: none;
    opacity: 0.7;
  }

  .spinner.ring {
    width: 1.2em;
    height: 1.2em;
    border: 3px solid transparent;
    border-top-color: currentColor;
    border-right-color: currentColor;
    border-radius: 50%;
    animation: ring 1s cubic-bezier(0.68, -0.55, 0.265, 1.55) infinite;
  }

  @keyframes ring {
    0% { transform: rotate(0deg) scale(1); }
    50% { transform: rotate(180deg) scale(1.1); }
    100% { transform: rotate(360deg) scale(1); }
  }

  .btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>

// snippets/components/vue/button/18/button.vue
<template>
  <button
    :class="buttonClasses"
    :disabled="disabled || loading"
    @click="handleClick"
  >
    <span v-if="loading" class="spinner"></span>
    <span v-if="icon && iconPosition === 'left' && !loading" class="icon-left">{{ icon }}</span>
    <span class="button-content"><slot /></span>
    <span v-if="icon && iconPosition === 'right' && !loading" class="icon-right">{{ icon }}</span>
  </button>
</template>

<script lang="ts">
import { defineComponent, computed, PropType } from 'vue';

interface ButtonTheme {
  primary: string;
  secondary: string;
  success: string;
  danger: string;
  warning: string;
  info: string;
}

export default defineComponent({
  name: 'Button',
  props: {
    variant: {
      type: String as PropType<'solid' | 'outline' | 'ghost' | 'glass'>,
      default: 'solid'
    },
    size: {
      type: String as PropType<'xs' | 'sm' | 'md' | 'lg' | 'xl'>,
      default: 'md'
    },
    fullWidth: {
      type: Boolean,
      default: false
    },
    loading: {
      type: Boolean,
      default: false
    },
    icon: {
      type: String,
      default: ''
    },
    iconPosition: {
      type: String as PropType<'left' | 'right'>,
      default: 'left'
    },
    disabled: {
      type: Boolean,
      default: false
    },
    theme: {
      type: Object as PropType<Partial<ButtonTheme>>,
      default: () => ({})
    }
  },
  emits: ['click'],
  setup(props, { emit }) {
    const defaultTheme: ButtonTheme = {
      primary: '#475569',
      secondary: '#334155',
      success: '#10b981',
      danger: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6'
    };

    const appliedTheme = { ...defaultTheme, ...props.theme };

    const buttonClasses = computed(() => [
      'btn',
      `btn-${props.variant}`,
      `btn-${props.size}`,
      { 'btn-full-width': props.fullWidth },
      { 'btn-loading': props.loading }
    ]);

    const handleClick = (event: MouseEvent) => {
      if (!props.disabled && !props.loading) {
        emit('click', event);
      }
    };

    return { buttonClasses, handleClick };
  }
});
</script>

<style scoped>
.btn {
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  font-weight: 600;
  border: none;
  border-radius: 1.25rem;
  cursor: pointer;
  transition: all 0.3s ease;
  font-family: inherit;
  outline: none;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* Sizes */
.btn-xs {
  padding: 0.375rem 0.75rem;
  font-size: 0.75rem;
}

.btn-sm {
  padding: 0.5rem 1rem;
  font-size: 0.875rem;
}

.btn-md {
  padding: 0.625rem 1.25rem;
  font-size: 1rem;
}

.btn-lg {
  padding: 0.75rem 1.5rem;
  font-size: 1.125rem;
}

.btn-xl {
  padding: 1rem 2rem;
  font-size: 1.25rem;
}

/* Solid Variant - Slate */
.btn-solid {
  background: linear-gradient(135deg, #475569 0%, #334155 100%);
  color: white;
  box-shadow: 0 4px 12px rgba(71, 85, 105, 0.35);
}

.btn-solid:hover:not(:disabled) {
  background: linear-gradient(135deg, #334155 0%, #475569 100%);
  box-shadow: 0 6px 18px rgba(71, 85, 105, 0.45);
  transform: translateY(-2px);
}

.btn-solid:active:not(:disabled) {
  transform: translateY(0);
}

/* Outline Variant */
.btn-outline {
  background: transparent;
  color: #475569;
  border: 2px solid #475569;
  box-shadow: none;
}

.btn-outline:hover:not(:disabled) {
  background: #475569;
  color: white;
  box-shadow: 0 4px 12px rgba(71, 85, 105, 0.3);
  transform: translateY(-2px);
}

/* Ghost Variant */
.btn-ghost {
  background: transparent;
  color: #475569;
  box-shadow: none;
}

.btn-ghost:hover:not(:disabled) {
  background: rgba(71, 85, 105, 0.1);
  transform: scale(1.05);
}

/* Special Variant Styles */
.btn-glass {
  background: rgba(71, 85, 105, 0.2);
  color: #334155;
  backdrop-filter: blur(10px);
  border: 1px solid rgba(71, 85, 105, 0.3);
  box-shadow: 0 8px 32px rgba(71, 85, 105, 0.2);
}

.btn-glass:hover:not(:disabled) {
  background: rgba(71, 85, 105, 0.3);
  border-color: rgba(71, 85, 105, 0.5);
  transform: translateY(-2px);
}

.btn-full-width {
  width: 100%;
}

/* Loading Spinner */
.spinner {
  width: 1rem;
  height: 1rem;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-top-color: white;
  border-radius: 50%;
  animation: roll 0.9s linear infinite;
}

@keyframes roll {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.icon-left, .icon-right {
  display: flex;
  align-items: center;
}

.button-content {
  display: flex;
  align-items: center;
}
</style>
