// snippets/screens/angular-ionic/loading_screen/3/loading_screen.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-loading-screen',
  template: `
    <ion-content [style.--background]="backgroundGradient" class="loading-container">
      <div class="content-wrapper">
        <!-- Loading Animation -->
        <div class="animation-container">
          <div class="pulse-ring" [style.transform]="'scale(' + pulseScale + ')'"></div>
          <div class="spinner-ring">
            <ion-spinner name="crescent" color="light"></ion-spinner>
          </div>
          <div class="inner-icon">
            <ion-icon name="bulb" [style.color]="primaryColor"></ion-icon>
          </div>
        </div>

        <!-- Title -->
        <h1 class="title">{{ title || 'Loading' }}</h1>

        <!-- Message -->
        <div class="message-container">
          <p class="message">{{ currentMessage }}</p>
        </div>

        <!-- Progress -->
        <div class="progress-container">
          <div *ngIf="showProgress" class="progress-section">
            <div *ngIf="progress !== undefined" class="progress-text">
              {{ Math.round(progress * 100) }}%
            </div>
            <ion-progress-bar
              [value]="progress || 0"
              color="light"
              class="progress-bar"
            ></ion-progress-bar>
          </div>

          <div *ngIf="!showProgress" class="dots-container">
            <div class="dot" *ngFor="let dot of [0,1,2]; let i = index" [style.animation-delay]="(i * 0.2) + 's'"></div>
          </div>
        </div>
      </div>
    </ion-content>
  `,
  styles: [`
    .loading-container {
      color: white;
    }

    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 32px;
      text-align: center;
    }

    .animation-container {
      position: relative;
      width: 80px;
      height: 80px;
      margin-bottom: 40px;
    }

    .pulse-ring {
      position: absolute;
      width: 80px;
      height: 80px;
      border-radius: 50%;
      background: rgba(255, 255, 255, 0.2);
      animation: pulse 1.5s ease-in-out infinite alternate;
    }

    @keyframes pulse {
      from { transform: scale(1); }
      to { transform: scale(1.2); }
    }

    .spinner-ring {
      position: absolute;
      top: 8px;
      left: 8px;
      width: 64px;
      height: 64px;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .inner-icon {
      position: absolute;
      top: 16px;
      left: 16px;
      width: 48px;
      height: 48px;
      background: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .inner-icon ion-icon {
      font-size: 24px;
    }

    .title {
      font-size: 28px;
      font-weight: 700;
      margin-bottom: 16px;
    }

    .message-container {
      height: 48px;
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 40px;
    }

    .message {
      font-size: 16px;
      opacity: 0.8;
      line-height: 1.4;
      max-width: 280px;
    }

    .progress-container {
      width: 100%;
      max-width: 280px;
    }

    .progress-section {
      width: 100%;
    }

    .progress-text {
      text-align: right;
      font-size: 14px;
      opacity: 0.7;
      margin-bottom: 8px;
      font-weight: 500;
    }

    .progress-bar {
      --background: rgba(255, 255, 255, 0.3);
      --progress-background: white;
      height: 4px;
      border-radius: 2px;
    }

    .dots-container {
      display: flex;
      justify-content: center;
      gap: 8px;
    }

    .dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: rgba(255, 255, 255, 0.6);
      animation: dot-pulse 1.4s ease-in-out infinite;
    }

    @keyframes dot-pulse {
      0%, 80%, 100% { opacity: 0.4; }
      40% { opacity: 1; }
    }
  `]
})
export class LoadingScreenComponent implements OnInit {
  @Input() title?: string;
  @Input() message?: string;
  @Input() showProgress = false;
  @Input() progress?: number;
  @Input() primaryColor = '#6366F1';

  currentMessageIndex = 0;
  pulseScale = 1;

  private loadingMessages = [
    'Preparing your experience...',
    'Loading AI challenges...',
    'Setting up your profile...',
    'Almost ready...'
  ];

  ngOnInit() {
    if (!this.message) {
      this.startMessageCycle();
    }
    this.startPulseAnimation();
  }

  get currentMessage(): string {
    return this.message || this.loadingMessages[this.currentMessageIndex];
  }

  get backgroundGradient(): string {
    return `linear-gradient(180deg, ${this.primaryColor} 0%, ${this.primaryColor}CC 100%)`;
  }

  private startMessageCycle() {
    setInterval(() => {
      this.currentMessageIndex = (this.currentMessageIndex + 1) % this.loadingMessages.length;
    }, 2000);
  }

  private startPulseAnimation() {
    setInterval(() => {
      this.pulseScale = this.pulseScale === 1 ? 1.2 : 1;
    }, 1500);
  }

  Math = Math;
}

// snippets/screens/react/loading_screen/2/loading_screen.jsx
import React, { useState, useEffect } from 'react';
import { Brain } from 'lucide-react';

const LoadingScreen = ({
  title = "Loading",
  message,
  showProgress = false,
  progress,
  primaryColor = "indigo"
}) => {
  const [currentMessageIndex, setCurrentMessageIndex] = useState(0);

  const loadingMessages = [
    "Preparing your experience...",
    "Loading AI challenges...",
    "Setting up your profile...",
    "Almost ready..."
  ];

  useEffect(() => {
    if (!message) {
      const interval = setInterval(() => {
        setCurrentMessageIndex((prev) => (prev + 1) % loadingMessages.length);
      }, 2000);

      return () => clearInterval(interval);
    }
  }, [message]);

  const colorClasses = {
    indigo: 'from-indigo-500 to-indigo-600',
    green: 'from-green-500 to-green-600',
    purple: 'from-purple-500 to-purple-600',
    cyan: 'from-cyan-500 to-cyan-600'
  };

  return (
    <div className={`min-h-screen bg-gradient-to-b ${colorClasses[primaryColor]} text-white flex items-center justify-center p-8`}>
      <div className="text-center w-full max-w-sm">
        {/* Loading Animation */}
        <div className="mb-10">
          <div className="relative">
            {/* Pulse Ring */}
            <div className="w-20 h-20 bg-white/20 rounded-full mx-auto animate-pulse"></div>

            {/* Spinning Ring */}
            <div className="absolute inset-0 w-16 h-16 border-3 border-white border-t-transparent rounded-full animate-spin mx-auto mt-2"></div>

            {/* Inner Icon */}
            <div className="absolute inset-0 w-12 h-12 bg-white rounded-full flex items-center justify-center mx-auto mt-4">
              <Brain size={24} className={`text-${primaryColor}-500`} />
            </div>
          </div>
        </div>

        {/* Title */}
        <h1 className="text-3xl font-bold mb-4">
          {title}
        </h1>

        {/* Message */}
        <div className="h-12 flex items-center justify-center">
          <p className="text-white/80 text-center leading-relaxed">
            {message || loadingMessages[currentMessageIndex]}
          </p>
        </div>

        {/* Progress */}
        <div className="mt-10">
          {showProgress ? (
            <div className="space-y-2">
              {progress !== undefined && (
                <div className="text-right text-sm text-white/70">
                  {Math.round(progress * 100)}%
                </div>
              )}
              <div className="w-full bg-white/30 rounded-full h-1">
                <div
                  className="bg-white h-1 rounded-full transition-all duration-300"
                  style={{ width: progress ? `${progress * 100}%` : '0%' }}
                ></div>
              </div>
            </div>
          ) : (
            <div className="flex justify-center space-x-2">
              {[0, 1, 2].map((i) => (
                <div
                  key={i}
                  className="w-2 h-2 bg-white/60 rounded-full animate-pulse"
                  style={{
                    animationDelay: `${i * 0.2}s`,
                    animationDuration: '1.4s'
                  }}
                ></div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default LoadingScreen;
