// snippets/screens/angular-ionic/welcome_screen/2/welcome_screen.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-welcome-screen',
  template: `
    <ion-content class="welcome-container">
      <div class="content-wrapper" [style.opacity]="contentOpacity" [style.transform]="'translateY(' + contentOffset + 'px)'">
        <!-- Header -->
        <div class="header">
          <ion-chip color="primary" class="welcome-badge">
            <ion-label>Welcome!</ion-label>
          </ion-chip>

          <h1 class="main-title">
            Ready to test your<br>AI intelligence?
          </h1>

          <p class="subtitle">
            Join thousands of users discovering their AI potential. Let's get you started
            on your journey to understanding artificial intelligence.
          </p>
        </div>

        <!-- Illustration -->
        <div class="illustration-container" [style.transform]="'scale(' + illustrationScale + ')'">
          <div class="illustration">
            <ion-icon name="bulb" class="illustration-icon"></ion-icon>
            <!-- Floating elements -->
            <div class="floating-element element-1">✨</div>
            <div class="floating-element element-2">🎉</div>
            <div class="floating-element element-3">⭐</div>
          </div>
        </div>

        <!-- Action Buttons -->
        <div class="buttons-container" [style.opacity]="buttonsOpacity">
          <ion-button
            expand="block"
            fill="solid"
            color="primary"
            class="primary-button"
            (click)="startTutorial()"
          >
            Start Tutorial
            <ion-icon name="arrow-forward" slot="end"></ion-icon>
          </ion-button>

          <ion-button
            expand="block"
            fill="outline"
            color="medium"
            class="secondary-button"
            (click)="skipTutorial()"
          >
            Skip Tutorial
          </ion-button>
        </div>
      </div>
    </ion-content>
  `,
  styles: [`
    .welcome-container {
      --background: #ffffff;
    }

    .content-wrapper {
      display: flex;
      flex-direction: column;
      height: 100vh;
      padding: 24px;
      padding-top: 80px;
      transition: all 0.8s ease-out;
    }

    .header {
      margin-bottom: 40px;
    }

    .welcome-badge {
      margin-bottom: 24px;
      --background: rgba(99, 102, 241, 0.1);
      --color: #6366F1;
    }

    .main-title {
      font-size: 32px;
      font-weight: 700;
      color: #1F2937;
      line-height: 1.2;
      margin-bottom: 16px;
    }

    .subtitle {
      font-size: 16px;
      color: #6B7280;
      line-height: 1.5;
    }

    .illustration-container {
      flex: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      transition: transform 0.8s cubic-bezier(0.175, 0.885, 0.32, 1.275);
    }

    .illustration {
      position: relative;
      width: 200px;
      height: 200px;
      background: linear-gradient(135deg, #6366F1, #8B5CF6);
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      box-shadow: 0 20px 40px rgba(99, 102, 241, 0.3);
    }

    .illustration-icon {
      font-size: 80px;
      color: white;
    }

    .floating-element {
      position: absolute;
      font-size: 20px;
      animation: float 3s ease-in-out infinite;
    }

    .element-1 {
      top: -10px;
      left: -10px;
      animation-delay: 0s;
    }

    .element-2 {
      top: -5px;
      right: -15px;
      animation-delay: 1s;
    }

    .element-3 {
      bottom: -10px;
      left: -5px;
      animation-delay: 2s;
    }

    @keyframes float {
      0%, 100% { transform: translateY(0px); }
      50% { transform: translateY(-10px); }
    }

    .buttons-container {
      display: flex;
      flex-direction: column;
      gap: 16px;
      transition: opacity 0.6s ease-out;
    }

    .primary-button, .secondary-button {
      --border-radius: 16px;
      height: 56px;
      margin: 0;
      font-weight: 600;
    }

    .primary-button {
      --background: #6366F1;
    }

    .secondary-button {
      --border-color: #E5E7EB;
      --color: #6B7280;
    }
  `]
})
export class WelcomeScreenComponent implements OnInit {
  contentOpacity = 0;
  contentOffset = 30;
  illustrationScale = 0.8;
  buttonsOpacity = 0;

  constructor(private router: Router) {}

  ngOnInit() {
    this.startAnimations();
  }

  private startAnimations() {
    // Content fade in
    setTimeout(() => {
      this.contentOpacity = 1;
      this.contentOffset = 0;
    }, 100);

    // Illustration scale
    setTimeout(() => {
      this.illustrationScale = 1;
    }, 400);

    // Buttons fade in
    setTimeout(() => {
      this.buttonsOpacity = 1;
    }, 800);
  }

  startTutorial() {
    this.router.navigate(['/tutorial']);
  }

  skipTutorial() {
    this.router.navigate(['/main']);
  }
}

// snippets/screens/react-native/welcome_screen/1/welcome_screen.jsx
import React, { useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Animated,
  Dimensions,
} from 'react-native';
import Icon from 'react-native-vector-icons/MaterialIcons';

const { width } = Dimensions.get('window');

const WelcomeScreen = ({ onStartTutorial, onSkipTutorial }) => {
  const fadeAnim = new Animated.Value(0);
  const slideAnim = new Animated.Value(30);
  const scaleAnim = new Animated.Value(0.8);

  useEffect(() => {
    Animated.sequence([
      Animated.parallel([
        Animated.timing(fadeAnim, {
          toValue: 1,
          duration: 600,
          useNativeDriver: true,
        }),
        Animated.timing(slideAnim, {
          toValue: 0,
          duration: 800,
          useNativeDriver: true,
        }),
      ]),
      Animated.timing(scaleAnim, {
        toValue: 1,
        duration: 800,
        useNativeDriver: true,
      }),
    ]).start();
  }, []);

  return (
    <View style={styles.container}>
      <Animated.View
        style={[
          styles.content,
          {
            opacity: fadeAnim,
            transform: [{ translateY: slideAnim }],
          },
        ]}
      >
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.badge}>
            <Text style={styles.badgeText}>Welcome!</Text>
          </View>

          <Text style={styles.title}>
            Ready to test your{'\n'}AI intelligence?
          </Text>

          <Text style={styles.subtitle}>
            Join thousands of users discovering their AI potential. Let's get you
            started on your journey to understanding artificial intelligence.
          </Text>
        </View>

        {/* Illustration */}
        <Animated.View
          style={[
            styles.illustrationContainer,
            {
              transform: [{ scale: scaleAnim }],
            },
          ]}
        >
          <View style={styles.illustration}>
            <Icon name="psychology" size={80} color="white" />
          </View>
        </Animated.View>

        {/* Action Buttons */}
        <View style={styles.buttonContainer}>
          <TouchableOpacity
            style={styles.primaryButton}
            onPress={onStartTutorial}
          >
            <Text style={styles.primaryButtonText}>Start Tutorial</Text>
            <Icon name="arrow-forward" size={20} color="white" />
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.secondaryButton}
            onPress={onSkipTutorial}
          >
            <Text style={styles.secondaryButtonText}>Skip Tutorial</Text>
          </TouchableOpacity>
        </View>
      </Animated.View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 80,
  },
  header: {
    marginBottom: 40,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 24,
  },
  badgeText: {
    color: '#6366F1',
    fontSize: 14,
    fontWeight: '600',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1F2937',
    lineHeight: 38,
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 16,
    color: '#6B7280',
    lineHeight: 24,
  },
  illustrationContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  illustration: {
    width: 200,
    height: 200,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6366F1',
    shadowColor: '#6366F1',
    shadowOffset: {
      width: 0,
      height: 20,
    },
    shadowOpacity: 0.3,
    shadowRadius: 40,
    elevation: 20,
  },
  buttonContainer: {
    paddingBottom: 40,
  },
  primaryButton: {
    backgroundColor: '#6366F1',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  primaryButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#6B7280',
    fontSize: 16,
    fontWeight: '500',
  },
});

export default WelcomeScreen;
