// snippets/screens/angular-ionic/error_screen/1/error_screen.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Location } from '@angular/common';

@Component({
  selector: 'app-error-screen',
  template: `
    <ion-content class="error-container">
      <div class="content-wrapper">
        <!-- Error Icon -->
        <div class="icon-container">
          <div class="error-circle">
            <ion-icon name="alert-circle-outline" class="error-icon"></ion-icon>
          </div>
        </div>

        <!-- Content -->
        <div class="content">
          <h1 class="title">{{ title || 'Oops! Something went wrong' }}</h1>
          <p class="message">
            {{ message || "We encountered an unexpected error. Don't worry, it happens to the best of us! Please try again." }}
          </p>
        </div>

        <!-- Error Illustration -->
        <div class="illustration">
          <div class="robot">🤖</div>
        </div>

        <!-- Action Buttons -->
        <div class="buttons-container">
          <ion-button
            expand="block"
            fill="solid"
            color="primary"
            class="retry-button"
            (click)="retry()"
          >
            <ion-icon name="refresh" slot="start"></ion-icon>
            {{ buttonText || 'Try Again' }}
          </ion-button>

          <ion-button
            expand="block"
            fill="outline"
            color="medium"
            class="back-button"
            (click)="goBack()"
          >
            <ion-icon name="arrow-back" slot="start"></ion-icon>
            Go Back
          </ion-button>
        </div>

        <p class="help-text">
          If the problem persists, please contact our support team
        </p>
      </div>
    </ion-content>
  `,
  styles: [`
    .error-container {
      --background: #ffffff;
    }

    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 24px;
      text-align: center;
    }

    .icon-container {
      margin-bottom: 40px;
    }

    .error-circle {
      width: 120px;
      height: 120px;
      background: rgba(239, 68, 68, 0.1);
      border: 2px solid rgba(239, 68, 68, 0.2);
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .error-icon {
      font-size: 60px;
      color: #EF4444;
    }

    .content {
      margin-bottom: 40px;
    }

    .title {
      font-size: 28px;
      font-weight: 700;
      color: #1F2937;
      margin-bottom: 16px;
      line-height: 1.2;
    }

    .message {
      font-size: 16px;
      color: #6B7280;
      line-height: 1.5;
      max-width: 320px;
    }

    .illustration {
      margin-bottom: 40px;
    }

    .robot {
      font-size: 60px;
    }

    .buttons-container {
      width: 100%;
      max-width: 320px;
      display: flex;
      flex-direction: column;
      gap: 12px;
      margin-bottom: 20px;
    }

    .retry-button, .back-button {
      --border-radius: 16px;
      height: 56px;
      margin: 0;
      font-weight: 600;
    }

    .retry-button {
      --background: #6366F1;
    }

    .back-button {
      --border-color: #E5E7EB;
      --color: #6B7280;
    }

    .help-text {
      font-size: 12px;
      color: rgba(107, 114, 128, 0.8);
    }
  `]
})
export class ErrorScreenComponent implements OnInit {
  @Input() title?: string;
  @Input() message?: string;
  @Input() buttonText?: string;

  constructor(private location: Location) {}

  ngOnInit() {}

  retry() {
    // Implement retry logic
    window.location.reload();
  }

  goBack() {
    this.location.back();
  }
}

// snippets/screens/react-native/error_screen/1/error_screen.jsx
import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
} from 'react-native';
import Icon from 'react-native-vector-icons/MaterialIcons';

const ErrorScreen = ({
  title = "Oops! Something went wrong",
  message = "We encountered an unexpected error. Don't worry, it happens to the best of us! Please try again.",
  buttonText = "Try Again",
  onRetry,
  onGoBack,
}) => {
  return (
    <View style={styles.container}>
      <View style={styles.content}>
        {/* Error Icon */}
        <View style={styles.iconContainer}>
          <View style={styles.iconCircle}>
            <Icon name="error-outline" size={60} color="#EF4444" />
          </View>
        </View>

        {/* Content */}
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.message}>{message}</Text>

        {/* Error Illustration */}
        <View style={styles.illustration}>
          <Text style={styles.robotEmoji}>🤖</Text>
        </View>

        {/* Action Buttons */}
        <View style={styles.buttonContainer}>
          <TouchableOpacity style={styles.retryButton} onPress={onRetry}>
            <Icon name="refresh" size={20} color="white" />
            <Text style={styles.retryButtonText}>{buttonText}</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.backButton} onPress={onGoBack}>
            <Icon name="arrow-back" size={20} color="#6B7280" />
            <Text style={styles.backButtonText}>Go Back</Text>
          </TouchableOpacity>
        </View>

        <Text style={styles.helpText}>
          If the problem persists, please contact our support team
        </Text>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  content: {
    alignItems: 'center',
    width: '100%',
    maxWidth: 320,
  },
  iconContainer: {
    marginBottom: 40,
  },
  iconCircle: {
    width: 120,
    height: 120,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1F2937',
    textAlign: 'center',
    marginBottom: 16,
  },
  message: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 40,
  },
  illustration: {
    marginBottom: 40,
  },
  robotEmoji: {
    fontSize: 60,
  },
  buttonContainer: {
    width: '100%',
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: '#6366F1',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  retryButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  backButton: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: '#6B7280',
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 8,
  },
  helpText: {
    fontSize: 12,
    color: 'rgba(107, 114, 128, 0.8)',
    textAlign: 'center',
  },
});

export default ErrorScreen;
