// snippets/screens/angular-ionic/onboarding_carousel_screen/3/onboarding_carousel_screen.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { IonSlides } from '@ionic/angular';
import { Router } from '@angular/router';

interface OnboardingPage {
  icon: string;
  title: string;
  description: string;
  color: string;
}

@Component({
  selector: 'app-onboarding-carousel',
  template: `
    <ion-content [style.--background]="currentBackgroundGradient" class="onboarding-container">
      <!-- Skip Button -->
      <div class="header">
        <ion-button fill="clear" color="light" (click)="skip()">
          Skip
        </ion-button>
      </div>

      <!-- Slides -->
      <ion-slides #slides pager="false" [options]="slideOpts" (ionSlideDidChange)="onSlideChange()">
        <ion-slide *ngFor="let page of pages">
          <div class="slide-content">
            <!-- Icon -->
            <div class="icon-container">
              <ion-icon [name]="page.icon" class="page-icon"></ion-icon>
            </div>

            <!-- Content -->
            <h1 class="page-title">{{ page.title }}</h1>
            <p class="page-description">{{ page.description }}</p>
          </div>
        </ion-slide>
      </ion-slides>

      <!-- Navigation -->
      <div class="navigation">
        <!-- Page Indicators -->
        <div class="indicators">
          <div
            *ngFor="let page of pages; let i = index"
            class="indicator"
            [class.active]="i === currentIndex"
          ></div>
        </div>

        <!-- Next Button -->
        <ion-button
          expand="block"
          fill="solid"
          color="light"
          class="next-button"
          (click)="nextSlide()"
        >
          <span>{{ isLastSlide ? 'Get Started' : 'Next' }}</span>
          <ion-icon *ngIf="!isLastSlide" name="arrow-forward" slot="end"></ion-icon>
        </ion-button>
      </div>
    </ion-content>
  `,
  styles: [`
    .onboarding-container {
      color: white;
    }

    .header {
      display: flex;
      justify-content: flex-end;
      padding: 16px;
      padding-top: 60px;
    }

    ion-slides {
      height: 60%;
    }

    .slide-content {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 24px;
      height: 100%;
    }

    .icon-container {
      width: 120px;
      height: 120px;
      background: rgba(255, 255, 255, 0.2);
      border-radius: 60px;
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 48px;
    }

    .page-icon {
      font-size: 60px;
      color: white;
    }

    .page-title {
      font-size: 28px;
      font-weight: 700;
      margin-bottom: 24px;
      line-height: 1.2;
    }

    .page-description {
      font-size: 16px;
      opacity: 0.8;
      line-height: 1.5;
      max-width: 320px;
    }

    .navigation {
      padding: 24px;
    }

    .indicators {
      display: flex;
      justify-content: center;
      gap: 8px;
      margin-bottom: 32px;
    }

    .indicator {
      width: 8px;
      height: 8px;
      border-radius: 4px;
      background: rgba(255, 255, 255, 0.4);
      transition: all 0.3s ease;
    }

    .indicator.active {
      width: 24px;
      background: white;
    }

    .next-button {
      --border-radius: 16px;
      --color: var(--current-color);
      margin: 0;
      height: 56px;
      font-weight: 600;
    }
  `]
})
export class OnboardingCarouselScreenComponent implements OnInit {
  @ViewChild('slides', { static: true }) slides!: IonSlides;

  currentIndex = 0;
  currentBackgroundGradient = 'linear-gradient(180deg, #6366F1 0%, rgba(99, 102, 241, 0.8) 100%)';

  pages: OnboardingPage[] = [
    {
      icon: 'bulb-outline',
      title: 'Discover Your AI Potential',
      description: 'Explore the fascinating world of artificial intelligence and discover how smart you really are.',
      color: '#6366F1'
    },
    {
      icon: 'help-circle-outline',
      title: 'Take Smart Challenges',
      description: 'Engage with carefully crafted questions designed to test your AI knowledge and reasoning skills.',
      color: '#8B5CF6'
    },
    {
      icon: 'trending-up-outline',
      title: 'Track Your Progress',
      description: 'Monitor your improvement over time and compete with friends to see who has the highest AIQ score.',
      color: '#06B6D4'
    }
  ];

  slideOpts = {
    initialSlide: 0,
    speed: 400,
    spaceBetween: 0,
  };

  constructor(private router: Router) {}

  ngOnInit() {}

  get isLastSlide(): boolean {
    return this.currentIndex === this.pages.length - 1;
  }

  async onSlideChange() {
    const index = await this.slides.getActiveIndex();
    this.currentIndex = index;
    this.updateBackground();
  }

  private updateBackground() {
    const currentColor = this.pages[this.currentIndex].color;
    this.currentBackgroundGradient = `linear-gradient(180deg, ${currentColor} 0%, ${currentColor}CC 100%)`;
  }

  async nextSlide() {
    if (this.isLastSlide) {
      this.router.navigate(['/welcome']);
    } else {
      await this.slides.slideNext();
    }
  }

  skip() {
    this.router.navigate(['/welcome']);
  }
}

// snippets/screens/react-native/onboarding_carousel_screen/2/onboarding_carousel_screen.jsx
import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  Dimensions,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import Icon from 'react-native-vector-icons/MaterialIcons';

const { width } = Dimensions.get('window');

const OnboardingCarouselScreen = ({ onComplete, onSkip }) => {
  const [currentIndex, setCurrentIndex] = useState(0);

  const pages = [
    {
      icon: 'psychology',
      title: 'Discover Your AI Potential',
      description: 'Explore the fascinating world of artificial intelligence and discover how smart you really are.',
      colors: ['#6366F1', 'rgba(99, 102, 241, 0.8)'],
    },
    {
      icon: 'quiz',
      title: 'Take Smart Challenges',
      description: 'Engage with carefully crafted questions designed to test your AI knowledge and reasoning skills.',
      colors: ['#8B5CF6', 'rgba(139, 92, 246, 0.8)'],
    },
    {
      icon: 'trending-up',
      title: 'Track Your Progress',
      description: 'Monitor your improvement over time and compete with friends to see who has the highest AIQ score.',
      colors: ['#06B6D4', 'rgba(6, 182, 212, 0.8)'],
    },
  ];

  const currentPage = pages[currentIndex];

  const nextPage = () => {
    if (currentIndex < pages.length - 1) {
      setCurrentIndex(currentIndex + 1);
    } else {
      onComplete?.();
    }
  };

  const onScroll = (event) => {
    const slideSize = event.nativeEvent.layoutMeasurement.width;
    const index = event.nativeEvent.contentOffset.x / slideSize;
    setCurrentIndex(Math.round(index));
  };

  return (
    <LinearGradient colors={currentPage.colors} style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={onSkip} style={styles.skipButton}>
          <Text style={styles.skipText}>Skip</Text>
        </TouchableOpacity>
      </View>

      <ScrollView
        horizontal
        pagingEnabled
        showsHorizontalScrollIndicator={false}
        onScroll={onScroll}
        scrollEventThrottle={16}
        style={styles.scrollView}
      >
        {pages.map((page, index) => (
          <View key={index} style={[styles.page, { width }]}>
            <View style={styles.pageContent}>
              {/* Icon */}
              <View style={styles.iconContainer}>
                <Icon name={page.icon} size={60} color="white" />
              </View>

              {/* Content */}
              <Text style={styles.title}>{page.title}</Text>
              <Text style={styles.description}>{page.description}</Text>
            </View>
          </View>
        ))}
      </ScrollView>

      {/* Navigation */}
      <View style={styles.navigation}>
        {/* Page indicators */}
        <View style={styles.indicators}>
          {pages.map((_, index) => (
            <View
              key={index}
              style={[
                styles.indicator,
                {
                  width: index === currentIndex ? 24 : 8,
                  backgroundColor:
                    index === currentIndex
                      ? 'white'
                      : 'rgba(255, 255, 255, 0.4)',
                },
              ]}
            />
          ))}
        </View>

        {/* Next button */}
        <TouchableOpacity style={styles.nextButton} onPress={nextPage}>
          <Text style={[styles.nextText, { color: currentPage.colors[0] }]}>
            {currentIndex === pages.length - 1 ? 'Get Started' : 'Next'}
          </Text>
          {currentIndex < pages.length - 1 && (
            <Icon
              name="arrow-forward"
              size={20}
              color={currentPage.colors[0]}
              style={styles.nextIcon}
            />
          )}
        </TouchableOpacity>
      </View>
    </LinearGradient>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingTop: 50,
    paddingHorizontal: 16,
    alignItems: 'flex-end',
  },
  skipButton: {
    padding: 8,
  },
  skipText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
  },
  scrollView: {
    flex: 1,
  },
  page: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  pageContent: {
    alignItems: 'center',
  },
  iconContainer: {
    width: 120,
    height: 120,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 48,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 34,
  },
  description: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 16,
  },
  navigation: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  indicators: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 32,
  },
  indicator: {
    height: 8,
    borderRadius: 4,
    marginHorizontal: 4,
  },
  nextButton: {
    backgroundColor: 'white',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextText: {
    fontSize: 16,
    fontWeight: '600',
  },
  nextIcon: {
    marginLeft: 8,
  },
});

export default OnboardingCarouselScreen;
