// snippets/components/vue/input/8/input.vue
<template>
  <div class="input-wrapper" :class="{ 'has-error': error, 'is-disabled': disabled }">
    <label v-if="label" class="input-label" :class="{ 'required': required }">{{ label }}</label>
    <div class="input-container" :class="[`size-${size}`, `variant-${variant}`]">
      <span v-if="icon && iconPosition === 'left'" class="input-icon left">{{ icon }}</span>
      <input :type="type" :value="modelValue" :placeholder="placeholder" :disabled="disabled" :required="required" @input="handleInput" @focus="isFocused = true" @blur="isFocused = false" class="input-field" :style="inputStyles" />
      <button v-if="showClear && modelValue && !disabled" @click="clearInput" class="clear-button" type="button">×</button>
      <span v-else-if="icon && iconPosition === 'right'" class="input-icon right">{{ icon }}</span>
    </div>
    <div v-if="error || helperText || showCounter" class="input-footer">
      <span v-if="error" class="error-message">{{ error }}</span>
      <span v-else-if="helperText" class="helper-text">{{ helperText }}</span>
      <span v-if="showCounter" class="character-counter">{{ characterCount }}/{{ maxLength }}</span>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed, ref, PropType } from 'vue';

interface InputTheme { primary: string; background: string; border: string; text: string; error: string; success: string; }

export default defineComponent({
  name: 'Input',
  props: {
    modelValue: { type: [String, Number], default: '' }, type: { type: String, default: 'text' }, label: { type: String, default: '' }, placeholder: { type: String, default: '' }, error: { type: String, default: '' }, helperText: { type: String, default: '' }, disabled: { type: Boolean, default: false }, required: { type: Boolean, default: false }, icon: { type: String, default: '' }, iconPosition: { type: String as PropType<'left' | 'right'>, default: 'left' }, variant: { type: String as PropType<'default' | 'filled' | 'outlined' | 'underlined' | 'floating'>, default: 'outlined' }, size: { type: String as PropType<'sm' | 'md' | 'lg'>, default: 'md' }, theme: { type: Object as PropType<Partial<InputTheme>>, default: () => ({}) }, showClear: { type: Boolean, default: false }, showCounter: { type: Boolean, default: false }, maxLength: { type: Number, default: 100 }
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {
    const isFocused = ref(false);
    const defaultTheme: InputTheme = { primary: '#a855f7', background: '#faf5ff', border: '#d8b4fe', text: '#581c87', error: '#dc2626', success: '#16a34a' };
    const appliedTheme = { ...defaultTheme, ...props.theme };
    const handleInput = (event: Event) => { emit('update:modelValue', (event.target as HTMLInputElement).value); };
    const clearInput = () => { emit('update:modelValue', ''); };
    const characterCount = computed(() => String(props.modelValue).length);
    const inputStyles = computed(() => ({ '--primary-color': appliedTheme.primary, '--bg-color': appliedTheme.background, '--border-color': appliedTheme.border, '--text-color': appliedTheme.text, '--error-color': appliedTheme.error, '--success-color': appliedTheme.success }));
    return { isFocused, handleInput, clearInput, characterCount, inputStyles };
  }
});
</script>

<style scoped>
.input-wrapper { width: 100%; margin-bottom: 1.25rem; }
.input-label { display: block; margin-bottom: 0.5rem; font-size: 0.875rem; font-weight: 600; color: var(--text-color); }
.input-label.required::after { content: ' *'; color: var(--error-color); }
.input-container { position: relative; display: flex; align-items: center; }
.input-field { width: 100%; font-family: inherit; font-size: 1rem; color: var(--text-color); background-color: var(--bg-color); border: 2px solid var(--border-color); border-radius: 0.5rem; transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); outline: none; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1); }
.input-field:focus { border-color: var(--primary-color); box-shadow: 0 0 0 4px rgba(168, 85, 247, 0.15); transform: translateY(-1px); }
.input-field:disabled { opacity: 0.5; cursor: not-allowed; background-color: #f9fafb; }
.has-error .input-field { border-color: var(--error-color); }
.size-sm .input-field { padding: 0.5rem 0.875rem; font-size: 0.875rem; }
.size-md .input-field { padding: 0.75rem 1.125rem; font-size: 1rem; }
.size-lg .input-field { padding: 1rem 1.375rem; font-size: 1.125rem; }
.variant-filled .input-field { background: linear-gradient(135deg, #faf5ff, #d8b4fe); border-color: transparent; }
.variant-outlined .input-field { background-color: transparent; }
.variant-underlined .input-field { border: none; border-bottom: 2px solid var(--border-color); border-radius: 0; background: transparent; }
.input-icon { position: absolute; color: var(--primary-color); pointer-events: none; font-weight: 500; }
.input-icon.left { left: 1rem; }
.input-icon.right { right: 1rem; }
.clear-button { position: absolute; right: 1rem; background: var(--primary-color); color: white; border: none; border-radius: 50%; width: 1.25rem; height: 1.25rem; display: flex; align-items: center; justify-content: center; font-size: 1.125rem; cursor: pointer; transition: all 0.2s; }
.clear-button:hover { transform: scale(1.1); }
.input-footer { display: flex; justify-content: space-between; margin-top: 0.5rem; font-size: 0.75rem; }
.error-message { color: var(--error-color); font-weight: 600; }
.helper-text { color: #581c87; }
.character-counter { color: var(--primary-color); margin-left: auto; font-weight: 500; }
</style>

// snippets/components/svelte/input/18/input.svelte
<script lang="ts">
  import { slide, fade } from 'svelte/transition';

  export interface InputTheme {
    primary: string;
    background: string;
    border: string;
    text: string;
    error: string;
    success: string;
  }

  export let value = '';
  export let type: string = 'text';
  export let label = '';
  export let placeholder = '';
  export let error = '';
  export let helperText = '';
  export let disabled = false;
  export let required = false;
  export let icon = '';
  export let iconPosition: 'left' | 'right' = 'left';
  export let variant: 'default' | 'filled' | 'outlined' | 'underlined' | 'floating' = 'floating';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let theme: Partial<InputTheme> = {};
  export let showCharCount = false;
  export let maxLength: number | undefined = undefined;
  export let showClear = false;

  const defaultTheme: InputTheme = {
    primary: '#ec4899',
    background: '#fdf2f8',
    border: '#fbcfe8',
    text: '#831843',
    error: '#b91c1c',
    success: '#16a34a'
  };

  $: appliedTheme = { ...defaultTheme, ...theme };
  $: hasError = !!error;
  $: showSuccess = !hasError && value.length > 0 && !disabled;

  let focused = false;
  let inputElement: HTMLInputElement;

  function handleClear() {
    value = '';
    inputElement?.focus();
  }

  $: sizeClasses = {
    sm: 'text-sm py-1.5 px-3',
    md: 'text-base py-2.5 px-4',
    lg: 'text-lg py-3.5 px-5'
  }[size];
</script>

<div class="input-wrapper" class:disabled>
  {#if label && variant !== 'floating'}
    <label class="label" class:required>
      {label}
    </label>
  {/if}

  <div class="input-container" class:focused class:error={hasError} class:success={showSuccess}>
    {#if icon && iconPosition === 'left'}
      <span class="icon icon-left">{icon}</span>
    {/if}

    <div class="input-inner">
      {#if variant === 'floating'}
        <label class="floating-label" class:floating={focused || value} class:required>
          {label}
        </label>
      {/if}

      <input
        bind:this={inputElement}
        bind:value
        {type}
        {placeholder}
        {disabled}
        {required}
        maxlength={maxLength}
        class="input {sizeClasses}"
        class:with-icon-left={icon && iconPosition === 'left'}
        class:with-icon-right={icon && iconPosition === 'right' || showClear}
        on:focus={() => focused = true}
        on:blur={() => focused = false}
        on:input
        on:change
        on:keydown
        on:keyup
      />
    </div>

    {#if showClear && value && !disabled}
      <button type="button" class="clear-btn" on:click={handleClear} transition:fade={{ duration: 150 }}>
        ×
      </button>
    {/if}

    {#if icon && iconPosition === 'right' && !showClear}
      <span class="icon icon-right">{icon}</span>
    {/if}
  </div>

  {#if error}
    <div class="message error-message" transition:slide={{ duration: 200 }}>
      {error}
    </div>
  {:else if helperText}
    <div class="message helper-message">
      {helperText}
    </div>
  {/if}

  {#if showCharCount && maxLength}
    <div class="char-count">
      {value.length}/{maxLength}
    </div>
  {/if}
</div>

<style>
  .input-wrapper {
    width: 100%;
    font-family: system-ui, -apple-system, sans-serif;
  }

  .label {
    display: block;
    margin-bottom: 0.5rem;
    font-weight: 600;
    color: v-bind('appliedTheme.primary');
    font-size: 0.875rem;
  }

  .label.required::after {
    content: ' *';
    color: v-bind('appliedTheme.error');
  }

  .input-container {
    position: relative;
    display: flex;
    align-items: center;
    background: v-bind('appliedTheme.background');
    border: 2px solid v-bind('appliedTheme.border');
    border-radius: 0.5rem;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  }

  .input-container:hover:not(.disabled) {
    border-color: v-bind('appliedTheme.primary');
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  }

  .input-container.focused {
    border-color: v-bind('appliedTheme.primary');
    box-shadow: 0 0 0 3px rgba(0, 0, 0, 0.1);
  }

  .input-container.error {
    border-color: v-bind('appliedTheme.error');
  }

  .input-container.success {
    border-color: v-bind('appliedTheme.success');
  }

  .input-inner {
    flex: 1;
    position: relative;
  }

  .input {
    width: 100%;
    border: none;
    outline: none;
    background: transparent;
    color: v-bind('appliedTheme.text');
    font-family: inherit;
    font-weight: 500;
  }

  .input.with-icon-left {
    padding-left: 2.5rem;
  }

  .input.with-icon-right {
    padding-right: 2.5rem;
  }

  .icon {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    color: v-bind('appliedTheme.primary');
    opacity: 0.6;
    pointer-events: none;
  }

  .icon-left {
    left: 1rem;
  }

  .icon-right {
    right: 1rem;
  }

  .clear-btn {
    position: absolute;
    right: 0.75rem;
    top: 50%;
    transform: translateY(-50%);
    background: v-bind('appliedTheme.border');
    border: none;
    border-radius: 50%;
    width: 1.5rem;
    height: 1.5rem;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    font-size: 1.25rem;
    line-height: 1;
    color: v-bind('appliedTheme.text');
    transition: all 0.2s;
  }

  .clear-btn:hover {
    background: v-bind('appliedTheme.primary');
    color: white;
  }

  .floating-label {
    position: absolute;
    left: 1rem;
    top: 50%;
    transform: translateY(-50%);
    color: v-bind('appliedTheme.text');
    opacity: 0.6;
    pointer-events: none;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    background: v-bind('appliedTheme.background');
    padding: 0 0.25rem;
  }

  .floating-label.floating {
    top: 0;
    font-size: 0.75rem;
    opacity: 1;
    color: v-bind('appliedTheme.primary');
  }

  .floating-label.required::after {
    content: ' *';
    color: v-bind('appliedTheme.error');
  }

  .message {
    margin-top: 0.5rem;
    font-size: 0.875rem;
  }

  .error-message {
    color: v-bind('appliedTheme.error');
  }

  .helper-message {
    color: v-bind('appliedTheme.text');
    opacity: 0.7;
  }

  .char-count {
    margin-top: 0.25rem;
    font-size: 0.75rem;
    text-align: right;
    color: v-bind('appliedTheme.primary');
    opacity: 0.6;
  }

  .disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .disabled .input-container {
    background: #f3f4f6;
  }

  .disabled input {
    cursor: not-allowed;
  }
</style>
