// snippets/components/react/accordion/4/accordion.tsx
import React, { useState } from 'react';

interface AccordionItem {
  id: string;
  title: string;
  content: string;
  icon?: string;
}

export interface ComponentProps {
  items?: AccordionItem[];
  theme?: { primary?: string; background?: string; text?: string };
  className?: string;
  allowMultiple?: boolean;
}

export const Component: React.FC<ComponentProps> = ({
  items = [
    { id: '1', title: 'Section 1', content: 'Content 1', icon: '📄' },
    { id: '2', title: 'Section 2', content: 'Content 2', icon: '📋' },
    { id: '3', title: 'Section 3', content: 'Content 3', icon: '📝' }
  ],
  theme = {},
  className = '',
  allowMultiple = false
}) => {
  const [activeIds, setActiveIds] = useState<Set<string>>(new Set());
  const primary = theme.primary || '#8b5cf6';
  const background = theme.background || '#faf5ff';

  const toggleItem = (id: string) => {
    const newIds = new Set(activeIds);
    if (newIds.has(id)) {
      newIds.delete(id);
    } else {
      if (!allowMultiple) {
        newIds.clear();
      }
      newIds.add(id);
    }
    setActiveIds(newIds);
  };

  return (
    <div className={className} style={{ width: '100%', maxWidth: '700px' }}>
      {items.map(item => {
        const isActive = activeIds.has(item.id);
        return (
          <div
            key={item.id}
            style={{
              marginBottom: '12px',
              borderRadius: '6px',
              overflow: 'hidden',
              boxShadow: isActive ? '0 8px 24px rgba(139,92,246,0.2)' : '0 2px 8px rgba(0,0,0,0.08)',
              transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)'
            }}
          >
            <button
              onClick={() => toggleItem(item.id)}
              style={{
                width: '100%',
                padding: '8px 12px',
                backgroundColor: isActive ? primary : '#fff',
                color: isActive ? '#fff' : '#1f2937',
                border: 'none',
                cursor: 'pointer',
                textAlign: 'left',
                fontWeight: '600',
                fontSize: '16px',
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
                transition: 'all 0.3s'
              }}
            >
              <span style={{ fontSize: '24px' }}> {item.icon}</span>
              <span style={{ flex: 1 }}> {item.title}</span>
              <span style={{
                transform: isActive ? 'rotate(180deg)' : 'rotate(0deg)',
                transition: 'transform 0.3s'
              }}>▼</span>
            </button>
            <div style={{
              maxHeight: isActive ? '1000px' : '0',
              overflow: 'hidden',
              transition: 'max-height 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
              backgroundColor: background
            }}>
              <div style={{
                padding: isActive ? '20px 24px' : '0 24px',
                color: '#4b5563',
                lineHeight: '1.6',
                transition: 'padding 0.3s'
              }}>
                {item.content}
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
};

// snippets/components/angular/accordion/1/accordion.component.ts
// Modern Smooth Accordion with Icons
import { Component, Input } from '@angular/core';
@Component({
  selector: 'app-accordion',
  template: `
  <div class="modern-accordion">
  <div class="accordion-item" *ngFor="let item of items; let i = index">
  <div class="accordion-header" (click)="toggle(i)" [class.active]="activeIndex === i">
  <span class="title">{{ item.title }}</span>
  <span class="icon" [class.rotated]="activeIndex === i">▼</span>
  </div>
  <div class="accordion-content" [class.open]="activeIndex === i">
  <div class="content-inner">{{ item.content }}</div>
  </div>
  </div>
  </div>
  `,
  styles: [`
  .modern-accordion { border-radius: 12px; overflow: hidden; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); }
  .accordion-item { border-bottom: 1px solid #e5e7eb; }
  .accordion-item:last-child { border-bottom: none; }
  .accordion-header { padding: 18px 24px; background: white; cursor: pointer; display: flex; justify-content: space-between; align-items: center; transition: all 0.3s; }
  .accordion-header:hover { background: #f9fafb; }
  .accordion-header.active { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; }
  .title { font-weight: 600; font-size: 15px; }
  .icon { transition: transform 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55); }
  .icon.rotated { transform: rotate(180deg); }
  .accordion-content { max-height: 0; overflow: hidden; transition: max-height 0.4s cubic-bezier(0.68, -0.55, 0.265, 1.55); }
  .accordion-content.open { max-height: 500px; }
  .content-inner { padding: 20px 24px; background: #f9fafb; }
  `]
})
export class AccordionComponent {
  @Input() items = [
  { title: 'Section 1', content: 'Content 1' },
  { title: 'Section 2', content: 'Content 2' },
  { title: 'Section 3', content: 'Content 3' }
  ];
  activeIndex: number | null = null;
  toggle(index: number): void {
  this.activeIndex = this.activeIndex === index ? null : index;
  }
}
