// snippets/screens/angular-ionic/error_screen/1/error_screen.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Location } from '@angular/common';

@Component({
  selector: 'app-error-screen',
  template: `
    <ion-content class="error-container">
      <div class="content-wrapper">
        <!-- Error Icon -->
        <div class="icon-container">
          <div class="error-circle">
            <ion-icon name="alert-circle-outline" class="error-icon"></ion-icon>
          </div>
        </div>

        <!-- Content -->
        <div class="content">
          <h1 class="title">{{ title || 'Oops! Something went wrong' }}</h1>
          <p class="message">
            {{ message || "We encountered an unexpected error. Don't worry, it happens to the best of us! Please try again." }}
          </p>
        </div>

        <!-- Error Illustration -->
        <div class="illustration">
          <div class="robot">🤖</div>
        </div>

        <!-- Action Buttons -->
        <div class="buttons-container">
          <ion-button
            expand="block"
            fill="solid"
            color="primary"
            class="retry-button"
            (click)="retry()"
          >
            <ion-icon name="refresh" slot="start"></ion-icon>
            {{ buttonText || 'Try Again' }}
          </ion-button>

          <ion-button
            expand="block"
            fill="outline"
            color="medium"
            class="back-button"
            (click)="goBack()"
          >
            <ion-icon name="arrow-back" slot="start"></ion-icon>
            Go Back
          </ion-button>
        </div>

        <p class="help-text">
          If the problem persists, please contact our support team
        </p>
      </div>
    </ion-content>
  `,
  styles: [`
    .error-container {
      --background: #ffffff;
    }

    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 24px;
      text-align: center;
    }

    .icon-container {
      margin-bottom: 40px;
    }

    .error-circle {
      width: 120px;
      height: 120px;
      background: rgba(239, 68, 68, 0.1);
      border: 2px solid rgba(239, 68, 68, 0.2);
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .error-icon {
      font-size: 60px;
      color: #EF4444;
    }

    .content {
      margin-bottom: 40px;
    }

    .title {
      font-size: 28px;
      font-weight: 700;
      color: #1F2937;
      margin-bottom: 16px;
      line-height: 1.2;
    }

    .message {
      font-size: 16px;
      color: #6B7280;
      line-height: 1.5;
      max-width: 320px;
    }

    .illustration {
      margin-bottom: 40px;
    }

    .robot {
      font-size: 60px;
    }

    .buttons-container {
      width: 100%;
      max-width: 320px;
      display: flex;
      flex-direction: column;
      gap: 12px;
      margin-bottom: 20px;
    }

    .retry-button, .back-button {
      --border-radius: 16px;
      height: 56px;
      margin: 0;
      font-weight: 600;
    }

    .retry-button {
      --background: #6366F1;
    }

    .back-button {
      --border-color: #E5E7EB;
      --color: #6B7280;
    }

    .help-text {
      font-size: 12px;
      color: rgba(107, 114, 128, 0.8);
    }
  `]
})
export class ErrorScreenComponent implements OnInit {
  @Input() title?: string;
  @Input() message?: string;
  @Input() buttonText?: string;

  constructor(private location: Location) {}

  ngOnInit() {}

  retry() {
    // Implement retry logic
    window.location.reload();
  }

  goBack() {
    this.location.back();
  }
}

// snippets/screens/react/error_screen/2/error_screen.jsx
import React from 'react';
import { AlertTriangle, RefreshCw, ArrowLeft } from 'lucide-react';

const ErrorScreen = ({
  title = "Oops! Something went wrong",
  message = "We encountered an unexpected error. Don't worry, it happens to the best of us! Please try again.",
  buttonText = "Try Again",
  onRetry,
  onGoBack
}) => {
  return (
    <div className="min-h-screen bg-white flex items-center justify-center p-6">
      <div className="text-center w-full max-w-md">
        {/* Error Icon */}
        <div className="mb-10">
          <div className="w-30 h-30 border-4 border-red-100 bg-red-50 rounded-full mx-auto flex items-center justify-center">
            <AlertTriangle size={60} className="text-red-500" />
          </div>
        </div>

        {/* Content */}
        <h1 className="text-3xl font-bold text-gray-900 mb-4 leading-tight">
          {title}
        </h1>

        <p className="text-gray-600 text-lg mb-10 leading-relaxed">
          {message}
        </p>

        {/* Error Illustration */}
        <div className="mb-10 py-8">
          <div className="w-24 h-24 mx-auto bg-gray-100 rounded-2xl flex items-center justify-center">
            <div className="text-gray-400 text-4xl">🤖</div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="space-y-3">
          <button
            onClick={onRetry}
            className="w-full bg-indigo-500 text-white py-4 px-6 rounded-2xl font-semibold hover:bg-indigo-600 transition-colors flex items-center justify-center space-x-2"
          >
            <RefreshCw size={20} />
            <span>{buttonText}</span>
          </button>

          <button
            onClick={onGoBack}
            className="w-full border-2 border-gray-200 text-gray-600 py-4 px-6 rounded-2xl font-medium hover:bg-gray-50 transition-colors flex items-center justify-center space-x-2"
          >
            <ArrowLeft size={20} />
            <span>Go Back</span>
          </button>
        </div>

        <p className="text-sm text-gray-400 mt-6">
          If the problem persists, please contact our support team
        </p>
      </div>
    </div>
  );
};

export default ErrorScreen;
