// snippets/components/vue/navbar/5/navbar.vue
<template>
  <nav
    :class="[
      'navbar',
      `navbar-${variant}`,
      { 'navbar-sticky': sticky, 'navbar-transparent': transparent }
    ]"
    :style="navbarStyles"
  >
    <div class="navbar-container">
      <!-- Logo/Brand Section -->
      <div class="navbar-brand">
        <img v-if="logo" :src="logo" alt="Logo" class="navbar-logo" />
        <span class="navbar-brand-text">{{ brandName }}</span>
      </div>

      <!-- Desktop Menu -->
      <div class="navbar-menu" :class="{ 'navbar-menu-open': mobileMenuOpen }">
        <div
          v-for="item in items"
          :key="item.id"
          class="navbar-item-wrapper"
          @mouseenter="handleMouseEnter(item.id)"
          @mouseleave="handleMouseLeave"
        >
          <a
            :href="item.route"
            :class="['navbar-item', { active: activeItem === item.id }]"
            :style="getItemStyles(item.id)"
            @click.prevent="handleItemClick(item)"
          >
            <span v-if="item.icon" class="navbar-item-icon">{{ item.icon }}</span>
            <span class="navbar-item-label">{{ item.label }}</span>
            <span v-if="item.dropdown" class="navbar-item-arrow">▼</span>
          </a>

          <!-- Dropdown Menu -->
          <div
            v-if="item.dropdown && item.dropdown.length"
            :class="['navbar-dropdown', { active: hoveredItem === item.id || activeDropdown === item.id }]"
            :style="dropdownStyles"
          >
            <a
              v-for="child in item.dropdown"
              :key="child.id"
              :href="child.route"
              class="navbar-dropdown-item"
              :style="dropdownItemStyles"
              @click.prevent="handleItemClick(child)"
            >
              <span v-if="child.icon" class="navbar-dropdown-icon">{{ child.icon }}</span>
              <span>{{ child.label }}</span>
            </a>
          </div>
        </div>
      </div>

      <!-- Right Section -->
      <div class="navbar-actions">
        <!-- Search Bar Slot -->
        <div v-if="$slots.search" class="navbar-search">
          <slot name="search"></slot>
        </div>

        <!-- Notifications -->
        <div v-if="showNotifications" class="navbar-notification">
          <button class="navbar-notification-btn" :style="actionButtonStyles">
            <span class="navbar-notification-icon">🔔</span>
            <span v-if="notificationCount > 0" class="navbar-notification-badge" :style="badgeStyles">
              {{ notificationCount }}
            </span>
          </button>
        </div>

        <!-- User Profile Slot -->
        <div v-if="$slots.profile" class="navbar-profile">
          <slot name="profile"></slot>
        </div>

        <!-- Mobile Menu Toggle -->
        <button
          class="navbar-mobile-toggle"
          :style="actionButtonStyles"
          @click="toggleMobileMenu"
        >
          <span class="navbar-hamburger">{{ mobileMenuOpen ? '✕' : '☰' }}</span>
        </button>
      </div>
    </div>

    <!-- Mobile Menu Overlay -->
    <transition name="mobile-menu-blur">
      <div v-if="mobileMenuOpen" class="navbar-mobile-overlay" :style="mobileOverlayStyles">
        <div class="navbar-mobile-menu">
          <div
            v-for="item in items"
            :key="item.id"
            class="navbar-mobile-item-wrapper"
          >
            <a
              :href="item.route"
              :class="['navbar-mobile-item', { active: activeItem === item.id }]"
              :style="getMobileItemStyles(item.id)"
              @click="handleMobileItemClick(item)"
            >
              <span v-if="item.icon" class="navbar-mobile-icon">{{ item.icon }}</span>
              <span>{{ item.label }}</span>
              <span v-if="item.dropdown" class="navbar-mobile-arrow">▼</span>
            </a>

            <!-- Mobile Dropdown -->
            <div
              v-if="item.dropdown && item.dropdown.length && activeDropdown === item.id"
              class="navbar-mobile-dropdown"
            >
              <a
                v-for="child in item.dropdown"
                :key="child.id"
                :href="child.route"
                class="navbar-mobile-dropdown-item"
                @click="handleMobileItemClick(child)"
              >
                <span v-if="child.icon">{{ child.icon }}</span>
                <span>{{ child.label }}</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </transition>
  </nav>
</template>

<script setup lang="ts">
import { ref, computed, defineProps, withDefaults } from 'vue'

interface NavbarTheme {
  primary: string
  background: string
  text: string
  activeColor: string
  hoverColor: string
}

interface NavItem {
  id: string
  label: string
  icon?: string
  route: string
  dropdown?: NavItem[]
}

interface Props {
  items: NavItem[]
  logo?: string
  brandName?: string
  variant?: 'solid' | 'transparent' | 'blur' | 'gradient' | 'minimal'
  sticky?: boolean
  transparent?: boolean
  theme?: Partial<NavbarTheme>
  showNotifications?: boolean
  notificationCount?: number
}

const props = withDefaults(defineProps<Props>(), {
  items: () => [],
  brandName: 'Brand',
  variant: 'blur',
  sticky: false,
  transparent: false,
  theme: () => ({}),
  showNotifications: true,
  notificationCount: 0
})

// State
const mobileMenuOpen = ref(false)
const activeItem = ref<string | null>(null)
const hoveredItem = ref<string | null>(null)
const activeDropdown = ref<string | null>(null)

// Default theme for variant 5 - Blur Modern
const defaultTheme: NavbarTheme = {
  primary: '#8b5cf6',
  background: 'rgba(17, 24, 39, 0.75)',
  text: '#f3f4f6',
  activeColor: '#a78bfa',
  hoverColor: 'rgba(139, 92, 246, 0.2)'
}

const mergedTheme = computed<NavbarTheme>(() => ({
  ...defaultTheme,
  ...props.theme
}))

// Computed Styles
const navbarStyles = computed(() => ({
  backgroundColor: props.transparent ? 'transparent' : mergedTheme.value.background,
  color: mergedTheme.value.text,
  backdropFilter: 'blur(16px) saturate(200%)',
  WebkitBackdropFilter: 'blur(16px) saturate(200%)',
  borderBottom: `1px solid rgba(139, 92, 246, 0.3)`,
  boxShadow: '0 4px 30px rgba(0, 0, 0, 0.1)'
}))

const dropdownStyles = computed(() => ({
  backgroundColor: mergedTheme.value.background,
  backdropFilter: 'blur(16px) saturate(200%)',
  WebkitBackdropFilter: 'blur(16px) saturate(200%)',
  border: `1px solid rgba(139, 92, 246, 0.3)`,
  boxShadow: '0 8px 32px rgba(139, 92, 246, 0.15)'
}))

const dropdownItemStyles = computed(() => ({
  color: mergedTheme.value.text
}))

const actionButtonStyles = computed(() => ({
  color: mergedTheme.value.text,
  backgroundColor: 'rgba(139, 92, 246, 0.15)',
  border: '1px solid rgba(139, 92, 246, 0.3)',
  backdropFilter: 'blur(8px)',
  WebkitBackdropFilter: 'blur(8px)'
}))

const badgeStyles = computed(() => ({
  backgroundColor: mergedTheme.value.activeColor,
  color: '#111827',
  fontWeight: '700',
  boxShadow: `0 0 16px ${mergedTheme.value.activeColor}`
}))

const mobileOverlayStyles = computed(() => ({
  backgroundColor: mergedTheme.value.background,
  backdropFilter: 'blur(16px) saturate(200%)',
  WebkitBackdropFilter: 'blur(16px) saturate(200%)'
}))

// Methods
const getItemStyles = (itemId: string) => {
  const isActive = activeItem.value === itemId
  const isHovered = hoveredItem.value === itemId

  return {
    color: isActive ? mergedTheme.value.activeColor : mergedTheme.value.text,
    backgroundColor: isHovered || isActive ? mergedTheme.value.hoverColor : 'transparent',
    borderRadius: '10px',
    boxShadow: isActive ? `0 0 20px rgba(139, 92, 246, 0.3)` : 'none',
    backdropFilter: isHovered || isActive ? 'blur(8px)' : 'none'
  }
}

const getMobileItemStyles = (itemId: string) => ({
  color: activeItem.value === itemId ? mergedTheme.value.activeColor : mergedTheme.value.text,
  backgroundColor: activeItem.value === itemId ? mergedTheme.value.hoverColor : 'transparent',
  backdropFilter: activeItem.value === itemId ? 'blur(8px)' : 'none'
})

const handleMouseEnter = (itemId: string) => {
  hoveredItem.value = itemId
}

const handleMouseLeave = () => {
  hoveredItem.value = null
}

const handleItemClick = (item: NavItem) => {
  if (item.dropdown && item.dropdown.length) {
    activeDropdown.value = activeDropdown.value === item.id ? null : item.id
  } else {
    activeItem.value = item.id
    activeDropdown.value = null
  }
}

const handleMobileItemClick = (item: NavItem) => {
  if (item.dropdown && item.dropdown.length) {
    activeDropdown.value = activeDropdown.value === item.id ? null : item.id
  } else {
    activeItem.value = item.id
    mobileMenuOpen.value = false
    activeDropdown.value = null
  }
}

const toggleMobileMenu = () => {
  mobileMenuOpen.value = !mobileMenuOpen.value
}
</script>

<style scoped>
.navbar {
  position: relative;
  width: 100%;
  padding: 0;
  transition: all 0.35s cubic-bezier(0.4, 0, 0.2, 1);
}

.navbar-sticky {
  position: sticky;
  top: 0;
  z-index: 1000;
}

.navbar-container {
  max-width: 1400px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 2rem;
}

.navbar-brand {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-size: 1.5rem;
  font-weight: 700;
  cursor: pointer;
  transition: all 0.3s ease;
  text-shadow: 0 2px 10px rgba(139, 92, 246, 0.5);
  letter-spacing: 0.5px;
}

.navbar-brand:hover {
  transform: scale(1.05);
  text-shadow: 0 4px 20px rgba(139, 92, 246, 0.8);
}

.navbar-logo {
  height: 40px;
  width: auto;
  filter: drop-shadow(0 2px 8px rgba(139, 92, 246, 0.4));
}

.navbar-menu {
  display: none;
  gap: 0.625rem;
  flex: 1;
  justify-content: center;
}

@media (min-width: 768px) {
  .navbar-menu {
    display: flex;
  }
}

.navbar-item-wrapper {
  position: relative;
}

.navbar-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.875rem 1.5rem;
  text-decoration: none;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  font-weight: 600;
  white-space: nowrap;
  font-size: 0.925rem;
  letter-spacing: 0.3px;
}

.navbar-item:hover {
  transform: translateY(-2px);
}

.navbar-item.active {
  font-weight: 700;
}

.navbar-item-icon {
  font-size: 1.125rem;
  transition: transform 0.3s ease;
}

.navbar-item:hover .navbar-item-icon {
  transform: scale(1.15) rotate(5deg);
}

.navbar-item-arrow {
  font-size: 0.7rem;
  margin-left: 0.25rem;
  transition: transform 0.3s ease;
}

.navbar-item:hover .navbar-item-arrow {
  transform: translateY(2px);
}

.navbar-dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  min-width: 220px;
  margin-top: 0.625rem;
  padding: 0.75rem;
  border-radius: 14px;
  opacity: 0;
  visibility: hidden;
  transform: translateY(-12px) scale(0.95);
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  z-index: 100;
}

.navbar-dropdown.active {
  opacity: 1;
  visibility: visible;
  transform: translateY(0) scale(1);
}

.navbar-dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.875rem 1.125rem;
  text-decoration: none;
  border-radius: 10px;
  transition: all 0.25s ease;
  font-weight: 500;
  letter-spacing: 0.25px;
}

.navbar-dropdown-item:hover {
  background-color: rgba(139, 92, 246, 0.2);
  transform: translateX(5px);
  box-shadow: 0 4px 12px rgba(139, 92, 246, 0.2);
  backdrop-filter: blur(8px);
}

.navbar-dropdown-icon {
  font-size: 1.05rem;
}

.navbar-actions {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.navbar-search {
  display: none;
}

@media (min-width: 768px) {
  .navbar-search {
    display: block;
  }
}

.navbar-notification {
  position: relative;
}

.navbar-notification-btn {
  position: relative;
  border-radius: 12px;
  width: 44px;
  height: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.3s ease;
}

.navbar-notification-btn:hover {
  transform: scale(1.12);
  background-color: rgba(139, 92, 246, 0.25);
  box-shadow: 0 6px 20px rgba(139, 92, 246, 0.3);
}

.navbar-notification-icon {
  font-size: 1.25rem;
}

.navbar-notification-badge {
  position: absolute;
  top: -3px;
  right: -3px;
  min-width: 20px;
  height: 20px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.7rem;
  padding: 0 6px;
  animation: glow 2s ease-in-out infinite;
}

@keyframes glow {
  0%, 100% {
    box-shadow: 0 0 16px currentColor;
  }
  50% {
    box-shadow: 0 0 24px currentColor;
  }
}

.navbar-mobile-toggle {
  display: flex;
  border-radius: 12px;
  padding: 0.625rem 0.875rem;
  cursor: pointer;
  transition: all 0.3s ease;
}

@media (min-width: 768px) {
  .navbar-mobile-toggle {
    display: none;
  }
}

.navbar-mobile-toggle:hover {
  transform: scale(1.1);
  box-shadow: 0 4px 16px rgba(139, 92, 246, 0.3);
}

.navbar-hamburger {
  font-size: 1.5rem;
}

.navbar-mobile-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100vh;
  z-index: 999;
  overflow-y: auto;
  padding-top: 85px;
}

@media (min-width: 768px) {
  .navbar-mobile-overlay {
    display: none;
  }
}

.navbar-mobile-menu {
  padding: 2rem 1.5rem;
}

.navbar-mobile-item-wrapper {
  margin-bottom: 0.625rem;
}

.navbar-mobile-item {
  display: flex;
  align-items: center;
  gap: 0.875rem;
  padding: 1.125rem 1.75rem;
  text-decoration: none;
  border-radius: 14px;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  font-size: 1.1rem;
  font-weight: 600;
  letter-spacing: 0.3px;
  border: 1px solid rgba(139, 92, 246, 0.2);
}

.navbar-mobile-icon {
  font-size: 1.35rem;
}

.navbar-mobile-arrow {
  margin-left: auto;
  font-size: 0.85rem;
  transition: transform 0.3s ease;
}

.navbar-mobile-dropdown {
  margin-left: 2.25rem;
  margin-top: 0.625rem;
  animation: dropdownSlide 0.3s ease;
}

@keyframes dropdownSlide {
  from {
    opacity: 0;
    transform: translateY(-8px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.navbar-mobile-dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.875rem 1.5rem;
  text-decoration: none;
  border-radius: 10px;
  transition: all 0.25s ease;
  opacity: 0.9;
  font-weight: 500;
  margin-bottom: 0.375rem;
  border: 1px solid rgba(139, 92, 246, 0.15);
  backdrop-filter: blur(8px);
}

.navbar-mobile-dropdown-item:hover {
  background-color: rgba(139, 92, 246, 0.2);
  opacity: 1;
  transform: translateX(6px);
  box-shadow: 0 4px 12px rgba(139, 92, 246, 0.2);
}

.mobile-menu-blur-enter-active,
.mobile-menu-blur-leave-active {
  transition: all 0.35s cubic-bezier(0.4, 0, 0.2, 1);
}

.mobile-menu-blur-enter-from {
  opacity: 0;
  backdrop-filter: blur(0px);
  transform: translateX(100%);
}

.mobile-menu-blur-leave-to {
  opacity: 0;
  backdrop-filter: blur(0px);
  transform: translateX(100%);
}
</style>

// snippets/components/angular/navbar/1/navbar.component.ts
import { Component, Input, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';

interface NavbarTheme {
  primaryColor: string;
  secondaryColor: string;
  backgroundColor: string;
  textColor: string;
  borderColor: string;
  accentColor: string;
}

interface MenuItem {
  label: string;
  route: string;
  icon?: string;
  children?: MenuItem[];
}

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule],
  template: `
    <nav [ngStyle]="navbarStyles" [class.scrolled]="isScrolled" role="navigation">
      <div class="navbar-container" [ngStyle]="containerStyles">
        <!-- Logo/Brand -->
        <div class="navbar-brand" [ngStyle]="brandStyles">
          <img *ngIf="logoUrl" [src]="logoUrl" alt="Logo" class="logo" [ngStyle]="logoStyles">
          <span class="brand-text" [ngStyle]="brandTextStyles">{{ brandName }}</span>
        </div>

        <!-- Desktop Menu -->
        <div class="navbar-menu" [ngStyle]="menuStyles" [class.active]="isMobileMenuOpen">
          <a *ngFor="let item of menuItems; let i = index"
             [href]="item.route"
             class="menu-item"
             [ngStyle]="getMenuItemStyles(item)"
             [class.active]="item.route === activeRoute"
             [attr.aria-current]="item.route === activeRoute ? 'page' : null"
             (mouseenter)="hoveredIndex = i"
             (mouseleave)="hoveredIndex = null">
            <span *ngIf="item.icon" class="item-icon">{{ item.icon }}</span>
            {{ item.label }}
            <span *ngIf="item.children" class="dropdown-arrow" [attr.aria-expanded]="expandedDropdown === i">▼</span>
          </a>
        </div>

        <!-- Search Bar -->
        <div *ngIf="showSearch" class="navbar-search" [ngStyle]="searchStyles">
          <input type="search"
                 placeholder="Search..."
                 [ngStyle]="searchInputStyles"
                 aria-label="Search">
          <span class="search-icon">🔍</span>
        </div>

        <!-- User Section -->
        <div class="navbar-actions" [ngStyle]="actionsStyles">
          <button *ngIf="showNotifications"
                  class="notification-btn"
                  [ngStyle]="notificationBtnStyles"
                  aria-label="Notifications">
            🔔
            <span *ngIf="notificationCount > 0" class="badge" [ngStyle]="badgeStyles">
              {{ notificationCount }}
            </span>
          </button>

          <div *ngIf="showUserProfile" class="user-profile" [ngStyle]="profileStyles">
            <img [src]="userAvatar" alt="User" class="avatar" [ngStyle]="avatarStyles">
            <span class="user-name">{{ userName }}</span>
          </div>
        </div>

        <!-- Mobile Menu Toggle -->
        <button class="mobile-toggle"
                [ngStyle]="mobileToggleStyles"
                (click)="toggleMobileMenu()"
                [attr.aria-expanded]="isMobileMenuOpen"
                aria-label="Toggle menu">
          <span class="hamburger" [ngStyle]="hamburgerStyles"></span>
        </button>
      </div>
    </nav>
  `,
  styles: [`
    nav {
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    }
    nav.scrolled {
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
      backdrop-filter: blur(10px);
    }
    .navbar-container {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 2rem;
    }
    .navbar-brand {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      cursor: pointer;
      transition: transform 0.2s;
    }
    .navbar-brand:hover {
      transform: scale(1.05);
    }
    .logo {
      height: 40px;
      width: auto;
    }
    .navbar-menu {
      display: flex;
      gap: 0.5rem;
      align-items: center;
      flex: 1;
    }
    .menu-item {
      position: relative;
      text-decoration: none;
      padding: 0.75rem 1.25rem;
      border-radius: 0.5rem;
      transition: all 0.3s ease;
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
    .menu-item:hover {
      transform: translateY(-2px);
    }
    .menu-item.active::after {
      content: '';
      position: absolute;
      bottom: 0;
      left: 50%;
      transform: translateX(-50%);
      width: 80%;
      height: 3px;
      background: currentColor;
      border-radius: 2px;
    }
    .navbar-search {
      position: relative;
      display: flex;
      align-items: center;
    }
    .search-icon {
      position: absolute;
      left: 1rem;
      pointer-events: none;
    }
    .navbar-actions {
      display: flex;
      align-items: center;
      gap: 1rem;
    }
    .notification-btn {
      position: relative;
      background: none;
      border: none;
      cursor: pointer;
      padding: 0.5rem;
      font-size: 1.5rem;
      transition: transform 0.2s;
    }
    .notification-btn:hover {
      transform: scale(1.1);
    }
    .badge {
      position: absolute;
      top: 0;
      right: 0;
      font-size: 0.75rem;
      min-width: 20px;
      height: 20px;
      display: flex;
      align-items: center;
      justify-content: center;
      border-radius: 10px;
      animation: pulse 2s infinite;
    }
    @keyframes pulse {
      0%, 100% { transform: scale(1); }
      50% { transform: scale(1.1); }
    }
    .user-profile {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      cursor: pointer;
      padding: 0.5rem 1rem;
      border-radius: 2rem;
      transition: all 0.3s;
    }
    .avatar {
      width: 36px;
      height: 36px;
      border-radius: 50%;
      object-fit: cover;
    }
    .mobile-toggle {
      display: none;
      background: none;
      border: none;
      cursor: pointer;
      padding: 0.5rem;
    }
    @media (max-width: 768px) {
      .navbar-menu {
        position: fixed;
        top: 70px;
        left: 0;
        right: 0;
        flex-direction: column;
        padding: 1rem;
        transform: translateY(-100%);
        opacity: 0;
        transition: all 0.3s;
      }
      .navbar-menu.active {
        transform: translateY(0);
        opacity: 1;
      }
      .mobile-toggle {
        display: block;
      }
      .navbar-search {
        display: none;
      }
    }
  `]
})
export class NavbarComponent {
  @Input() theme: Partial<NavbarTheme> = {};
  @Input() variant: 'solid' | 'transparent' | 'blur' | 'gradient' = 'solid';
  @Input() position: 'static' | 'sticky' | 'fixed' = 'sticky';
  @Input() brandName = 'Brand';
  @Input() logoUrl = '';
  @Input() menuItems: MenuItem[] = [
    { label: 'Home', route: '/' },
    { label: 'About', route: '/about' },
    { label: 'Services', route: '/services' },
    { label: 'Contact', route: '/contact' }
  ];
  @Input() activeRoute = '/';
  @Input() showSearch = true;
  @Input() showNotifications = true;
  @Input() showUserProfile = true;
  @Input() notificationCount = 3;
  @Input() userName = 'User';
  @Input() userAvatar = 'https://i.pravatar.cc/150?img=1';

  private defaultTheme: NavbarTheme = {
    primaryColor: '#3b82f6',
    secondaryColor: '#8b5cf6',
    backgroundColor: '#ffffff',
    textColor: '#111827',
    borderColor: '#e5e7eb',
    accentColor: '#f59e0b'
  };

  isMobileMenuOpen = false;
  isScrolled = false;
  expandedDropdown: number | null = null;
  hoveredIndex: number | null = null;

  get appliedTheme(): NavbarTheme {
    return { ...this.defaultTheme, ...this.theme };
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
    this.isScrolled = window.scrollY > 20;
  }

  toggleMobileMenu() {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }

  get navbarStyles() {
    const variantStyles = {
      solid: {
        backgroundColor: this.appliedTheme.backgroundColor,
        borderBottom: `1px solid ${this.appliedTheme.borderColor}`,
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)'
      },
      transparent: {
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        backdropFilter: 'blur(10px)',
        borderBottom: `1px solid rgba(0, 0, 0, 0.1)`
      },
      blur: {
        backgroundColor: 'rgba(255, 255, 255, 0.6)',
        backdropFilter: 'blur(20px) saturate(180%)',
        borderBottom: 'none'
      },
      gradient: {
        background: `linear-gradient(135deg, ${this.appliedTheme.primaryColor}, ${this.appliedTheme.secondaryColor})`,
        borderBottom: 'none',
        color: '#ffffff'
      }
    };

    return {
      position: this.position,
      top: this.position !== 'static' ? '0' : 'auto',
      left: '0',
      right: '0',
      zIndex: '1000',
      ...variantStyles[this.variant]
    };
  }

  get containerStyles() {
    return {
      maxWidth: '1280px',
      margin: '0 auto',
      padding: '1rem 2rem'
    };
  }

  get brandStyles() {
    return {
      fontWeight: '700',
      fontSize: '1.5rem',
      color: this.variant === 'gradient' ? '#ffffff' : this.appliedTheme.primaryColor
    };
  }

  get logoStyles() {
    return {
      filter: this.variant === 'gradient' ? 'brightness(0) invert(1)' : 'none'
    };
  }

  get brandTextStyles() {
    return {
      background: this.variant === 'gradient' ? '#ffffff' : `linear-gradient(135deg, ${this.appliedTheme.primaryColor}, ${this.appliedTheme.secondaryColor})`,
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: this.variant === 'gradient' ? '#ffffff' : 'transparent',
      backgroundClip: 'text'
    };
  }

  get menuStyles() {
    return {
      backgroundColor: this.variant === 'gradient' ? 'rgba(255, 255, 255, 0.1)' : 'transparent'
    };
  }

  getMenuItemStyles(item: MenuItem) {
    const isActive = item.route === this.activeRoute;
    const baseColor = this.variant === 'gradient' ? '#ffffff' : this.appliedTheme.textColor;

    return {
      color: isActive ? this.appliedTheme.primaryColor : baseColor,
      backgroundColor: isActive ? (this.variant === 'gradient' ? 'rgba(255, 255, 255, 0.2)' : `${this.appliedTheme.primaryColor}15`) : 'transparent',
      fontWeight: isActive ? '600' : '500'
    };
  }

  get searchStyles() {
    return {
      flex: '0 0 300px'
    };
  }

  get searchInputStyles() {
    return {
      width: '100%',
      padding: '0.625rem 1rem 0.625rem 3rem',
      border: `1px solid ${this.appliedTheme.borderColor}`,
      borderRadius: '2rem',
      backgroundColor: this.variant === 'gradient' ? 'rgba(255, 255, 255, 0.2)' : this.appliedTheme.backgroundColor,
      color: this.variant === 'gradient' ? '#ffffff' : this.appliedTheme.textColor,
      outline: 'none',
      transition: 'all 0.3s'
    };
  }

  get actionsStyles() {
    return {};
  }

  get notificationBtnStyles() {
    return {
      color: this.variant === 'gradient' ? '#ffffff' : this.appliedTheme.textColor
    };
  }

  get badgeStyles() {
    return {
      backgroundColor: this.appliedTheme.accentColor,
      color: '#ffffff',
      fontWeight: '600'
    };
  }

  get profileStyles() {
    return {
      backgroundColor: this.variant === 'gradient' ? 'rgba(255, 255, 255, 0.2)' : `${this.appliedTheme.primaryColor}10`,
      color: this.variant === 'gradient' ? '#ffffff' : this.appliedTheme.textColor
    };
  }

  get avatarStyles() {
    return {
      border: `2px solid ${this.variant === 'gradient' ? '#ffffff' : this.appliedTheme.primaryColor}`
    };
  }

  get mobileToggleStyles() {
    return {
      color: this.variant === 'gradient' ? '#ffffff' : this.appliedTheme.textColor
    };
  }

  get hamburgerStyles() {
    return {
      display: 'block',
      width: '24px',
      height: '2px',
      backgroundColor: 'currentColor',
      position: 'relative',
      transition: 'all 0.3s'
    };
  }
}
