// snippets/components/vue/input/2/input.vue
<template>
  <div class="input-container">
    <label v-if="label" class="input-label">{{ label }}</label>
    <div class="input-wrapper">
      <input
        :type="type"
        :value="modelValue"
        :placeholder="placeholder"
        :disabled="disabled"
        @input="$emit('update:modelValue', ($event.target as HTMLInputElement).value)"
        class="text-input"
        :class="{ error, focused }"
        @focus="focused = true"
        @blur="focused = false"
      />
    </div>
    <p v-if="error" class="error-text">{{ error }}</p>
  </div>
</template>
<script lang="ts">
import { defineComponent, ref } from 'vue';
export default defineComponent({
  name: 'TextInput',
  props: {
    modelValue: { type: [String, Number], default: '' },
    type: { type: String, default: 'text' },
    label: { type: String, default: '' },
    placeholder: { type: String, default: '' },
    error: { type: String, default: '' },
    disabled: { type: Boolean, default: false }
  },
  emits: ['update:modelValue'],
  setup() {
    const focused = ref(false);
    return { focused };
  }
});
</script>
<style scoped>
.input-container {
  margin: 1rem 0;
}
.input-label {
  display: block;
  margin-bottom: 0.5rem;
  font-size: 0.875rem;
  font-weight: 500;
  color: #374151;
}
.text-input {
  width: 100%;
  padding: 0.5rem 1rem;
  font-size: 1rem;
  border: 2px solid #d1d5db;
  border-radius: 0.25rem;
  outline: none;
  transition: all 0.2s;
  background: white;
}
.text-input:focus {
  border-color: #blue500;
  box-shadow: 0 0 0 3px rgba(var(--blue-rgb), 0.1);
}
.text-input.error {
  border-color: #ef4444;
}
.error-text {
  margin-top: 0.5rem;
  font-size: 0.875rem;
  color: #ef4444;
}
</style>

// snippets/components/svelte/input/2/input.svelte
<script lang="ts">
  export let value: string = '';
  export let placeholder: string = '';
  export let label: string = '';
  export let error: string = '';
  export let disabled: boolean = false;
  
  let focused = false;
</script>

<div class="field">
  {#if label}
    <label class="field-label">{label}</label>
  {/if}
  <input
    type="text"
    bind:value
    {placeholder}
    {disabled}
    on:focus={() => focused = true}
    on:blur={() => focused = false}
    class="field-input"
    class:focused
    class:error
  />
  {#if error}
    <p class="field-error">{error}</p>
  {/if}
</div>

<style>
  .field {
    margin: 1.25rem 0;
  }
  
  .field-label {
    display: block;
    margin-bottom: 0.625rem;
    font-size: 0.875rem;
    font-weight: 600;
    color: #1f2937;
  }
  
  .field-input {
    width: 100%;
    padding: 0.75rem 1.125rem;
    font-size: 1rem;
    border: 2px solid #e5e7eb;
    border-radius: 4px;
    outline: none;
    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
    background: white;
  }
  
  .field-input:hover:not(:disabled) {
    border-color: #cbd5e1;
  }
  
  .field-input.focused {
    border-color: var(--blue-500, #3b82f6);
    box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
  }
  
  .field-input.error {
    border-color: #ef4444;
  }
  
  .field-error {
    margin-top: 0.5rem;
    font-size: 0.875rem;
    color: #dc2626;
    font-weight: 500;
  }
</style>
