// snippets/components/vue/navbar/5/navbar.vue
<template>
  <nav
    :class="[
      'navbar',
      `navbar-${variant}`,
      { 'navbar-sticky': sticky, 'navbar-transparent': transparent }
    ]"
    :style="navbarStyles"
  >
    <div class="navbar-container">
      <!-- Logo/Brand Section -->
      <div class="navbar-brand">
        <img v-if="logo" :src="logo" alt="Logo" class="navbar-logo" />
        <span class="navbar-brand-text">{{ brandName }}</span>
      </div>

      <!-- Desktop Menu -->
      <div class="navbar-menu" :class="{ 'navbar-menu-open': mobileMenuOpen }">
        <div
          v-for="item in items"
          :key="item.id"
          class="navbar-item-wrapper"
          @mouseenter="handleMouseEnter(item.id)"
          @mouseleave="handleMouseLeave"
        >
          <a
            :href="item.route"
            :class="['navbar-item', { active: activeItem === item.id }]"
            :style="getItemStyles(item.id)"
            @click.prevent="handleItemClick(item)"
          >
            <span v-if="item.icon" class="navbar-item-icon">{{ item.icon }}</span>
            <span class="navbar-item-label">{{ item.label }}</span>
            <span v-if="item.dropdown" class="navbar-item-arrow">▼</span>
          </a>

          <!-- Dropdown Menu -->
          <div
            v-if="item.dropdown && item.dropdown.length"
            :class="['navbar-dropdown', { active: hoveredItem === item.id || activeDropdown === item.id }]"
            :style="dropdownStyles"
          >
            <a
              v-for="child in item.dropdown"
              :key="child.id"
              :href="child.route"
              class="navbar-dropdown-item"
              :style="dropdownItemStyles"
              @click.prevent="handleItemClick(child)"
            >
              <span v-if="child.icon" class="navbar-dropdown-icon">{{ child.icon }}</span>
              <span>{{ child.label }}</span>
            </a>
          </div>
        </div>
      </div>

      <!-- Right Section -->
      <div class="navbar-actions">
        <!-- Search Bar Slot -->
        <div v-if="$slots.search" class="navbar-search">
          <slot name="search"></slot>
        </div>

        <!-- Notifications -->
        <div v-if="showNotifications" class="navbar-notification">
          <button class="navbar-notification-btn" :style="actionButtonStyles">
            <span class="navbar-notification-icon">🔔</span>
            <span v-if="notificationCount > 0" class="navbar-notification-badge" :style="badgeStyles">
              {{ notificationCount }}
            </span>
          </button>
        </div>

        <!-- User Profile Slot -->
        <div v-if="$slots.profile" class="navbar-profile">
          <slot name="profile"></slot>
        </div>

        <!-- Mobile Menu Toggle -->
        <button
          class="navbar-mobile-toggle"
          :style="actionButtonStyles"
          @click="toggleMobileMenu"
        >
          <span class="navbar-hamburger">{{ mobileMenuOpen ? '✕' : '☰' }}</span>
        </button>
      </div>
    </div>

    <!-- Mobile Menu Overlay -->
    <transition name="mobile-menu-blur">
      <div v-if="mobileMenuOpen" class="navbar-mobile-overlay" :style="mobileOverlayStyles">
        <div class="navbar-mobile-menu">
          <div
            v-for="item in items"
            :key="item.id"
            class="navbar-mobile-item-wrapper"
          >
            <a
              :href="item.route"
              :class="['navbar-mobile-item', { active: activeItem === item.id }]"
              :style="getMobileItemStyles(item.id)"
              @click="handleMobileItemClick(item)"
            >
              <span v-if="item.icon" class="navbar-mobile-icon">{{ item.icon }}</span>
              <span>{{ item.label }}</span>
              <span v-if="item.dropdown" class="navbar-mobile-arrow">▼</span>
            </a>

            <!-- Mobile Dropdown -->
            <div
              v-if="item.dropdown && item.dropdown.length && activeDropdown === item.id"
              class="navbar-mobile-dropdown"
            >
              <a
                v-for="child in item.dropdown"
                :key="child.id"
                :href="child.route"
                class="navbar-mobile-dropdown-item"
                @click="handleMobileItemClick(child)"
              >
                <span v-if="child.icon">{{ child.icon }}</span>
                <span>{{ child.label }}</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </transition>
  </nav>
</template>

<script setup lang="ts">
import { ref, computed, defineProps, withDefaults } from 'vue'

interface NavbarTheme {
  primary: string
  background: string
  text: string
  activeColor: string
  hoverColor: string
}

interface NavItem {
  id: string
  label: string
  icon?: string
  route: string
  dropdown?: NavItem[]
}

interface Props {
  items: NavItem[]
  logo?: string
  brandName?: string
  variant?: 'solid' | 'transparent' | 'blur' | 'gradient' | 'minimal'
  sticky?: boolean
  transparent?: boolean
  theme?: Partial<NavbarTheme>
  showNotifications?: boolean
  notificationCount?: number
}

const props = withDefaults(defineProps<Props>(), {
  items: () => [],
  brandName: 'Brand',
  variant: 'blur',
  sticky: false,
  transparent: false,
  theme: () => ({}),
  showNotifications: true,
  notificationCount: 0
})

// State
const mobileMenuOpen = ref(false)
const activeItem = ref<string | null>(null)
const hoveredItem = ref<string | null>(null)
const activeDropdown = ref<string | null>(null)

// Default theme for variant 5 - Blur Modern
const defaultTheme: NavbarTheme = {
  primary: '#8b5cf6',
  background: 'rgba(17, 24, 39, 0.75)',
  text: '#f3f4f6',
  activeColor: '#a78bfa',
  hoverColor: 'rgba(139, 92, 246, 0.2)'
}

const mergedTheme = computed<NavbarTheme>(() => ({
  ...defaultTheme,
  ...props.theme
}))

// Computed Styles
const navbarStyles = computed(() => ({
  backgroundColor: props.transparent ? 'transparent' : mergedTheme.value.background,
  color: mergedTheme.value.text,
  backdropFilter: 'blur(16px) saturate(200%)',
  WebkitBackdropFilter: 'blur(16px) saturate(200%)',
  borderBottom: `1px solid rgba(139, 92, 246, 0.3)`,
  boxShadow: '0 4px 30px rgba(0, 0, 0, 0.1)'
}))

const dropdownStyles = computed(() => ({
  backgroundColor: mergedTheme.value.background,
  backdropFilter: 'blur(16px) saturate(200%)',
  WebkitBackdropFilter: 'blur(16px) saturate(200%)',
  border: `1px solid rgba(139, 92, 246, 0.3)`,
  boxShadow: '0 8px 32px rgba(139, 92, 246, 0.15)'
}))

const dropdownItemStyles = computed(() => ({
  color: mergedTheme.value.text
}))

const actionButtonStyles = computed(() => ({
  color: mergedTheme.value.text,
  backgroundColor: 'rgba(139, 92, 246, 0.15)',
  border: '1px solid rgba(139, 92, 246, 0.3)',
  backdropFilter: 'blur(8px)',
  WebkitBackdropFilter: 'blur(8px)'
}))

const badgeStyles = computed(() => ({
  backgroundColor: mergedTheme.value.activeColor,
  color: '#111827',
  fontWeight: '700',
  boxShadow: `0 0 16px ${mergedTheme.value.activeColor}`
}))

const mobileOverlayStyles = computed(() => ({
  backgroundColor: mergedTheme.value.background,
  backdropFilter: 'blur(16px) saturate(200%)',
  WebkitBackdropFilter: 'blur(16px) saturate(200%)'
}))

// Methods
const getItemStyles = (itemId: string) => {
  const isActive = activeItem.value === itemId
  const isHovered = hoveredItem.value === itemId

  return {
    color: isActive ? mergedTheme.value.activeColor : mergedTheme.value.text,
    backgroundColor: isHovered || isActive ? mergedTheme.value.hoverColor : 'transparent',
    borderRadius: '10px',
    boxShadow: isActive ? `0 0 20px rgba(139, 92, 246, 0.3)` : 'none',
    backdropFilter: isHovered || isActive ? 'blur(8px)' : 'none'
  }
}

const getMobileItemStyles = (itemId: string) => ({
  color: activeItem.value === itemId ? mergedTheme.value.activeColor : mergedTheme.value.text,
  backgroundColor: activeItem.value === itemId ? mergedTheme.value.hoverColor : 'transparent',
  backdropFilter: activeItem.value === itemId ? 'blur(8px)' : 'none'
})

const handleMouseEnter = (itemId: string) => {
  hoveredItem.value = itemId
}

const handleMouseLeave = () => {
  hoveredItem.value = null
}

const handleItemClick = (item: NavItem) => {
  if (item.dropdown && item.dropdown.length) {
    activeDropdown.value = activeDropdown.value === item.id ? null : item.id
  } else {
    activeItem.value = item.id
    activeDropdown.value = null
  }
}

const handleMobileItemClick = (item: NavItem) => {
  if (item.dropdown && item.dropdown.length) {
    activeDropdown.value = activeDropdown.value === item.id ? null : item.id
  } else {
    activeItem.value = item.id
    mobileMenuOpen.value = false
    activeDropdown.value = null
  }
}

const toggleMobileMenu = () => {
  mobileMenuOpen.value = !mobileMenuOpen.value
}
</script>

<style scoped>
.navbar {
  position: relative;
  width: 100%;
  padding: 0;
  transition: all 0.35s cubic-bezier(0.4, 0, 0.2, 1);
}

.navbar-sticky {
  position: sticky;
  top: 0;
  z-index: 1000;
}

.navbar-container {
  max-width: 1400px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 2rem;
}

.navbar-brand {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-size: 1.5rem;
  font-weight: 700;
  cursor: pointer;
  transition: all 0.3s ease;
  text-shadow: 0 2px 10px rgba(139, 92, 246, 0.5);
  letter-spacing: 0.5px;
}

.navbar-brand:hover {
  transform: scale(1.05);
  text-shadow: 0 4px 20px rgba(139, 92, 246, 0.8);
}

.navbar-logo {
  height: 40px;
  width: auto;
  filter: drop-shadow(0 2px 8px rgba(139, 92, 246, 0.4));
}

.navbar-menu {
  display: none;
  gap: 0.625rem;
  flex: 1;
  justify-content: center;
}

@media (min-width: 768px) {
  .navbar-menu {
    display: flex;
  }
}

.navbar-item-wrapper {
  position: relative;
}

.navbar-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.875rem 1.5rem;
  text-decoration: none;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  font-weight: 600;
  white-space: nowrap;
  font-size: 0.925rem;
  letter-spacing: 0.3px;
}

.navbar-item:hover {
  transform: translateY(-2px);
}

.navbar-item.active {
  font-weight: 700;
}

.navbar-item-icon {
  font-size: 1.125rem;
  transition: transform 0.3s ease;
}

.navbar-item:hover .navbar-item-icon {
  transform: scale(1.15) rotate(5deg);
}

.navbar-item-arrow {
  font-size: 0.7rem;
  margin-left: 0.25rem;
  transition: transform 0.3s ease;
}

.navbar-item:hover .navbar-item-arrow {
  transform: translateY(2px);
}

.navbar-dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  min-width: 220px;
  margin-top: 0.625rem;
  padding: 0.75rem;
  border-radius: 14px;
  opacity: 0;
  visibility: hidden;
  transform: translateY(-12px) scale(0.95);
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  z-index: 100;
}

.navbar-dropdown.active {
  opacity: 1;
  visibility: visible;
  transform: translateY(0) scale(1);
}

.navbar-dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.875rem 1.125rem;
  text-decoration: none;
  border-radius: 10px;
  transition: all 0.25s ease;
  font-weight: 500;
  letter-spacing: 0.25px;
}

.navbar-dropdown-item:hover {
  background-color: rgba(139, 92, 246, 0.2);
  transform: translateX(5px);
  box-shadow: 0 4px 12px rgba(139, 92, 246, 0.2);
  backdrop-filter: blur(8px);
}

.navbar-dropdown-icon {
  font-size: 1.05rem;
}

.navbar-actions {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.navbar-search {
  display: none;
}

@media (min-width: 768px) {
  .navbar-search {
    display: block;
  }
}

.navbar-notification {
  position: relative;
}

.navbar-notification-btn {
  position: relative;
  border-radius: 12px;
  width: 44px;
  height: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.3s ease;
}

.navbar-notification-btn:hover {
  transform: scale(1.12);
  background-color: rgba(139, 92, 246, 0.25);
  box-shadow: 0 6px 20px rgba(139, 92, 246, 0.3);
}

.navbar-notification-icon {
  font-size: 1.25rem;
}

.navbar-notification-badge {
  position: absolute;
  top: -3px;
  right: -3px;
  min-width: 20px;
  height: 20px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.7rem;
  padding: 0 6px;
  animation: glow 2s ease-in-out infinite;
}

@keyframes glow {
  0%, 100% {
    box-shadow: 0 0 16px currentColor;
  }
  50% {
    box-shadow: 0 0 24px currentColor;
  }
}

.navbar-mobile-toggle {
  display: flex;
  border-radius: 12px;
  padding: 0.625rem 0.875rem;
  cursor: pointer;
  transition: all 0.3s ease;
}

@media (min-width: 768px) {
  .navbar-mobile-toggle {
    display: none;
  }
}

.navbar-mobile-toggle:hover {
  transform: scale(1.1);
  box-shadow: 0 4px 16px rgba(139, 92, 246, 0.3);
}

.navbar-hamburger {
  font-size: 1.5rem;
}

.navbar-mobile-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100vh;
  z-index: 999;
  overflow-y: auto;
  padding-top: 85px;
}

@media (min-width: 768px) {
  .navbar-mobile-overlay {
    display: none;
  }
}

.navbar-mobile-menu {
  padding: 2rem 1.5rem;
}

.navbar-mobile-item-wrapper {
  margin-bottom: 0.625rem;
}

.navbar-mobile-item {
  display: flex;
  align-items: center;
  gap: 0.875rem;
  padding: 1.125rem 1.75rem;
  text-decoration: none;
  border-radius: 14px;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  font-size: 1.1rem;
  font-weight: 600;
  letter-spacing: 0.3px;
  border: 1px solid rgba(139, 92, 246, 0.2);
}

.navbar-mobile-icon {
  font-size: 1.35rem;
}

.navbar-mobile-arrow {
  margin-left: auto;
  font-size: 0.85rem;
  transition: transform 0.3s ease;
}

.navbar-mobile-dropdown {
  margin-left: 2.25rem;
  margin-top: 0.625rem;
  animation: dropdownSlide 0.3s ease;
}

@keyframes dropdownSlide {
  from {
    opacity: 0;
    transform: translateY(-8px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.navbar-mobile-dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.875rem 1.5rem;
  text-decoration: none;
  border-radius: 10px;
  transition: all 0.25s ease;
  opacity: 0.9;
  font-weight: 500;
  margin-bottom: 0.375rem;
  border: 1px solid rgba(139, 92, 246, 0.15);
  backdrop-filter: blur(8px);
}

.navbar-mobile-dropdown-item:hover {
  background-color: rgba(139, 92, 246, 0.2);
  opacity: 1;
  transform: translateX(6px);
  box-shadow: 0 4px 12px rgba(139, 92, 246, 0.2);
}

.mobile-menu-blur-enter-active,
.mobile-menu-blur-leave-active {
  transition: all 0.35s cubic-bezier(0.4, 0, 0.2, 1);
}

.mobile-menu-blur-enter-from {
  opacity: 0;
  backdrop-filter: blur(0px);
  transform: translateX(100%);
}

.mobile-menu-blur-leave-to {
  opacity: 0;
  backdrop-filter: blur(0px);
  transform: translateX(100%);
}
</style>

// snippets/components/angular/navbar/19/navbar.component.ts
import { Component, Input, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';

interface NavbarTheme {
  primaryColor: string;
  secondaryColor: string;
  backgroundColor: string;
  textColor: string;
  borderColor: string;
  accentColor: string;
}

interface MenuItem {
  label: string;
  route: string;
  icon?: string;
}

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule],
  template: `
  <nav [ngStyle]="navbarStyles" [class.scrolled]="isScrolled" role="navigation">
  <div class="container" [ngStyle]="containerStyles">
  <div class="brand" [ngStyle]="brandStyles">
  <div class="icon" [ngStyle]="iconStyles">👑</div>
  <span class="name">Gold</span>
  </div>
  
  <div class="menu" [ngStyle]="menuStyles" [class.active]="isMobileMenuOpen">
  <a *ngFor="let item of menuItems; let i = index"
  [href]="item.route"
  [ngStyle]="getItemStyles(i)"
  [class.active]="item.route === activeRoute"
  [attr.aria-current]="item.route === activeRoute ? 'page' : null"
  (mouseenter)="hoveredIndex = i"
  (mouseleave)="hoveredIndex = null">
  <span *ngIf="item.icon">{{item.icon}}</span>
  {{item.label}}
  </a>
  </div>
  
  <div class="actions" [ngStyle]="actionsStyles">
  <div *ngIf="showSearch" class="search">
  <input type="search" placeholder="Explore..." aria-label="Search" [ngStyle]="searchStyles">
  </div>
  <button *ngIf="showNotifications" [ngStyle]="notifStyles" aria-label="Notifications">
  🔔<span *ngIf="notificationCount > 0" class="badge" [ngStyle]="badgeStyles">{{notificationCount}}</span>
  </button>
  <div *ngIf="showUserProfile" [ngStyle]="profileStyles">
  <img [src]="userAvatar" alt="{{userName}}" class="avatar" [ngStyle]="avatarStyles">
  <span>{{userName}}</span>
  </div>
  </div>
  
  <button class="toggle" (click)="toggleMobileMenu()" [attr.aria-expanded]="isMobileMenuOpen" aria-label="Menu">
  <span></span><span></span><span></span>
  </button>
  </div>
  </nav>
  `,
  styles: [`
  nav { transition: all 0.3s cubic-bezier(0.4, 0, 0.6, 1); }
  nav.scrolled { box-shadow: 0 10px 35px rgba(251, 191, 36,0.20); backdrop-filter: blur(15px); }
  .container { display: flex; align-items: center; justify-content: space-between; max-width: 1450px; margin: 0 auto; padding: 1.25rem 2.5rem; gap: 2.25rem; }
  .brand { display: flex; align-items: center; gap: 1.1rem; cursor: pointer; font-weight: 900; }
  .icon { font-size: 1.9rem; transition: transform 0.3s ease-in-out; }
  .icon:hover { transform: scale(1.25) rotate(-10deg); }
  .name { font-size: 1.7rem; font-weight: 900; letter-spacing: -0.6px; }
  .menu { display: flex; gap: 0.7rem; flex: 1; justify-content: center; }
  .menu a { padding: 0.9rem 1.5rem; border-radius: 0.8rem; text-decoration: none; transition: all 0.26s ease; font-weight: 550; display: flex; align-items: center; gap: 0.5rem; position: relative; }
  .menu a:hover { transform: translateY(-3px) scale(1.02); background-color: rgba(0,0,0,0.06); }
  .menu a.active { font-weight: 700; }
  .menu a.active::after { content: ''; position: absolute; bottom: 0px; left: 50%; transform: translateX(-50%); width: 32px; height: 3.5px; background: currentColor; border-radius: 2.5px; }
  .actions { display: flex; gap: 1.3rem; align-items: center; }
  .search input { padding: 0.7rem 1.3rem; border-radius: 2rem; border: 2px solid; outline: none; transition: all 0.28s; width: 240px; }
  .search input:focus { transform: scale(1.04); box-shadow: 0 0 12px rgba(0,0,0,0.1); }
  button { position: relative; background: none; border: none; cursor: pointer; padding: 0.7rem; font-size: 1.3rem; transition: transform 0.25s; border-radius: 0.7rem; }
  button:hover { transform: scale(1.12); }
  .badge { position: absolute; top: 0px; right: 0px; font-size: 0.75rem; min-width: 20px; height: 20px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: 800; animation: pulse 1.5s infinite; }
  @keyframes pulse { 0%, 100% { transform: scale(1); } 50% { transform: scale(1.22); } }
  .avatar { width: 40px; height: 40px; border-radius: 50%; object-fit: cover; border: 3px solid; }
  .toggle { display: none; flex-direction: column; gap: 0.32rem; }
  .toggle span { width: 27px; height: 3px; background: currentColor; border-radius: 2.5px; transition: all 0.3s; }
  @media (max-width: 768px) { .menu, .search { display: none; } .toggle { display: flex; } .menu.active { display: flex; position: absolute; top: 100%; left: 0; right: 0; flex-direction: column; padding: 1.75rem; animation: slideDown 0.28s; } @keyframes slideDown { from { opacity: 0; transform: translateY(-15px); } to { opacity: 1; transform: translateY(0); } } }
  `]
})
export class NavbarComponent {
  @Input() theme: Partial<NavbarTheme> = {};
  @Input() variant: 'solid' | 'transparent' | 'blur' | 'gradient' = 'gradient';
  @Input() position: 'static' | 'sticky' | 'fixed' = 'sticky';
  @Input() brandName = 'Gold';
  @Input() menuItems: MenuItem[] = [{ label: 'Crown', route: '/', icon: '👑' }, { label: 'Royal', route: '/royal', icon: '💎' }, { label: 'Luxury', route: '/luxury', icon: '✨' }];
  @Input() activeRoute = '/';
  @Input() showSearch = true;
  @Input() showNotifications = true;
  @Input() showUserProfile = true;
  @Input() notificationCount = 88;
  @Input() userName = 'Regal';
  @Input() userAvatar = 'https://i.pravatar.cc/150?img=23';

  private defaultTheme: NavbarTheme = {
  primaryColor: '#fbbf24',
  secondaryColor: '#f59e0b',
  backgroundColor: '#fefce8',
  textColor: '#713f12',
  borderColor: '#fde68a',
  accentColor: '#8b5cf6'
  };

  isMobileMenuOpen = false;
  isScrolled = false;
  hoveredIndex: number | null = null;

  get appliedTheme(): NavbarTheme {
  return { ...this.defaultTheme, ...this.theme };
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
  this.isScrolled = window.scrollY > 25;
  }

  toggleMobileMenu() {
  this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }

  get navbarStyles() {
  const variants = {
  solid: { backgroundColor: this.appliedTheme.backgroundColor, borderBottom: `2px solid ${this.appliedTheme.borderColor}`, boxShadow: '0 4px 6px rgba(0,0,0,0.12)' },
  transparent: { backgroundColor: `${this.appliedTheme.backgroundColor}DD`, backdropFilter: 'blur(15px)' },
  blur: { backgroundColor: `${this.appliedTheme.backgroundColor}AD`, backdropFilter: 'blur(20px) saturate(190%)' },
  gradient: { background: `linear-gradient(110deg, ${this.appliedTheme.primaryColor}, ${this.appliedTheme.secondaryColor})` }
  };
  return {
  position: this.position,
  top: '0',
  left: '0',
  right: '0',
  zIndex: '1100',
  color: this.appliedTheme.textColor,
  ...variants[this.variant]
  };
  }

  get containerStyles() { return {}; }
  get brandStyles() { return { color: this.appliedTheme.primaryColor }; }
  get iconStyles() { return { color: this.appliedTheme.accentColor }; }
  get menuStyles() { return {}; }
  get actionsStyles() { return {}; }
  get searchStyles() { return { borderColor: this.appliedTheme.borderColor, color: this.appliedTheme.textColor, backgroundColor: `${this.appliedTheme.backgroundColor}95` }; }
  get notifStyles() { return { color: this.appliedTheme.textColor, backgroundColor: `${this.appliedTheme.primaryColor}22` }; }
  get badgeStyles() { return { backgroundColor: this.appliedTheme.accentColor, color: '#ffffff' }; }
  get profileStyles() { return { color: this.appliedTheme.textColor, backgroundColor: `${this.appliedTheme.primaryColor}20`, padding: '0.6rem 1.1rem', borderRadius: '2.5rem' }; }
  get avatarStyles() { return { borderColor: this.appliedTheme.secondaryColor }; }

  getItemStyles(index: number) {
  const isActive = this.menuItems[index].route === this.activeRoute;
  const isHovered = this.hoveredIndex === index;
  return {
  color: this.appliedTheme.textColor,
  backgroundColor: isActive ? `${this.appliedTheme.primaryColor}30` : isHovered ? `${this.appliedTheme.primaryColor}18` : 'transparent',
  boxShadow: isActive ? `0 5px 15px rgba(0,0,0,0.12)` : 'none'
  };
  }
}
